/*
 * Copyright (c) 2025-2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CK1025GC01064_PINCTRL_H_
#define MICROCHIP_PIC32CK1025GC01064_PINCTRL_H_

#include <dt-bindings/pic32c/pic32ck_gc/common/mchp_pinctrl_pinmux_pic32c.h>

#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

#define PA0A_EIC_EXTINT14 MCHP_PINMUX(a, 0, a, periph)

#define PA0D_SERCOM6_PAD0 MCHP_PINMUX(a, 0, d, periph)

#define PA0F_TCC2_WO0 MCHP_PINMUX(a, 0, f, periph)

#define PA0G_BSDAP_TDI MCHP_PINMUX(a, 0, g, periph)

#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

#define PA1A_EIC_EXTINT1 MCHP_PINMUX(a, 1, a, periph)

#define PA1C_SERCOM7_PAD0 MCHP_PINMUX(a, 1, c, periph)

#define PA1D_SERCOM6_PAD1 MCHP_PINMUX(a, 1, d, periph)

#define PA1F_TCC2_WO3 MCHP_PINMUX(a, 1, f, periph)

#define PA1G_BSDAP_TDO MCHP_PINMUX(a, 1, g, periph)

#define PA1M_GCLK_IO1 MCHP_PINMUX(a, 1, m, periph)

#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

#define PA2D_SERCOM6_PAD2 MCHP_PINMUX(a, 2, d, periph)

#define PA2G_BSDAP_TMS_SWDIO MCHP_PINMUX(a, 2, g, periph)

#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

#define PA3D_SERCOM6_PAD3 MCHP_PINMUX(a, 3, d, periph)

#define PA3G_BSDAP_TCK_SWCLK MCHP_PINMUX(a, 3, g, periph)

#define PA3M_GCLK_IO0 MCHP_PINMUX(a, 3, m, periph)

#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

#define PA4B_ADC_VINP0 MCHP_PINMUX(a, 4, b, periph)

#define PA4C_SERCOM7_PAD1 MCHP_PINMUX(a, 4, c, periph)

#define PA4F_TCC3_WO0 MCHP_PINMUX(a, 4, f, periph)

#define PA4M_CCL_IN9 MCHP_PINMUX(a, 4, m, periph)

#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

#define PA5A_EIC_EXTINT5 MCHP_PINMUX(a, 5, a, periph)

#define PA5B_ADC_VINM0 MCHP_PINMUX(a, 5, b, periph)

#define PA5B_ADC_VINP1 MCHP_PINMUX(a, 5, b, periph)

#define PA5C_SERCOM7_PAD2 MCHP_PINMUX(a, 5, c, periph)

#define PA5D_SERCOM5_PAD0 MCHP_PINMUX(a, 5, d, periph)

#define PA5F_TCC3_WO1 MCHP_PINMUX(a, 5, f, periph)

#define PA5M_CCL_IN10 MCHP_PINMUX(a, 5, m, periph)

#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

#define PA6B_AC_AIN0 MCHP_PINMUX(a, 6, b, periph)

#define PA6B_ADC_VINP2 MCHP_PINMUX(a, 6, b, periph)

#define PA6C_SERCOM7_PAD3 MCHP_PINMUX(a, 6, c, periph)

#define PA6D_SERCOM5_PAD1 MCHP_PINMUX(a, 6, d, periph)

#define PA6F_TCC3_WO2 MCHP_PINMUX(a, 6, f, periph)

#define PA6M_CCL_IN11 MCHP_PINMUX(a, 6, m, periph)

#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

#define PA7A_EIC_EXTINT7 MCHP_PINMUX(a, 7, a, periph)

#define PA7B_AC_AIN1 MCHP_PINMUX(a, 7, b, periph)

#define PA7B_ADC_VINM2 MCHP_PINMUX(a, 7, b, periph)

#define PA7B_ADC_VINP3 MCHP_PINMUX(a, 7, b, periph)

#define PA7C_SERCOM6_PAD0 MCHP_PINMUX(a, 7, c, periph)

#define PA7D_SERCOM5_PAD2 MCHP_PINMUX(a, 7, d, periph)

#define PA7F_TCC3_WO3 MCHP_PINMUX(a, 7, f, periph)

#define PA7M_CCL_OUT3 MCHP_PINMUX(a, 7, m, periph)

#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

#define PA8A_EIC_EXTINT8 MCHP_PINMUX(a, 8, a, periph)

#define PA8B_ADC_VINP4 MCHP_PINMUX(a, 8, b, periph)

#define PA8C_SERCOM6_PAD1 MCHP_PINMUX(a, 8, c, periph)

#define PA8D_SERCOM5_PAD3 MCHP_PINMUX(a, 8, d, periph)

#define PA8F_TCC3_WO4 MCHP_PINMUX(a, 8, f, periph)

#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

#define PA9B_ADC_VINP5 MCHP_PINMUX(a, 9, b, periph)

#define PA9C_SERCOM6_PAD2 MCHP_PINMUX(a, 9, c, periph)

#define PA9D_SERCOM6_PAD3 MCHP_PINMUX(a, 9, d, periph)

#define PA9G_TCC3_WO0 MCHP_PINMUX(a, 9, g, periph)

#define PA9J_SPI_IXS_FSYNC MCHP_PINMUX(a, 9, j, periph)

#define PA9M_GCLK_IO0 MCHP_PINMUX(a, 9, m, periph)

#define PA9N_PTC_DRV0 MCHP_PINMUX(a, 9, n, periph)

#define PA10_GPIO MCHP_PINMUX(a, 10, gpio, gpio)

#define PA10A_EIC_EXTINT10 MCHP_PINMUX(a, 10, a, periph)

#define PA10B_ADC_VINP6 MCHP_PINMUX(a, 10, b, periph)

#define PA10C_SERCOM6_PAD3 MCHP_PINMUX(a, 10, c, periph)

#define PA10G_TCC3_WO1 MCHP_PINMUX(a, 10, g, periph)

#define PA10H_SQI_CS2 MCHP_PINMUX(a, 10, h, periph)

#define PA10I_SDMMC0_SDCD MCHP_PINMUX(a, 10, i, periph)

#define PA10K_PCC_DEN1 MCHP_PINMUX(a, 10, k, periph)

#define PA10M_GCLK_IO1 MCHP_PINMUX(a, 10, m, periph)

#define PA10N_PTC_DRV1 MCHP_PINMUX(a, 10, n, periph)

#define PA11_GPIO MCHP_PINMUX(a, 11, gpio, gpio)

#define PA11A_EIC_EXTINT11 MCHP_PINMUX(a, 11, a, periph)

#define PA11B_ADC_VINP7 MCHP_PINMUX(a, 11, b, periph)

#define PA11C_SERCOM5_PAD0 MCHP_PINMUX(a, 11, c, periph)

#define PA11D_SERCOM7_PAD1 MCHP_PINMUX(a, 11, d, periph)

#define PA11F_TCC4_WO0 MCHP_PINMUX(a, 11, f, periph)

#define PA11G_TCC3_WO2 MCHP_PINMUX(a, 11, g, periph)

#define PA11J_SPI_IXS_SCK MCHP_PINMUX(a, 11, j, periph)

#define PA11L_ETH_MDC MCHP_PINMUX(a, 11, l, periph)

#define PA11M_AC_CMP0 MCHP_PINMUX(a, 11, m, periph)

#define PA11N_PTC_DRV2 MCHP_PINMUX(a, 11, n, periph)

#define PA12_GPIO MCHP_PINMUX(a, 12, gpio, gpio)

#define PA12A_EIC_EXTINT12 MCHP_PINMUX(a, 12, a, periph)

#define PA12B_ADC_VINP8 MCHP_PINMUX(a, 12, b, periph)

#define PA12C_SERCOM5_PAD1 MCHP_PINMUX(a, 12, c, periph)

#define PA12D_SERCOM7_PAD0 MCHP_PINMUX(a, 12, d, periph)

#define PA12F_TCC4_WO1 MCHP_PINMUX(a, 12, f, periph)

#define PA12G_TCC3_WO3 MCHP_PINMUX(a, 12, g, periph)

#define PA12I_SDMMC0_SDCD MCHP_PINMUX(a, 12, i, periph)

#define PA12J_SPI_IXS_SDI MCHP_PINMUX(a, 12, j, periph)

#define PA12L_ETH_MDIO MCHP_PINMUX(a, 12, l, periph)

#define PA12M_AC_CMP1 MCHP_PINMUX(a, 12, m, periph)

#define PA12N_PTC_DRV3 MCHP_PINMUX(a, 12, n, periph)

#define PB0_GPIO MCHP_PINMUX(b, 0, gpio, gpio)

#define PB0A_EIC_EXTINT0 MCHP_PINMUX(b, 0, a, periph)

#define PB0B_ADC_VINP9 MCHP_PINMUX(b, 0, b, periph)

#define PB0C_SERCOM5_PAD2 MCHP_PINMUX(b, 0, c, periph)

#define PB0D_SERCOM7_PAD2 MCHP_PINMUX(b, 0, d, periph)

#define PB0F_TCC5_WO0 MCHP_PINMUX(b, 0, f, periph)

#define PB0G_TCC3_WO4 MCHP_PINMUX(b, 0, g, periph)

#define PB0H_CAN1_TX MCHP_PINMUX(b, 0, h, periph)

#define PB0I_SDMMC0_SDWP MCHP_PINMUX(b, 0, i, periph)

#define PB0J_SPI_IXS_SDO MCHP_PINMUX(b, 0, j, periph)

#define PB0N_PTC_DRV4 MCHP_PINMUX(b, 0, n, periph)

#define PB1_GPIO MCHP_PINMUX(b, 1, gpio, gpio)

#define PB1A_EIC_EXTINT1 MCHP_PINMUX(b, 1, a, periph)

#define PB1B_ADC_VREFP0 MCHP_PINMUX(b, 1, b, periph)

#define PB1C_SERCOM5_PAD3 MCHP_PINMUX(b, 1, c, periph)

#define PB1D_SERCOM7_PAD3 MCHP_PINMUX(b, 1, d, periph)

#define PB1F_TCC5_WO1 MCHP_PINMUX(b, 1, f, periph)

#define PB1G_TCC3_WO5 MCHP_PINMUX(b, 1, g, periph)

#define PB1H_CAN1_RX MCHP_PINMUX(b, 1, h, periph)

#define PB1N_PTC_DRV5 MCHP_PINMUX(b, 1, n, periph)

#define PB2_GPIO MCHP_PINMUX(b, 2, gpio, gpio)

#define PB2A_EIC_EXTINT2 MCHP_PINMUX(b, 2, a, periph)

#define PB3_GPIO MCHP_PINMUX(b, 3, gpio, gpio)

#define PB3A_EIC_EXTINT3 MCHP_PINMUX(b, 3, a, periph)

#define PB4_GPIO MCHP_PINMUX(b, 4, gpio, gpio)

#define PB4A_EIC_EXTINT4 MCHP_PINMUX(b, 4, a, periph)

#define PB4C_SERCOM4_PAD0 MCHP_PINMUX(b, 4, c, periph)

#define PB4F_TCC0_WO0 MCHP_PINMUX(b, 4, f, periph)

#define PB4G_PDEC_QDI0 MCHP_PINMUX(b, 4, g, periph)

#define PB5_GPIO MCHP_PINMUX(b, 5, gpio, gpio)

#define PB5A_EIC_EXTINT5 MCHP_PINMUX(b, 5, a, periph)

#define PB5C_SERCOM4_PAD1 MCHP_PINMUX(b, 5, c, periph)

#define PB5F_TCC0_WO1 MCHP_PINMUX(b, 5, f, periph)

#define PB5G_PDEC_QDI1 MCHP_PINMUX(b, 5, g, periph)

#define PB6_GPIO MCHP_PINMUX(b, 6, gpio, gpio)

#define PB6A_EIC_EXTINT6 MCHP_PINMUX(b, 6, a, periph)

#define PB6C_SERCOM4_PAD3 MCHP_PINMUX(b, 6, c, periph)

#define PB6F_TCC0_WO3 MCHP_PINMUX(b, 6, f, periph)

#define PB7_GPIO MCHP_PINMUX(b, 7, gpio, gpio)

#define PB7A_EIC_EXTINT7 MCHP_PINMUX(b, 7, a, periph)

#define PB7C_SERCOM3_PAD2 MCHP_PINMUX(b, 7, c, periph)

#define PB7D_SERCOM4_PAD2 MCHP_PINMUX(b, 7, d, periph)

#define PB7F_TCC7_WO0 MCHP_PINMUX(b, 7, f, periph)

#define PB7G_PDEC_QDI0 MCHP_PINMUX(b, 7, g, periph)

#define PB7I_SDMMC1_SDCMD MCHP_PINMUX(b, 7, i, periph)

#define PB7K_PCC_DATA3 MCHP_PINMUX(b, 7, k, periph)

#define PB7M_CCL_IN0 MCHP_PINMUX(b, 7, m, periph)

#define PB7N_PTC_DRV6 MCHP_PINMUX(b, 7, n, periph)

#define PB8_GPIO MCHP_PINMUX(b, 8, gpio, gpio)

#define PB8A_EIC_EXTINT8 MCHP_PINMUX(b, 8, a, periph)

#define PB8C_SERCOM3_PAD3 MCHP_PINMUX(b, 8, c, periph)

#define PB8D_SERCOM4_PAD3 MCHP_PINMUX(b, 8, d, periph)

#define PB8F_TCC7_WO1 MCHP_PINMUX(b, 8, f, periph)

#define PB8G_PDEC_QDI1 MCHP_PINMUX(b, 8, g, periph)

#define PB8H_CAN0_TX MCHP_PINMUX(b, 8, h, periph)

#define PB8K_PCC_DATA4 MCHP_PINMUX(b, 8, k, periph)

#define PB8M_CCL_IN1 MCHP_PINMUX(b, 8, m, periph)

#define PB8N_PTC_DRV7 MCHP_PINMUX(b, 8, n, periph)

#define PB9_GPIO MCHP_PINMUX(b, 9, gpio, gpio)

#define PB9A_EIC_EXTINT9 MCHP_PINMUX(b, 9, a, periph)

#define PB9C_SERCOM4_PAD0 MCHP_PINMUX(b, 9, c, periph)

#define PB9D_SERCOM4_PAD1 MCHP_PINMUX(b, 9, d, periph)

#define PB9G_PDEC_QDI2 MCHP_PINMUX(b, 9, g, periph)

#define PB9H_CAN0_RX MCHP_PINMUX(b, 9, h, periph)

#define PB9K_PCC_DATA5 MCHP_PINMUX(b, 9, k, periph)

#define PB9M_CCL_IN2 MCHP_PINMUX(b, 9, m, periph)

#define PB9N_PTC_DRV8 MCHP_PINMUX(b, 9, n, periph)

#define PB10_GPIO MCHP_PINMUX(b, 10, gpio, gpio)

#define PB10A_EIC_EXTINT10 MCHP_PINMUX(b, 10, a, periph)

#define PB10C_SERCOM4_PAD1 MCHP_PINMUX(b, 10, c, periph)

#define PB10D_SERCOM4_PAD0 MCHP_PINMUX(b, 10, d, periph)

#define PB10G_TCC0_WO0 MCHP_PINMUX(b, 10, g, periph)

#define PB10I_SDMMC1_SDDAT0 MCHP_PINMUX(b, 10, i, periph)

#define PB10K_PCC_DATA6 MCHP_PINMUX(b, 10, k, periph)

#define PB10L_ETH_MDC MCHP_PINMUX(b, 10, l, periph)

#define PB10M_CCL_OUT0 MCHP_PINMUX(b, 10, m, periph)

#define PB10N_PTC_DRV9 MCHP_PINMUX(b, 10, n, periph)

#define PC0_GPIO MCHP_PINMUX(c, 0, gpio, gpio)

#define PC0A_EIC_EXTINT0 MCHP_PINMUX(c, 0, a, periph)

#define PC0C_SERCOM4_PAD2 MCHP_PINMUX(c, 0, c, periph)

#define PC0G_TCC0_WO1 MCHP_PINMUX(c, 0, g, periph)

#define PC0I_SDMMC1_SDDAT1 MCHP_PINMUX(c, 0, i, periph)

#define PC0K_PCC_DATA7 MCHP_PINMUX(c, 0, k, periph)

#define PC0L_ETH_REF_CLK MCHP_PINMUX(c, 0, l, periph)

#define PC0L_ETH_TX_CLK MCHP_PINMUX(c, 0, l, periph)

#define PC0M_GCLK_IO2 MCHP_PINMUX(c, 0, m, periph)

#define PC0N_PTC_DRV10 MCHP_PINMUX(c, 0, n, periph)

#define PC1_GPIO MCHP_PINMUX(c, 1, gpio, gpio)

#define PC1A_EIC_EXTINT1 MCHP_PINMUX(c, 1, a, periph)

#define PC1C_SERCOM4_PAD3 MCHP_PINMUX(c, 1, c, periph)

#define PC1F_TCC6_WO0 MCHP_PINMUX(c, 1, f, periph)

#define PC1G_TCC0_WO2 MCHP_PINMUX(c, 1, g, periph)

#define PC1H_USB_SOF_1KHZ MCHP_PINMUX(c, 1, h, periph)

#define PC1I_SDMMC1_SDDAT2 MCHP_PINMUX(c, 1, i, periph)

#define PC1K_PCC_DATA0 MCHP_PINMUX(c, 1, k, periph)

#define PC1M_GCLK_IO3 MCHP_PINMUX(c, 1, m, periph)

#define PC1N_PTC_DRV11 MCHP_PINMUX(c, 1, n, periph)

#define PC2_GPIO MCHP_PINMUX(c, 2, gpio, gpio)

#define PC2A_EIC_EXTINT2 MCHP_PINMUX(c, 2, a, periph)

#define PC2C_SERCOM3_PAD0 MCHP_PINMUX(c, 2, c, periph)

#define PC2F_TCC6_WO1 MCHP_PINMUX(c, 2, f, periph)

#define PC2G_TCC0_WO3 MCHP_PINMUX(c, 2, g, periph)

#define PC2H_CAN0_TX MCHP_PINMUX(c, 2, h, periph)

#define PC2I_SDMMC1_SDDAT3 MCHP_PINMUX(c, 2, i, periph)

#define PC2K_PCC_DATA1 MCHP_PINMUX(c, 2, k, periph)

#define PC2L_ETH_MDIO MCHP_PINMUX(c, 2, l, periph)

#define PC2M_GCLK_IO4 MCHP_PINMUX(c, 2, m, periph)

#define PC2N_PTC_DRV12 MCHP_PINMUX(c, 2, n, periph)

#define PC3_GPIO MCHP_PINMUX(c, 3, gpio, gpio)

#define PC3A_EIC_EXTINT3 MCHP_PINMUX(c, 3, a, periph)

#define PC3C_SERCOM3_PAD1 MCHP_PINMUX(c, 3, c, periph)

#define PC3F_TCC7_WO0 MCHP_PINMUX(c, 3, f, periph)

#define PC3G_TCC0_WO4 MCHP_PINMUX(c, 3, g, periph)

#define PC3H_CAN0_RX MCHP_PINMUX(c, 3, h, periph)

#define PC3I_SDMMC1_SDWP MCHP_PINMUX(c, 3, i, periph)

#define PC3K_PCC_DATA2 MCHP_PINMUX(c, 3, k, periph)

#define PC3L_ETH_MDC MCHP_PINMUX(c, 3, l, periph)

#define PC3M_GCLK_IO5 MCHP_PINMUX(c, 3, m, periph)

#define PC3N_PTC_DRV13 MCHP_PINMUX(c, 3, n, periph)

#define PC4_GPIO MCHP_PINMUX(c, 4, gpio, gpio)

#define PC4A_EIC_EXTINT4 MCHP_PINMUX(c, 4, a, periph)

#define PC4C_SERCOM3_PAD2 MCHP_PINMUX(c, 4, c, periph)

#define PC4F_TCC7_WO1 MCHP_PINMUX(c, 4, f, periph)

#define PC4G_TCC0_WO5 MCHP_PINMUX(c, 4, g, periph)

#define PC4I_SDMMC1_SDCD MCHP_PINMUX(c, 4, i, periph)

#define PC4K_PCC_DEN1 MCHP_PINMUX(c, 4, k, periph)

#define PC4L_ETH_MDIO MCHP_PINMUX(c, 4, l, periph)

#define PC4M_GCLK_IO6 MCHP_PINMUX(c, 4, m, periph)

#define PC4N_PTC_DRV14 MCHP_PINMUX(c, 4, n, periph)

#define PC5_GPIO MCHP_PINMUX(c, 5, gpio, gpio)

#define PC5A_EIC_EXTINT5 MCHP_PINMUX(c, 5, a, periph)

#define PC5C_SERCOM3_PAD3 MCHP_PINMUX(c, 5, c, periph)

#define PC5G_TCC1_WO0 MCHP_PINMUX(c, 5, g, periph)

#define PC5I_SDMMC1_SDCK MCHP_PINMUX(c, 5, i, periph)

#define PC5K_PCC_CLK MCHP_PINMUX(c, 5, k, periph)

#define PC5L_ETH_RXD2 MCHP_PINMUX(c, 5, l, periph)

#define PC5M_GCLK_IO7 MCHP_PINMUX(c, 5, m, periph)

#define PC5N_PTC_DRV15 MCHP_PINMUX(c, 5, n, periph)

#define PC6_GPIO MCHP_PINMUX(c, 6, gpio, gpio)

#define PC6A_EIC_EXTINT6 MCHP_PINMUX(c, 6, a, periph)

#define PC6B_AC_AIN2 MCHP_PINMUX(c, 6, b, periph)

#define PC6C_SERCOM2_PAD0 MCHP_PINMUX(c, 6, c, periph)

#define PC6D_SERCOM3_PAD1 MCHP_PINMUX(c, 6, d, periph)

#define PC6G_TCC1_WO1 MCHP_PINMUX(c, 6, g, periph)

#define PC6H_CAN1_TX MCHP_PINMUX(c, 6, h, periph)

#define PC6L_ETH_RXD1 MCHP_PINMUX(c, 6, l, periph)

#define PC6N_PTC_DRV16 MCHP_PINMUX(c, 6, n, periph)

#define PC7_GPIO MCHP_PINMUX(c, 7, gpio, gpio)

#define PC7A_EIC_EXTINT7 MCHP_PINMUX(c, 7, a, periph)

#define PC7B_AC_AIN3 MCHP_PINMUX(c, 7, b, periph)

#define PC7C_SERCOM2_PAD1 MCHP_PINMUX(c, 7, c, periph)

#define PC7D_SERCOM3_PAD0 MCHP_PINMUX(c, 7, d, periph)

#define PC7G_TCC1_WO2 MCHP_PINMUX(c, 7, g, periph)

#define PC7H_CAN1_RX MCHP_PINMUX(c, 7, h, periph)

#define PC7L_ETH_RXD0 MCHP_PINMUX(c, 7, l, periph)

#define PC7N_PTC_DRV17 MCHP_PINMUX(c, 7, n, periph)

#define PC9_GPIO MCHP_PINMUX(c, 9, gpio, gpio)

#define PC9A_EIC_EXTINT9 MCHP_PINMUX(c, 9, a, periph)

#define PC9C_SERCOM2_PAD2 MCHP_PINMUX(c, 9, c, periph)

#define PC9D_SERCOM3_PAD2 MCHP_PINMUX(c, 9, d, periph)

#define PC9G_TCC1_WO3 MCHP_PINMUX(c, 9, g, periph)

#define PC9L_ETH_RXER MCHP_PINMUX(c, 9, l, periph)

#define PC9M_AC_CMP0 MCHP_PINMUX(c, 9, m, periph)

#define PC9N_PTC_DRV19 MCHP_PINMUX(c, 9, n, periph)

#define PC10_GPIO MCHP_PINMUX(c, 10, gpio, gpio)

#define PC10A_EIC_EXTINT10 MCHP_PINMUX(c, 10, a, periph)

#define PC10C_SERCOM0_PAD0 MCHP_PINMUX(c, 10, c, periph)

#define PC10D_SERCOM2_PAD1 MCHP_PINMUX(c, 10, d, periph)

#define PC10G_TCC1_WO5 MCHP_PINMUX(c, 10, g, periph)

#define PC10L_ETH_RXDV MCHP_PINMUX(c, 10, l, periph)

#define PC10M_CCL_IN3 MCHP_PINMUX(c, 10, m, periph)

#define PC10N_PTC_DRV20 MCHP_PINMUX(c, 10, n, periph)

#define PC11_GPIO MCHP_PINMUX(c, 11, gpio, gpio)

#define PC11A_EIC_EXTINT11 MCHP_PINMUX(c, 11, a, periph)

#define PC11C_SERCOM0_PAD1 MCHP_PINMUX(c, 11, c, periph)

#define PC11D_SERCOM2_PAD0 MCHP_PINMUX(c, 11, d, periph)

#define PC11G_TCC1_WO6 MCHP_PINMUX(c, 11, g, periph)

#define PC11L_ETH_TXEN MCHP_PINMUX(c, 11, l, periph)

#define PC11M_CCL_IN4 MCHP_PINMUX(c, 11, m, periph)

#define PC11N_PTC_DRV21 MCHP_PINMUX(c, 11, n, periph)

#define PC12_GPIO MCHP_PINMUX(c, 12, gpio, gpio)

#define PC12A_EIC_EXTINT12 MCHP_PINMUX(c, 12, a, periph)

#define PC12C_SERCOM0_PAD2 MCHP_PINMUX(c, 12, c, periph)

#define PC12D_SERCOM2_PAD2 MCHP_PINMUX(c, 12, d, periph)

#define PC12G_TCC1_WO7 MCHP_PINMUX(c, 12, g, periph)

#define PC12L_ETH_TXD0 MCHP_PINMUX(c, 12, l, periph)

#define PC12M_CCL_IN5 MCHP_PINMUX(c, 12, m, periph)

#define PC12N_PTC_DRV22 MCHP_PINMUX(c, 12, n, periph)

#define PC13_GPIO MCHP_PINMUX(c, 13, gpio, gpio)

#define PC13A_EIC_EXTINT13 MCHP_PINMUX(c, 13, a, periph)

#define PC13C_SERCOM0_PAD3 MCHP_PINMUX(c, 13, c, periph)

#define PC13D_SERCOM2_PAD3 MCHP_PINMUX(c, 13, d, periph)

#define PC13L_ETH_TXD1 MCHP_PINMUX(c, 13, l, periph)

#define PC13M_CCL_OUT1 MCHP_PINMUX(c, 13, m, periph)

#define PC13N_PTC_DRV18 MCHP_PINMUX(c, 13, n, periph)

#define PD0_GPIO MCHP_PINMUX(d, 0, gpio, gpio)

#define PD0A_EIC_EXTINT0 MCHP_PINMUX(d, 0, a, periph)

#define PD1_GPIO MCHP_PINMUX(d, 1, gpio, gpio)

#define PD1A_EIC_EXTINT1 MCHP_PINMUX(d, 1, a, periph)

#define PD2_GPIO MCHP_PINMUX(d, 2, gpio, gpio)

#define PD2A_EIC_NMI MCHP_PINMUX(d, 2, a, periph)

#define PD2H_USB_SOF_1KHZ MCHP_PINMUX(d, 2, h, periph)

#define PD2K_PCC_DEN2 MCHP_PINMUX(d, 2, k, periph)

#define PD2L_ETH_TSUCOMP MCHP_PINMUX(d, 2, l, periph)

#define PD3_GPIO MCHP_PINMUX(d, 3, gpio, gpio)

#define PD3A_EIC_EXTINT3 MCHP_PINMUX(d, 3, a, periph)

#define PD3H_USB_DM MCHP_PINMUX(d, 3, h, periph)

#define PD4_GPIO MCHP_PINMUX(d, 4, gpio, gpio)

#define PD4A_EIC_EXTINT4 MCHP_PINMUX(d, 4, a, periph)

#define PD4H_USB_DP MCHP_PINMUX(d, 4, h, periph)

#define PD5_GPIO MCHP_PINMUX(d, 5, gpio, gpio)

#define PD5A_EIC_EXTINT5 MCHP_PINMUX(d, 5, a, periph)

#define PD5C_SERCOM0_PAD2 MCHP_PINMUX(d, 5, c, periph)

#define PD5G_TCC2_WO0 MCHP_PINMUX(d, 5, g, periph)

#define PD5H_SQI_CS1 MCHP_PINMUX(d, 5, h, periph)

#define PD5I_SDMMC0_SDWP MCHP_PINMUX(d, 5, i, periph)

#define PD5M_GCLK_IO3 MCHP_PINMUX(d, 5, m, periph)

#define PD6_GPIO MCHP_PINMUX(d, 6, gpio, gpio)

#define PD6A_EIC_EXTINT6 MCHP_PINMUX(d, 6, a, periph)

#define PD6C_SERCOM0_PAD0 MCHP_PINMUX(d, 6, c, periph)

#define PD6F_TCC2_WO4 MCHP_PINMUX(d, 6, f, periph)

#define PD6G_TCC2_WO1 MCHP_PINMUX(d, 6, g, periph)

#define PD6H_SQI_CS0 MCHP_PINMUX(d, 6, h, periph)

#define PD6I_SDMMC0_SDCMD MCHP_PINMUX(d, 6, i, periph)

#define PD6J_SPI_IXS_FSYNC MCHP_PINMUX(d, 6, j, periph)

#define PD6L_ETH_MDIO MCHP_PINMUX(d, 6, l, periph)

#define PD6M_GCLK_IO4 MCHP_PINMUX(d, 6, m, periph)

#define PD7_GPIO MCHP_PINMUX(d, 7, gpio, gpio)

#define PD7A_EIC_EXTINT7 MCHP_PINMUX(d, 7, a, periph)

#define PD7C_SERCOM0_PAD1 MCHP_PINMUX(d, 7, c, periph)

#define PD7F_TCC2_WO5 MCHP_PINMUX(d, 7, f, periph)

#define PD7G_TCC2_WO2 MCHP_PINMUX(d, 7, g, periph)

#define PD7H_SQI_DATA0 MCHP_PINMUX(d, 7, h, periph)

#define PD7I_SDMMC0_SDDAT0 MCHP_PINMUX(d, 7, i, periph)

#define PD7J_SPI_IXS_SDI MCHP_PINMUX(d, 7, j, periph)

#define PD7L_ETH_MDC MCHP_PINMUX(d, 7, l, periph)

#define PD7M_GCLK_IO5 MCHP_PINMUX(d, 7, m, periph)

#define PD8_GPIO MCHP_PINMUX(d, 8, gpio, gpio)

#define PD8A_EIC_EXTINT8 MCHP_PINMUX(d, 8, a, periph)

#define PD8C_SERCOM1_PAD0 MCHP_PINMUX(d, 8, c, periph)

#define PD8G_TCC2_WO3 MCHP_PINMUX(d, 8, g, periph)

#define PD8H_SQI_DATA2 MCHP_PINMUX(d, 8, h, periph)

#define PD8I_SDMMC0_SDDAT2 MCHP_PINMUX(d, 8, i, periph)

#define PD8J_SPI_IXS_SDO MCHP_PINMUX(d, 8, j, periph)

#define PD8M_CCL_IN6 MCHP_PINMUX(d, 8, m, periph)

#define PD9_GPIO MCHP_PINMUX(d, 9, gpio, gpio)

#define PD9A_EIC_EXTINT9 MCHP_PINMUX(d, 9, a, periph)

#define PD9C_SERCOM1_PAD1 MCHP_PINMUX(d, 9, c, periph)

#define PD9G_TCC2_WO4 MCHP_PINMUX(d, 9, g, periph)

#define PD9H_SQI_DATA3 MCHP_PINMUX(d, 9, h, periph)

#define PD9I_SDMMC0_SDDAT3 MCHP_PINMUX(d, 9, i, periph)

#define PD9M_CCL_IN7 MCHP_PINMUX(d, 9, m, periph)

#define PD10_GPIO MCHP_PINMUX(d, 10, gpio, gpio)

#define PD10A_EIC_EXTINT10 MCHP_PINMUX(d, 10, a, periph)

#define PD10C_SERCOM1_PAD2 MCHP_PINMUX(d, 10, c, periph)

#define PD10G_TCC2_WO5 MCHP_PINMUX(d, 10, g, periph)

#define PD10H_SQI_CLK MCHP_PINMUX(d, 10, h, periph)

#define PD10I_SDMMC0_SDCK MCHP_PINMUX(d, 10, i, periph)

#define PD10J_SPI_IXS_SCK MCHP_PINMUX(d, 10, j, periph)

#define PD10M_CCL_IN8 MCHP_PINMUX(d, 10, m, periph)

#define PD11_GPIO MCHP_PINMUX(d, 11, gpio, gpio)

#define PD11A_EIC_EXTINT11 MCHP_PINMUX(d, 11, a, periph)

#define PD11C_SERCOM1_PAD3 MCHP_PINMUX(d, 11, c, periph)

#define PD11F_TCC2_WO2 MCHP_PINMUX(d, 11, f, periph)

#define PD11G_TCC2_WO6 MCHP_PINMUX(d, 11, g, periph)

#define PD11H_SQI_DATA1 MCHP_PINMUX(d, 11, h, periph)

#define PD11I_SDMMC0_SDDAT1 MCHP_PINMUX(d, 11, i, periph)

#define PD11M_CCL_OUT2 MCHP_PINMUX(d, 11, m, periph)

#endif /* MICROCHIP_PIC32CK1025GC01064_PINCTRL_H_ */
