/*
 * Copyright (c) 2025 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CM5112GC00048_PINCTRL_H_
#define MICROCHIP_PIC32CM5112GC00048_PINCTRL_H_

#include <dt-bindings/pic32c/common/mchp_pinctrl_pinmux_pic32c.h>

/* pa0_gpio */
#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

/* pa0a_eic_extint0 */
#define PA0A_EIC_EXTINT0 MCHP_PINMUX(a, 0, a, periph)

/* pa0adc_test_pad_adc_res_test3 */
#define PA0ADC_TEST_PAD_ADC_RES_TEST3 MCHP_PINMUX(a, 0, adc_test_pad, periph)

/* pa0d_sercom3_pad1 */
#define PA0D_SERCOM3_PAD1 MCHP_PINMUX(a, 0, d, periph)

/* pa0f_tcc5_wo1 */
#define PA0F_TCC5_WO1 MCHP_PINMUX(a, 0, f, periph)

/* pa0h_can1_rx */
#define PA0H_CAN1_RX MCHP_PINMUX(a, 0, h, periph)

/* pa0i_ccl0_in6 */
#define PA0I_CCL0_IN6 MCHP_PINMUX(a, 0, i, periph)

/* pa0p_ptc_ptcxy4 */
#define PA0P_PTC_PTCXY4 MCHP_PINMUX(a, 0, p, periph)

/* pa0p_ptc_drv4 */
#define PA0P_PTC_DRV4 MCHP_PINMUX(a, 0, p, periph)

/* pa0pdmi_test_pdm_pdmi3 */
#define PA0PDMI_TEST_PDM_PDMI3 MCHP_PINMUX(a, 0, pdmi_test, periph)

/* pa1_gpio */
#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

/* pa1a_eic_extint1 */
#define PA1A_EIC_EXTINT1 MCHP_PINMUX(a, 1, a, periph)

/* pa1adc_test_pad_adc_res_test4 */
#define PA1ADC_TEST_PAD_ADC_RES_TEST4 MCHP_PINMUX(a, 1, adc_test_pad, periph)

/* pa1b_ac_cmp0 */
#define PA1B_AC_CMP0 MCHP_PINMUX(a, 1, b, periph)

/* pa1d_sercom3_pad2 */
#define PA1D_SERCOM3_PAD2 MCHP_PINMUX(a, 1, d, periph)

/* pa1f_tcc6_wo0 */
#define PA1F_TCC6_WO0 MCHP_PINMUX(a, 1, f, periph)

/* pa1h_can1_tx */
#define PA1H_CAN1_TX MCHP_PINMUX(a, 1, h, periph)

/* pa1i_ccl0_in7 */
#define PA1I_CCL0_IN7 MCHP_PINMUX(a, 1, i, periph)

/* pa1p_ptc_ptcxy5 */
#define PA1P_PTC_PTCXY5 MCHP_PINMUX(a, 1, p, periph)

/* pa1p_ptc_drv5 */
#define PA1P_PTC_DRV5 MCHP_PINMUX(a, 1, p, periph)

/* pa2_gpio */
#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

/* pa2a_eic_extint2 */
#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

/* pa2adc_test_pad_adc_res_test5 */
#define PA2ADC_TEST_PAD_ADC_RES_TEST5 MCHP_PINMUX(a, 2, adc_test_pad, periph)

/* pa2b_ac_cmp1 */
#define PA2B_AC_CMP1 MCHP_PINMUX(a, 2, b, periph)

/* pa2d_sercom3_pad3 */
#define PA2D_SERCOM3_PAD3 MCHP_PINMUX(a, 2, d, periph)

/* pa2f_tcc6_wo1 */
#define PA2F_TCC6_WO1 MCHP_PINMUX(a, 2, f, periph)

/* pa2i_ccl0_out2 */
#define PA2I_CCL0_OUT2 MCHP_PINMUX(a, 2, i, periph)

/* pa2p_ptc_ptcxy6 */
#define PA2P_PTC_PTCXY6 MCHP_PINMUX(a, 2, p, periph)

/* pa2p_ptc_drv6 */
#define PA2P_PTC_DRV6 MCHP_PINMUX(a, 2, p, periph)

/* pa3_gpio */
#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

/* pa3a_eic_extint3 */
#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

/* pa3adc_test_pad_adc_res_test6 */
#define PA3ADC_TEST_PAD_ADC_RES_TEST6 MCHP_PINMUX(a, 3, adc_test_pad, periph)

/* pa3b_adc_adc0_ain0 */
#define PA3B_ADC_ADC0_AIN0 MCHP_PINMUX(a, 3, b, periph)

/* pa3d_sercom4_pad0 */
#define PA3D_SERCOM4_PAD0 MCHP_PINMUX(a, 3, d, periph)

/* pa3p_ptc_ptcxy7 */
#define PA3P_PTC_PTCXY7 MCHP_PINMUX(a, 3, p, periph)

/* pa3p_ptc_drv7 */
#define PA3P_PTC_DRV7 MCHP_PINMUX(a, 3, p, periph)

/* pa4_gpio */
#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

/* pa4a_eic_extint4 */
#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

/* pa4adc_test_pad_adc_res_test7 */
#define PA4ADC_TEST_PAD_ADC_RES_TEST7 MCHP_PINMUX(a, 4, adc_test_pad, periph)

/* pa4b_adc_adc0_ain1 */
#define PA4B_ADC_ADC0_AIN1 MCHP_PINMUX(a, 4, b, periph)

/* pa4b_adc_adc0_ann0 */
#define PA4B_ADC_ADC0_ANN0 MCHP_PINMUX(a, 4, b, periph)

/* pa4d_sercom4_pad1 */
#define PA4D_SERCOM4_PAD1 MCHP_PINMUX(a, 4, d, periph)

/* pa4p_ptc_ptcxy8 */
#define PA4P_PTC_PTCXY8 MCHP_PINMUX(a, 4, p, periph)

/* pa4p_ptc_drv8 */
#define PA4P_PTC_DRV8 MCHP_PINMUX(a, 4, p, periph)

/* pa5_gpio */
#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

/* pa5a_eic_extint5 */
#define PA5A_EIC_EXTINT5 MCHP_PINMUX(a, 5, a, periph)

/* pa5b_adc_adc0_ain2 */
#define PA5B_ADC_ADC0_AIN2 MCHP_PINMUX(a, 5, b, periph)

/* pa5d_sercom4_pad2 */
#define PA5D_SERCOM4_PAD2 MCHP_PINMUX(a, 5, d, periph)

/* pa5i_ccl1_out2 */
#define PA5I_CCL1_OUT2 MCHP_PINMUX(a, 5, i, periph)

/* pa5p_ptc_ptcxy9 */
#define PA5P_PTC_PTCXY9 MCHP_PINMUX(a, 5, p, periph)

/* pa5p_ptc_drv9 */
#define PA5P_PTC_DRV9 MCHP_PINMUX(a, 5, p, periph)

/* pa5valio_testval_valio3 */
#define PA5VALIO_TESTVAL_VALIO3 MCHP_PINMUX(a, 5, valio, periph)

/* pa6_gpio */
#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

/* pa6a_eic_extint6 */
#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

/* pa6b_adc_adc0_ain3 */
#define PA6B_ADC_ADC0_AIN3 MCHP_PINMUX(a, 6, b, periph)

/* pa6b_adc_adc0_ann2 */
#define PA6B_ADC_ADC0_ANN2 MCHP_PINMUX(a, 6, b, periph)

/* pa6d_sercom4_pad3 */
#define PA6D_SERCOM4_PAD3 MCHP_PINMUX(a, 6, d, periph)

/* pa6i_ccl1_in7 */
#define PA6I_CCL1_IN7 MCHP_PINMUX(a, 6, i, periph)

/* pa6p_ptc_ptcxy10 */
#define PA6P_PTC_PTCXY10 MCHP_PINMUX(a, 6, p, periph)

/* pa6p_ptc_drv10 */
#define PA6P_PTC_DRV10 MCHP_PINMUX(a, 6, p, periph)

/* pa7_gpio */
#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

/* pa7a_eic_extint7 */
#define PA7A_EIC_EXTINT7 MCHP_PINMUX(a, 7, a, periph)

/* pa7b_ac_ain0 */
#define PA7B_AC_AIN0 MCHP_PINMUX(a, 7, b, periph)

/* pa7b_adc_adc0_ain4 */
#define PA7B_ADC_ADC0_AIN4 MCHP_PINMUX(a, 7, b, periph)

/* pa7p_ptc_ptcxy11 */
#define PA7P_PTC_PTCXY11 MCHP_PINMUX(a, 7, p, periph)

/* pa7p_ptc_drv11 */
#define PA7P_PTC_DRV11 MCHP_PINMUX(a, 7, p, periph)

/* pa8_gpio */
#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

/* pa8a_eic_extint8 */
#define PA8A_EIC_EXTINT8 MCHP_PINMUX(a, 8, a, periph)

/* pa8b_ac_ain1 */
#define PA8B_AC_AIN1 MCHP_PINMUX(a, 8, b, periph)

/* pa8b_adc_adc0_ain5 */
#define PA8B_ADC_ADC0_AIN5 MCHP_PINMUX(a, 8, b, periph)

/* pa8b_adc_adc0_ann4 */
#define PA8B_ADC_ADC0_ANN4 MCHP_PINMUX(a, 8, b, periph)

/* pa8p_ptc_ptcxy12 */
#define PA8P_PTC_PTCXY12 MCHP_PINMUX(a, 8, p, periph)

/* pa8p_ptc_drv12 */
#define PA8P_PTC_DRV12 MCHP_PINMUX(a, 8, p, periph)

/* pa9_gpio */
#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

/* pa9a_eic_extint9 */
#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

/* pa9b_adc_adc0_ain6 */
#define PA9B_ADC_ADC0_AIN6 MCHP_PINMUX(a, 9, b, periph)

/* pa9i_ccl1_in6 */
#define PA9I_CCL1_IN6 MCHP_PINMUX(a, 9, i, periph)

/* pa9p_ptc_ptcxy13 */
#define PA9P_PTC_PTCXY13 MCHP_PINMUX(a, 9, p, periph)

/* pa9p_ptc_drv13 */
#define PA9P_PTC_DRV13 MCHP_PINMUX(a, 9, p, periph)

/* pa9volt_ref_adc_vrefh */
#define PA9VOLT_REF_ADC_VREFH MCHP_PINMUX(a, 9, volt_ref, periph)

/* pb0_gpio */
#define PB0_GPIO MCHP_PINMUX(b, 0, gpio, gpio)

/* pb0a_eic_extint0 */
#define PB0A_EIC_EXTINT0 MCHP_PINMUX(b, 0, a, periph)

/* pb0b_ac_ain2 */
#define PB0B_AC_AIN2 MCHP_PINMUX(b, 0, b, periph)

/* pb0b_adc_adc0_ain7 */
#define PB0B_ADC_ADC0_AIN7 MCHP_PINMUX(b, 0, b, periph)

/* pb0i_ccl1_out3 */
#define PB0I_CCL1_OUT3 MCHP_PINMUX(b, 0, i, periph)

/* pb0p_ptc_ptcxy14 */
#define PB0P_PTC_PTCXY14 MCHP_PINMUX(b, 0, p, periph)

/* pb0p_ptc_drv14 */
#define PB0P_PTC_DRV14 MCHP_PINMUX(b, 0, p, periph)

/* pb1_gpio */
#define PB1_GPIO MCHP_PINMUX(b, 1, gpio, gpio)

/* pb1a_eic_extint1 */
#define PB1A_EIC_EXTINT1 MCHP_PINMUX(b, 1, a, periph)

/* pb2_gpio */
#define PB2_GPIO MCHP_PINMUX(b, 2, gpio, gpio)

/* pb2a_eic_extint2 */
#define PB2A_EIC_EXTINT2 MCHP_PINMUX(b, 2, a, periph)

/* pb3_gpio */
#define PB3_GPIO MCHP_PINMUX(b, 3, gpio, gpio)

/* pb3a_eic_extint3 */
#define PB3A_EIC_EXTINT3 MCHP_PINMUX(b, 3, a, periph)

/* pb3adc_test_pad_adc_res_test8 */
#define PB3ADC_TEST_PAD_ADC_RES_TEST8 MCHP_PINMUX(b, 3, adc_test_pad, periph)

/* pb3b_ac_ain3 */
#define PB3B_AC_AIN3 MCHP_PINMUX(b, 3, b, periph)

/* pb3b_adc_adc0_ain8 */
#define PB3B_ADC_ADC0_AIN8 MCHP_PINMUX(b, 3, b, periph)

/* pb3d_sercom5_pad0 */
#define PB3D_SERCOM5_PAD0 MCHP_PINMUX(b, 3, d, periph)

/* pb3i_ccl1_in10 */
#define PB3I_CCL1_IN10 MCHP_PINMUX(b, 3, i, periph)

/* pb3p_ptc_ptcxy15 */
#define PB3P_PTC_PTCXY15 MCHP_PINMUX(b, 3, p, periph)

/* pb3p_ptc_drv15 */
#define PB3P_PTC_DRV15 MCHP_PINMUX(b, 3, p, periph)

/* pb3pdmo_lv_test_pdm_pdmo0 */
#define PB3PDMO_LV_TEST_PDM_PDMO0 MCHP_PINMUX(b, 3, pdmo_lv_test, periph)

/* pb3pdmo_mv_test_pdm_pdmo0_mv */
#define PB3PDMO_MV_TEST_PDM_PDMO0_MV MCHP_PINMUX(b, 3, pdmo_mv_test, periph)

/* pb4_gpio */
#define PB4_GPIO MCHP_PINMUX(b, 4, gpio, gpio)

/* pb4a_eic_extint4 */
#define PB4A_EIC_EXTINT4 MCHP_PINMUX(b, 4, a, periph)

/* pb4adc_test_pad_adc_res_test9 */
#define PB4ADC_TEST_PAD_ADC_RES_TEST9 MCHP_PINMUX(b, 4, adc_test_pad, periph)

/* pb4b_adc_adc0_ain9 */
#define PB4B_ADC_ADC0_AIN9 MCHP_PINMUX(b, 4, b, periph)

/* pb4d_sercom5_pad1 */
#define PB4D_SERCOM5_PAD1 MCHP_PINMUX(b, 4, d, periph)

/* pb4i_ccl1_in9 */
#define PB4I_CCL1_IN9 MCHP_PINMUX(b, 4, i, periph)

/* pb4p_ptc_ptcxy16 */
#define PB4P_PTC_PTCXY16 MCHP_PINMUX(b, 4, p, periph)

/* pb4p_ptc_drv16 */
#define PB4P_PTC_DRV16 MCHP_PINMUX(b, 4, p, periph)

/* pb4pdmo_lv_test_pdm_pdmo1 */
#define PB4PDMO_LV_TEST_PDM_PDMO1 MCHP_PINMUX(b, 4, pdmo_lv_test, periph)

/* pb4pdmo_mv_test_pdm_pdmo1_mv */
#define PB4PDMO_MV_TEST_PDM_PDMO1_MV MCHP_PINMUX(b, 4, pdmo_mv_test, periph)

/* pb5_gpio */
#define PB5_GPIO MCHP_PINMUX(b, 5, gpio, gpio)

/* pb5a_eic_extint5 */
#define PB5A_EIC_EXTINT5 MCHP_PINMUX(b, 5, a, periph)

/* pb5adc_test_pad_adc_res_test10 */
#define PB5ADC_TEST_PAD_ADC_RES_TEST10 MCHP_PINMUX(b, 5, adc_test_pad, periph)

/* pb5b_adc_adc0_ain10 */
#define PB5B_ADC_ADC0_AIN10 MCHP_PINMUX(b, 5, b, periph)

/* pb5d_sercom5_pad2 */
#define PB5D_SERCOM5_PAD2 MCHP_PINMUX(b, 5, d, periph)

/* pb5i_ccl0_in9 */
#define PB5I_CCL0_IN9 MCHP_PINMUX(b, 5, i, periph)

/* pb5p_ptc_ptcxy17 */
#define PB5P_PTC_PTCXY17 MCHP_PINMUX(b, 5, p, periph)

/* pb5p_ptc_drv17 */
#define PB5P_PTC_DRV17 MCHP_PINMUX(b, 5, p, periph)

/* pb5pdmo_lv_test_pdm_pdmo2 */
#define PB5PDMO_LV_TEST_PDM_PDMO2 MCHP_PINMUX(b, 5, pdmo_lv_test, periph)

/* pb5pdmo_mv_test_pdm_pdmo2_mv */
#define PB5PDMO_MV_TEST_PDM_PDMO2_MV MCHP_PINMUX(b, 5, pdmo_mv_test, periph)

/* pb6_gpio */
#define PB6_GPIO MCHP_PINMUX(b, 6, gpio, gpio)

/* pb6a_eic_extint6 */
#define PB6A_EIC_EXTINT6 MCHP_PINMUX(b, 6, a, periph)

/* pb6adc_test_pad_adc_res_test11 */
#define PB6ADC_TEST_PAD_ADC_RES_TEST11 MCHP_PINMUX(b, 6, adc_test_pad, periph)

/* pb6b_adc_adc0_ain11 */
#define PB6B_ADC_ADC0_AIN11 MCHP_PINMUX(b, 6, b, periph)

/* pb6d_sercom5_pad3 */
#define PB6D_SERCOM5_PAD3 MCHP_PINMUX(b, 6, d, periph)

/* pb6i_ccl0_in10 */
#define PB6I_CCL0_IN10 MCHP_PINMUX(b, 6, i, periph)

/* pb6k_gclk_io0 */
#define PB6K_GCLK_IO0 MCHP_PINMUX(b, 6, k, periph)

/* pb6p_ptc_ptcxy18 */
#define PB6P_PTC_PTCXY18 MCHP_PINMUX(b, 6, p, periph)

/* pb6p_ptc_drv18 */
#define PB6P_PTC_DRV18 MCHP_PINMUX(b, 6, p, periph)

/* pb6pdmo_lv_test_pdm_pdmo3 */
#define PB6PDMO_LV_TEST_PDM_PDMO3 MCHP_PINMUX(b, 6, pdmo_lv_test, periph)

/* pb6pdmo_mv_test_pdm_pdmo3_mv */
#define PB6PDMO_MV_TEST_PDM_PDMO3_MV MCHP_PINMUX(b, 6, pdmo_mv_test, periph)

/* pc0_gpio */
#define PC0_GPIO MCHP_PINMUX(c, 0, gpio, gpio)

/* pc0a_eic_extint0 */
#define PC0A_EIC_EXTINT0 MCHP_PINMUX(c, 0, a, periph)

/* pc0d_sercom0_pad0 */
#define PC0D_SERCOM0_PAD0 MCHP_PINMUX(c, 0, d, periph)

/* pc0f_tcc0_wo0 */
#define PC0F_TCC0_WO0 MCHP_PINMUX(c, 0, f, periph)

/* pc0i_ccl0_out3 */
#define PC0I_CCL0_OUT3 MCHP_PINMUX(c, 0, i, periph)

/* pc0k_gclk_io1 */
#define PC0K_GCLK_IO1 MCHP_PINMUX(c, 0, k, periph)

/* pc0p_ptc_ptcxy19 */
#define PC0P_PTC_PTCXY19 MCHP_PINMUX(c, 0, p, periph)

/* pc0p_ptc_drv19 */
#define PC0P_PTC_DRV19 MCHP_PINMUX(c, 0, p, periph)

/* pc0pdmo_lv_test_pdm_pdmo4 */
#define PC0PDMO_LV_TEST_PDM_PDMO4 MCHP_PINMUX(c, 0, pdmo_lv_test, periph)

/* pc0pdmo_mv_test_pdm_pdmo4_mv */
#define PC0PDMO_MV_TEST_PDM_PDMO4_MV MCHP_PINMUX(c, 0, pdmo_mv_test, periph)

/* pc1_gpio */
#define PC1_GPIO MCHP_PINMUX(c, 1, gpio, gpio)

/* pc1a_eic_extint1 */
#define PC1A_EIC_EXTINT1 MCHP_PINMUX(c, 1, a, periph)

/* pc1d_sercom0_pad1 */
#define PC1D_SERCOM0_PAD1 MCHP_PINMUX(c, 1, d, periph)

/* pc1f_tcc0_wo1 */
#define PC1F_TCC0_WO1 MCHP_PINMUX(c, 1, f, periph)

/* pc1h_can0_rx */
#define PC1H_CAN0_RX MCHP_PINMUX(c, 1, h, periph)

/* pc1i_ccl0_in0 */
#define PC1I_CCL0_IN0 MCHP_PINMUX(c, 1, i, periph)

/* pc1k_gclk_io2 */
#define PC1K_GCLK_IO2 MCHP_PINMUX(c, 1, k, periph)

/* pc1p_ptc_ptcxy20 */
#define PC1P_PTC_PTCXY20 MCHP_PINMUX(c, 1, p, periph)

/* pc1p_ptc_drv20 */
#define PC1P_PTC_DRV20 MCHP_PINMUX(c, 1, p, periph)

/* pc1pdmo_lv_test_pdm_pdmo5 */
#define PC1PDMO_LV_TEST_PDM_PDMO5 MCHP_PINMUX(c, 1, pdmo_lv_test, periph)

/* pc1pdmo_mv_test_pdm_pdmo5_mv */
#define PC1PDMO_MV_TEST_PDM_PDMO5_MV MCHP_PINMUX(c, 1, pdmo_mv_test, periph)

/* pc1valio_testval_valio4 */
#define PC1VALIO_TESTVAL_VALIO4 MCHP_PINMUX(c, 1, valio, periph)

/* pc2_gpio */
#define PC2_GPIO MCHP_PINMUX(c, 2, gpio, gpio)

/* pc2a_eic_extint2 */
#define PC2A_EIC_EXTINT2 MCHP_PINMUX(c, 2, a, periph)

/* pc2d_sercom0_pad2 */
#define PC2D_SERCOM0_PAD2 MCHP_PINMUX(c, 2, d, periph)

/* pc2f_tcc1_wo0 */
#define PC2F_TCC1_WO0 MCHP_PINMUX(c, 2, f, periph)

/* pc2h_can0_tx */
#define PC2H_CAN0_TX MCHP_PINMUX(c, 2, h, periph)

/* pc2i_ccl0_in1 */
#define PC2I_CCL0_IN1 MCHP_PINMUX(c, 2, i, periph)

/* pc2k_gclk_io3 */
#define PC2K_GCLK_IO3 MCHP_PINMUX(c, 2, k, periph)

/* pc2p_ptc_ptcxy21 */
#define PC2P_PTC_PTCXY21 MCHP_PINMUX(c, 2, p, periph)

/* pc2p_ptc_drv21 */
#define PC2P_PTC_DRV21 MCHP_PINMUX(c, 2, p, periph)

/* pc2pdmo_lv_test_pdm_pdmo6 */
#define PC2PDMO_LV_TEST_PDM_PDMO6 MCHP_PINMUX(c, 2, pdmo_lv_test, periph)

/* pc2pdmo_mv_test_pdm_pdmo6_mv */
#define PC2PDMO_MV_TEST_PDM_PDMO6_MV MCHP_PINMUX(c, 2, pdmo_mv_test, periph)

/* pc2valio_testval_valio5 */
#define PC2VALIO_TESTVAL_VALIO5 MCHP_PINMUX(c, 2, valio, periph)

/* pc3_gpio */
#define PC3_GPIO MCHP_PINMUX(c, 3, gpio, gpio)

/* pc3a_eic_extint3 */
#define PC3A_EIC_EXTINT3 MCHP_PINMUX(c, 3, a, periph)

/* pc3d_sercom0_pad3 */
#define PC3D_SERCOM0_PAD3 MCHP_PINMUX(c, 3, d, periph)

/* pc3f_tcc1_wo1 */
#define PC3F_TCC1_WO1 MCHP_PINMUX(c, 3, f, periph)

/* pc3i_ccl0_out0 */
#define PC3I_CCL0_OUT0 MCHP_PINMUX(c, 3, i, periph)

/* pc3k_gclk_io4 */
#define PC3K_GCLK_IO4 MCHP_PINMUX(c, 3, k, periph)

/* pc3p_ptc_eci0 */
#define PC3P_PTC_ECI0 MCHP_PINMUX(c, 3, p, periph)

/* pc3pdmo_lv_test_pdm_pdmo7 */
#define PC3PDMO_LV_TEST_PDM_PDMO7 MCHP_PINMUX(c, 3, pdmo_lv_test, periph)

/* pc3pdmo_mv_test_pdm_pdmo7_mv */
#define PC3PDMO_MV_TEST_PDM_PDMO7_MV MCHP_PINMUX(c, 3, pdmo_mv_test, periph)

/* pc4_gpio */
#define PC4_GPIO MCHP_PINMUX(c, 4, gpio, gpio)

/* pc4a_eic_extint4 */
#define PC4A_EIC_EXTINT4 MCHP_PINMUX(c, 4, a, periph)

/* pc4d_sercom2_pad0 */
#define PC4D_SERCOM2_PAD0 MCHP_PINMUX(c, 4, d, periph)

/* pc4f_tcc2_wo0 */
#define PC4F_TCC2_WO0 MCHP_PINMUX(c, 4, f, periph)

/* pc4i_ccl1_in0 */
#define PC4I_CCL1_IN0 MCHP_PINMUX(c, 4, i, periph)

/* pc4k_gclk_io5 */
#define PC4K_GCLK_IO5 MCHP_PINMUX(c, 4, k, periph)

/* pc4p_ptc_eci1 */
#define PC4P_PTC_ECI1 MCHP_PINMUX(c, 4, p, periph)

/* pc4valio_testval_valio2 */
#define PC4VALIO_TESTVAL_VALIO2 MCHP_PINMUX(c, 4, valio, periph)

/* pc5_gpio */
#define PC5_GPIO MCHP_PINMUX(c, 5, gpio, gpio)

/* pc5a_eic_extint5 */
#define PC5A_EIC_EXTINT5 MCHP_PINMUX(c, 5, a, periph)

/* pc5d_sercom1_pad3 */
#define PC5D_SERCOM1_PAD3 MCHP_PINMUX(c, 5, d, periph)

/* pc5dsu_msa_dsu_msa */
#define PC5DSU_MSA_DSU_MSA MCHP_PINMUX(c, 5, dsu_msa, periph)

/* pc5f_tcc2_wo1 */
#define PC5F_TCC2_WO1 MCHP_PINMUX(c, 5, f, periph)

/* pc5h_can1_rx */
#define PC5H_CAN1_RX MCHP_PINMUX(c, 5, h, periph)

/* pc5i_ccl1_in1 */
#define PC5I_CCL1_IN1 MCHP_PINMUX(c, 5, i, periph)

/* pc5k_gclk_io1 */
#define PC5K_GCLK_IO1 MCHP_PINMUX(c, 5, k, periph)

/* pc6_gpio */
#define PC6_GPIO MCHP_PINMUX(c, 6, gpio, gpio)

/* pc6a_eic_extint6 */
#define PC6A_EIC_EXTINT6 MCHP_PINMUX(c, 6, a, periph)

/* pc6d_sercom1_pad2 */
#define PC6D_SERCOM1_PAD2 MCHP_PINMUX(c, 6, d, periph)

/* pc6dsu_swccstat_dsu_swccstat */
#define PC6DSU_SWCCSTAT_DSU_SWCCSTAT MCHP_PINMUX(c, 6, dsu_swccstat, periph)

/* pc6h_can1_tx */
#define PC6H_CAN1_TX MCHP_PINMUX(c, 6, h, periph)

/* pc6i_ccl1_out0 */
#define PC6I_CCL1_OUT0 MCHP_PINMUX(c, 6, i, periph)

/* pc8_gpio */
#define PC8_GPIO MCHP_PINMUX(c, 8, gpio, gpio)

/* pc8dsu_test_gclk_gclk_tst_gclk */
#define PC8DSU_TEST_GCLK_GCLK_TST_GCLK MCHP_PINMUX(c, 8, dsu_test_gclk, periph)

/* pd0_gpio */
#define PD0_GPIO MCHP_PINMUX(d, 0, gpio, gpio)

/* pd0a_eic_nmi */
#define PD0A_EIC_NMI MCHP_PINMUX(d, 0, a, periph)

/* pd0d_sercom1_pad1 */
#define PD0D_SERCOM1_PAD1 MCHP_PINMUX(d, 0, d, periph)

/* pd0f_tcc3_wo0 */
#define PD0F_TCC3_WO0 MCHP_PINMUX(d, 0, f, periph)

/* pd0i_ccl0_in3 */
#define PD0I_CCL0_IN3 MCHP_PINMUX(d, 0, i, periph)

/* pd0valio_testval_valio0 */
#define PD0VALIO_TESTVAL_VALIO0 MCHP_PINMUX(d, 0, valio, periph)

/* pd1_gpio */
#define PD1_GPIO MCHP_PINMUX(d, 1, gpio, gpio)

/* pd1a_eic_extint1 */
#define PD1A_EIC_EXTINT1 MCHP_PINMUX(d, 1, a, periph)

/* pd1d_sercom1_pad0 */
#define PD1D_SERCOM1_PAD0 MCHP_PINMUX(d, 1, d, periph)

/* pd1f_tcc3_wo1 */
#define PD1F_TCC3_WO1 MCHP_PINMUX(d, 1, f, periph)

/* pd1h_usb_sof */
#define PD1H_USB_SOF MCHP_PINMUX(d, 1, h, periph)

/* pd1i_ccl0_in4 */
#define PD1I_CCL0_IN4 MCHP_PINMUX(d, 1, i, periph)

/* pd1valio_testval_valio1 */
#define PD1VALIO_TESTVAL_VALIO1 MCHP_PINMUX(d, 1, valio, periph)

/* pd2_gpio */
#define PD2_GPIO MCHP_PINMUX(d, 2, gpio, gpio)

/* pd2h_usb_usbdm */
#define PD2H_USB_USBDM MCHP_PINMUX(d, 2, h, periph)

/* pd3_gpio */
#define PD3_GPIO MCHP_PINMUX(d, 3, gpio, gpio)

/* pd3h_usb_usbdp */
#define PD3H_USB_USBDP MCHP_PINMUX(d, 3, h, periph)

/* pd4_gpio */
#define PD4_GPIO MCHP_PINMUX(d, 4, gpio, gpio)

/* pd4a_eic_extint2 */
#define PD4A_EIC_EXTINT2 MCHP_PINMUX(d, 4, a, periph)

/* pd4k_gclk_io1 */
#define PD4K_GCLK_IO1 MCHP_PINMUX(d, 4, k, periph)

/* pd5_gpio */
#define PD5_GPIO MCHP_PINMUX(d, 5, gpio, gpio)

/* pd5a_eic_extint3 */
#define PD5A_EIC_EXTINT3 MCHP_PINMUX(d, 5, a, periph)

/* pd5k_gclk_io0 */
#define PD5K_GCLK_IO0 MCHP_PINMUX(d, 5, k, periph)

/* pd6_gpio */
#define PD6_GPIO MCHP_PINMUX(d, 6, gpio, gpio)

/* pd6d_sercom2_pad1 */
#define PD6D_SERCOM2_PAD1 MCHP_PINMUX(d, 6, d, periph)

/* pd6h_can0_rx */
#define PD6H_CAN0_RX MCHP_PINMUX(d, 6, h, periph)

/* pd6i_ccl1_in3 */
#define PD6I_CCL1_IN3 MCHP_PINMUX(d, 6, i, periph)

/* pd6p_ptc_ptcxy0 */
#define PD6P_PTC_PTCXY0 MCHP_PINMUX(d, 6, p, periph)

/* pd6p_ptc_drv0 */
#define PD6P_PTC_DRV0 MCHP_PINMUX(d, 6, p, periph)

/* pd7_gpio */
#define PD7_GPIO MCHP_PINMUX(d, 7, gpio, gpio)

/* pd7a_eic_extint4 */
#define PD7A_EIC_EXTINT4 MCHP_PINMUX(d, 7, a, periph)

/* pd7adc_test_pad_adc_res_test2 */
#define PD7ADC_TEST_PAD_ADC_RES_TEST2 MCHP_PINMUX(d, 7, adc_test_pad, periph)

/* pd7d_sercom2_pad2 */
#define PD7D_SERCOM2_PAD2 MCHP_PINMUX(d, 7, d, periph)

/* pd7f_tcc4_wo0 */
#define PD7F_TCC4_WO0 MCHP_PINMUX(d, 7, f, periph)

/* pd7i_ccl1_in4 */
#define PD7I_CCL1_IN4 MCHP_PINMUX(d, 7, i, periph)

/* pd7p_ptc_ptcxy1 */
#define PD7P_PTC_PTCXY1 MCHP_PINMUX(d, 7, p, periph)

/* pd7p_ptc_drv1 */
#define PD7P_PTC_DRV1 MCHP_PINMUX(d, 7, p, periph)

/* pd7pdmi_test_pdm_pdmi0 */
#define PD7PDMI_TEST_PDM_PDMI0 MCHP_PINMUX(d, 7, pdmi_test, periph)

/* pd8_gpio */
#define PD8_GPIO MCHP_PINMUX(d, 8, gpio, gpio)

/* pd8a_eic_extint5 */
#define PD8A_EIC_EXTINT5 MCHP_PINMUX(d, 8, a, periph)

/* pd8adc_test_pad_adc_res_test0 */
#define PD8ADC_TEST_PAD_ADC_RES_TEST0 MCHP_PINMUX(d, 8, adc_test_pad, periph)

/* pd8d_sercom2_pad3 */
#define PD8D_SERCOM2_PAD3 MCHP_PINMUX(d, 8, d, periph)

/* pd8f_tcc4_wo1 */
#define PD8F_TCC4_WO1 MCHP_PINMUX(d, 8, f, periph)

/* pd8h_can0_tx */
#define PD8H_CAN0_TX MCHP_PINMUX(d, 8, h, periph)

/* pd8i_ccl0_out1 */
#define PD8I_CCL0_OUT1 MCHP_PINMUX(d, 8, i, periph)

/* pd8p_ptc_ptcxy2 */
#define PD8P_PTC_PTCXY2 MCHP_PINMUX(d, 8, p, periph)

/* pd8p_ptc_drv2 */
#define PD8P_PTC_DRV2 MCHP_PINMUX(d, 8, p, periph)

/* pd8pdmi_test_pdm_pdmi1 */
#define PD8PDMI_TEST_PDM_PDMI1 MCHP_PINMUX(d, 8, pdmi_test, periph)

/* pd9_gpio */
#define PD9_GPIO MCHP_PINMUX(d, 9, gpio, gpio)

/* pd9a_eic_extint6 */
#define PD9A_EIC_EXTINT6 MCHP_PINMUX(d, 9, a, periph)

/* pd9adc_test_pad_adc_res_test1 */
#define PD9ADC_TEST_PAD_ADC_RES_TEST1 MCHP_PINMUX(d, 9, adc_test_pad, periph)

/* pd9d_sercom3_pad0 */
#define PD9D_SERCOM3_PAD0 MCHP_PINMUX(d, 9, d, periph)

/* pd9f_tcc5_wo0 */
#define PD9F_TCC5_WO0 MCHP_PINMUX(d, 9, f, periph)

/* pd9i_ccl1_out1 */
#define PD9I_CCL1_OUT1 MCHP_PINMUX(d, 9, i, periph)

/* pd9p_ptc_ptcxy3 */
#define PD9P_PTC_PTCXY3 MCHP_PINMUX(d, 9, p, periph)

/* pd9p_ptc_drv3 */
#define PD9P_PTC_DRV3 MCHP_PINMUX(d, 9, p, periph)

/* pd9pdmi_test_pdm_pdmi2 */
#define PD9PDMI_TEST_PDM_PDMI2 MCHP_PINMUX(d, 9, pdmi_test, periph)

#endif /* MICROCHIP_PIC32CM5112GC00048_PINCTRL_H_ */
