/*
 * Copyright (c) 2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CM5112GC00048_PINCTRL_H_
#define MICROCHIP_PIC32CM5112GC00048_PINCTRL_H_

#include <dt-bindings/pic32c/pic32cm_sg_gc/common/mchp_pinctrl_pinmux_pic32c.h>

#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

#define PA0A_EIC_EXTINT0 MCHP_PINMUX(a, 0, a, periph)

#define PA0D_SERCOM3_PAD1 MCHP_PINMUX(a, 0, d, periph)

#define PA0F_TCC5_WO1 MCHP_PINMUX(a, 0, f, periph)

#define PA0H_CAN1_RX MCHP_PINMUX(a, 0, h, periph)

#define PA0I_CCL0_IN6 MCHP_PINMUX(a, 0, i, periph)

#define PA0P_PTC_DRV4 MCHP_PINMUX(a, 0, p, periph)

#define PA0P_PTC_PTCXY4 MCHP_PINMUX(a, 0, p, periph)

#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

#define PA1A_EIC_EXTINT1 MCHP_PINMUX(a, 1, a, periph)

#define PA1B_AC_CMP0 MCHP_PINMUX(a, 1, b, periph)

#define PA1D_SERCOM3_PAD2 MCHP_PINMUX(a, 1, d, periph)

#define PA1F_TCC6_WO0 MCHP_PINMUX(a, 1, f, periph)

#define PA1H_CAN1_TX MCHP_PINMUX(a, 1, h, periph)

#define PA1I_CCL0_IN7 MCHP_PINMUX(a, 1, i, periph)

#define PA1P_PTC_DRV5 MCHP_PINMUX(a, 1, p, periph)

#define PA1P_PTC_PTCXY5 MCHP_PINMUX(a, 1, p, periph)

#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

#define PA2B_AC_CMP1 MCHP_PINMUX(a, 2, b, periph)

#define PA2D_SERCOM3_PAD3 MCHP_PINMUX(a, 2, d, periph)

#define PA2F_TCC6_WO1 MCHP_PINMUX(a, 2, f, periph)

#define PA2I_CCL0_OUT2 MCHP_PINMUX(a, 2, i, periph)

#define PA2P_PTC_DRV6 MCHP_PINMUX(a, 2, p, periph)

#define PA2P_PTC_PTCXY6 MCHP_PINMUX(a, 2, p, periph)

#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

#define PA3B_ADC_ADC0_AIN0 MCHP_PINMUX(a, 3, b, periph)

#define PA3D_SERCOM4_PAD0 MCHP_PINMUX(a, 3, d, periph)

#define PA3P_PTC_DRV7 MCHP_PINMUX(a, 3, p, periph)

#define PA3P_PTC_PTCXY7 MCHP_PINMUX(a, 3, p, periph)

#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

#define PA4B_ADC_ADC0_AIN1 MCHP_PINMUX(a, 4, b, periph)

#define PA4B_ADC_ADC0_ANN0 MCHP_PINMUX(a, 4, b, periph)

#define PA4D_SERCOM4_PAD1 MCHP_PINMUX(a, 4, d, periph)

#define PA4P_PTC_DRV8 MCHP_PINMUX(a, 4, p, periph)

#define PA4P_PTC_PTCXY8 MCHP_PINMUX(a, 4, p, periph)

#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

#define PA5A_EIC_EXTINT5 MCHP_PINMUX(a, 5, a, periph)

#define PA5B_ADC_ADC0_AIN2 MCHP_PINMUX(a, 5, b, periph)

#define PA5D_SERCOM4_PAD2 MCHP_PINMUX(a, 5, d, periph)

#define PA5I_CCL1_OUT2 MCHP_PINMUX(a, 5, i, periph)

#define PA5P_PTC_DRV9 MCHP_PINMUX(a, 5, p, periph)

#define PA5P_PTC_PTCXY9 MCHP_PINMUX(a, 5, p, periph)

#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

#define PA6B_ADC_ADC0_AIN3 MCHP_PINMUX(a, 6, b, periph)

#define PA6B_ADC_ADC0_ANN2 MCHP_PINMUX(a, 6, b, periph)

#define PA6D_SERCOM4_PAD3 MCHP_PINMUX(a, 6, d, periph)

#define PA6I_CCL1_IN7 MCHP_PINMUX(a, 6, i, periph)

#define PA6P_PTC_DRV10 MCHP_PINMUX(a, 6, p, periph)

#define PA6P_PTC_PTCXY10 MCHP_PINMUX(a, 6, p, periph)

#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

#define PA7A_EIC_EXTINT7 MCHP_PINMUX(a, 7, a, periph)

#define PA7B_AC_AIN0 MCHP_PINMUX(a, 7, b, periph)

#define PA7B_ADC_ADC0_AIN4 MCHP_PINMUX(a, 7, b, periph)

#define PA7P_PTC_DRV11 MCHP_PINMUX(a, 7, p, periph)

#define PA7P_PTC_PTCXY11 MCHP_PINMUX(a, 7, p, periph)

#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

#define PA8A_EIC_EXTINT8 MCHP_PINMUX(a, 8, a, periph)

#define PA8B_AC_AIN1 MCHP_PINMUX(a, 8, b, periph)

#define PA8B_ADC_ADC0_AIN5 MCHP_PINMUX(a, 8, b, periph)

#define PA8B_ADC_ADC0_ANN4 MCHP_PINMUX(a, 8, b, periph)

#define PA8P_PTC_DRV12 MCHP_PINMUX(a, 8, p, periph)

#define PA8P_PTC_PTCXY12 MCHP_PINMUX(a, 8, p, periph)

#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

#define PA9B_ADC_ADC0_AIN6 MCHP_PINMUX(a, 9, b, periph)

#define PA9I_CCL1_IN6 MCHP_PINMUX(a, 9, i, periph)

#define PA9P_PTC_DRV13 MCHP_PINMUX(a, 9, p, periph)

#define PA9P_PTC_PTCXY13 MCHP_PINMUX(a, 9, p, periph)

#define PB0_GPIO MCHP_PINMUX(b, 0, gpio, gpio)

#define PB0A_EIC_EXTINT0 MCHP_PINMUX(b, 0, a, periph)

#define PB0B_AC_AIN2 MCHP_PINMUX(b, 0, b, periph)

#define PB0B_ADC_ADC0_AIN7 MCHP_PINMUX(b, 0, b, periph)

#define PB0I_CCL1_OUT3 MCHP_PINMUX(b, 0, i, periph)

#define PB0P_PTC_DRV14 MCHP_PINMUX(b, 0, p, periph)

#define PB0P_PTC_PTCXY14 MCHP_PINMUX(b, 0, p, periph)

#define PB1_GPIO MCHP_PINMUX(b, 1, gpio, gpio)

#define PB1A_EIC_EXTINT1 MCHP_PINMUX(b, 1, a, periph)

#define PB2_GPIO MCHP_PINMUX(b, 2, gpio, gpio)

#define PB2A_EIC_EXTINT2 MCHP_PINMUX(b, 2, a, periph)

#define PB3_GPIO MCHP_PINMUX(b, 3, gpio, gpio)

#define PB3A_EIC_EXTINT3 MCHP_PINMUX(b, 3, a, periph)

#define PB3B_AC_AIN3 MCHP_PINMUX(b, 3, b, periph)

#define PB3B_ADC_ADC0_AIN8 MCHP_PINMUX(b, 3, b, periph)

#define PB3D_SERCOM5_PAD0 MCHP_PINMUX(b, 3, d, periph)

#define PB3I_CCL1_IN10 MCHP_PINMUX(b, 3, i, periph)

#define PB3P_PTC_DRV15 MCHP_PINMUX(b, 3, p, periph)

#define PB3P_PTC_PTCXY15 MCHP_PINMUX(b, 3, p, periph)

#define PB4_GPIO MCHP_PINMUX(b, 4, gpio, gpio)

#define PB4A_EIC_EXTINT4 MCHP_PINMUX(b, 4, a, periph)

#define PB4B_ADC_ADC0_AIN9 MCHP_PINMUX(b, 4, b, periph)

#define PB4D_SERCOM5_PAD1 MCHP_PINMUX(b, 4, d, periph)

#define PB4I_CCL1_IN9 MCHP_PINMUX(b, 4, i, periph)

#define PB4P_PTC_DRV16 MCHP_PINMUX(b, 4, p, periph)

#define PB4P_PTC_PTCXY16 MCHP_PINMUX(b, 4, p, periph)

#define PB5_GPIO MCHP_PINMUX(b, 5, gpio, gpio)

#define PB5A_EIC_EXTINT5 MCHP_PINMUX(b, 5, a, periph)

#define PB5B_ADC_ADC0_AIN10 MCHP_PINMUX(b, 5, b, periph)

#define PB5D_SERCOM5_PAD2 MCHP_PINMUX(b, 5, d, periph)

#define PB5I_CCL0_IN9 MCHP_PINMUX(b, 5, i, periph)

#define PB5P_PTC_DRV17 MCHP_PINMUX(b, 5, p, periph)

#define PB5P_PTC_PTCXY17 MCHP_PINMUX(b, 5, p, periph)

#define PB6_GPIO MCHP_PINMUX(b, 6, gpio, gpio)

#define PB6A_EIC_EXTINT6 MCHP_PINMUX(b, 6, a, periph)

#define PB6B_ADC_ADC0_AIN11 MCHP_PINMUX(b, 6, b, periph)

#define PB6D_SERCOM5_PAD3 MCHP_PINMUX(b, 6, d, periph)

#define PB6I_CCL0_IN10 MCHP_PINMUX(b, 6, i, periph)

#define PB6K_GCLK_IO0 MCHP_PINMUX(b, 6, k, periph)

#define PB6P_PTC_DRV18 MCHP_PINMUX(b, 6, p, periph)

#define PB6P_PTC_PTCXY18 MCHP_PINMUX(b, 6, p, periph)

#define PC0_GPIO MCHP_PINMUX(c, 0, gpio, gpio)

#define PC0A_EIC_EXTINT0 MCHP_PINMUX(c, 0, a, periph)

#define PC0D_SERCOM0_PAD0 MCHP_PINMUX(c, 0, d, periph)

#define PC0F_TCC0_WO0 MCHP_PINMUX(c, 0, f, periph)

#define PC0I_CCL0_OUT3 MCHP_PINMUX(c, 0, i, periph)

#define PC0K_GCLK_IO1 MCHP_PINMUX(c, 0, k, periph)

#define PC0P_PTC_DRV19 MCHP_PINMUX(c, 0, p, periph)

#define PC0P_PTC_PTCXY19 MCHP_PINMUX(c, 0, p, periph)

#define PC1_GPIO MCHP_PINMUX(c, 1, gpio, gpio)

#define PC1A_EIC_EXTINT1 MCHP_PINMUX(c, 1, a, periph)

#define PC1D_SERCOM0_PAD1 MCHP_PINMUX(c, 1, d, periph)

#define PC1F_TCC0_WO1 MCHP_PINMUX(c, 1, f, periph)

#define PC1H_CAN0_RX MCHP_PINMUX(c, 1, h, periph)

#define PC1I_CCL0_IN0 MCHP_PINMUX(c, 1, i, periph)

#define PC1K_GCLK_IO2 MCHP_PINMUX(c, 1, k, periph)

#define PC1P_PTC_DRV20 MCHP_PINMUX(c, 1, p, periph)

#define PC1P_PTC_PTCXY20 MCHP_PINMUX(c, 1, p, periph)

#define PC2_GPIO MCHP_PINMUX(c, 2, gpio, gpio)

#define PC2A_EIC_EXTINT2 MCHP_PINMUX(c, 2, a, periph)

#define PC2D_SERCOM0_PAD2 MCHP_PINMUX(c, 2, d, periph)

#define PC2F_TCC1_WO0 MCHP_PINMUX(c, 2, f, periph)

#define PC2H_CAN0_TX MCHP_PINMUX(c, 2, h, periph)

#define PC2I_CCL0_IN1 MCHP_PINMUX(c, 2, i, periph)

#define PC2K_GCLK_IO3 MCHP_PINMUX(c, 2, k, periph)

#define PC2P_PTC_DRV21 MCHP_PINMUX(c, 2, p, periph)

#define PC2P_PTC_PTCXY21 MCHP_PINMUX(c, 2, p, periph)

#define PC3_GPIO MCHP_PINMUX(c, 3, gpio, gpio)

#define PC3A_EIC_EXTINT3 MCHP_PINMUX(c, 3, a, periph)

#define PC3D_SERCOM0_PAD3 MCHP_PINMUX(c, 3, d, periph)

#define PC3F_TCC1_WO1 MCHP_PINMUX(c, 3, f, periph)

#define PC3I_CCL0_OUT0 MCHP_PINMUX(c, 3, i, periph)

#define PC3K_GCLK_IO4 MCHP_PINMUX(c, 3, k, periph)

#define PC3P_PTC_ECI0 MCHP_PINMUX(c, 3, p, periph)

#define PC4_GPIO MCHP_PINMUX(c, 4, gpio, gpio)

#define PC4A_EIC_EXTINT4 MCHP_PINMUX(c, 4, a, periph)

#define PC4D_SERCOM2_PAD0 MCHP_PINMUX(c, 4, d, periph)

#define PC4F_TCC2_WO0 MCHP_PINMUX(c, 4, f, periph)

#define PC4I_CCL1_IN0 MCHP_PINMUX(c, 4, i, periph)

#define PC4K_GCLK_IO5 MCHP_PINMUX(c, 4, k, periph)

#define PC4P_PTC_ECI1 MCHP_PINMUX(c, 4, p, periph)

#define PC5_GPIO MCHP_PINMUX(c, 5, gpio, gpio)

#define PC5A_EIC_EXTINT5 MCHP_PINMUX(c, 5, a, periph)

#define PC5D_SERCOM1_PAD3 MCHP_PINMUX(c, 5, d, periph)

#define PC5F_TCC2_WO1 MCHP_PINMUX(c, 5, f, periph)

#define PC5H_CAN1_RX MCHP_PINMUX(c, 5, h, periph)

#define PC5I_CCL1_IN1 MCHP_PINMUX(c, 5, i, periph)

#define PC5K_GCLK_IO1 MCHP_PINMUX(c, 5, k, periph)

#define PC6_GPIO MCHP_PINMUX(c, 6, gpio, gpio)

#define PC6A_EIC_EXTINT6 MCHP_PINMUX(c, 6, a, periph)

#define PC6D_SERCOM1_PAD2 MCHP_PINMUX(c, 6, d, periph)

#define PC6H_CAN1_TX MCHP_PINMUX(c, 6, h, periph)

#define PC6I_CCL1_OUT0 MCHP_PINMUX(c, 6, i, periph)

#define PD0_GPIO MCHP_PINMUX(d, 0, gpio, gpio)

#define PD0A_EIC_NMI MCHP_PINMUX(d, 0, a, periph)

#define PD0D_SERCOM1_PAD1 MCHP_PINMUX(d, 0, d, periph)

#define PD0F_TCC3_WO0 MCHP_PINMUX(d, 0, f, periph)

#define PD0I_CCL0_IN3 MCHP_PINMUX(d, 0, i, periph)

#define PD1_GPIO MCHP_PINMUX(d, 1, gpio, gpio)

#define PD1A_EIC_EXTINT1 MCHP_PINMUX(d, 1, a, periph)

#define PD1D_SERCOM1_PAD0 MCHP_PINMUX(d, 1, d, periph)

#define PD1F_TCC3_WO1 MCHP_PINMUX(d, 1, f, periph)

#define PD1H_USB_SOF MCHP_PINMUX(d, 1, h, periph)

#define PD1I_CCL0_IN4 MCHP_PINMUX(d, 1, i, periph)

#define PD2_GPIO MCHP_PINMUX(d, 2, gpio, gpio)

#define PD2H_USB_USBDM MCHP_PINMUX(d, 2, h, periph)

#define PD3_GPIO MCHP_PINMUX(d, 3, gpio, gpio)

#define PD3H_USB_USBDP MCHP_PINMUX(d, 3, h, periph)

#define PD4_GPIO MCHP_PINMUX(d, 4, gpio, gpio)

#define PD4A_EIC_EXTINT2 MCHP_PINMUX(d, 4, a, periph)

#define PD4K_GCLK_IO1 MCHP_PINMUX(d, 4, k, periph)

#define PD5_GPIO MCHP_PINMUX(d, 5, gpio, gpio)

#define PD5A_EIC_EXTINT3 MCHP_PINMUX(d, 5, a, periph)

#define PD5K_GCLK_IO0 MCHP_PINMUX(d, 5, k, periph)

#define PD6_GPIO MCHP_PINMUX(d, 6, gpio, gpio)

#define PD6D_SERCOM2_PAD1 MCHP_PINMUX(d, 6, d, periph)

#define PD6H_CAN0_RX MCHP_PINMUX(d, 6, h, periph)

#define PD6I_CCL1_IN3 MCHP_PINMUX(d, 6, i, periph)

#define PD6P_PTC_DRV0 MCHP_PINMUX(d, 6, p, periph)

#define PD6P_PTC_PTCXY0 MCHP_PINMUX(d, 6, p, periph)

#define PD7_GPIO MCHP_PINMUX(d, 7, gpio, gpio)

#define PD7A_EIC_EXTINT4 MCHP_PINMUX(d, 7, a, periph)

#define PD7D_SERCOM2_PAD2 MCHP_PINMUX(d, 7, d, periph)

#define PD7F_TCC4_WO0 MCHP_PINMUX(d, 7, f, periph)

#define PD7I_CCL1_IN4 MCHP_PINMUX(d, 7, i, periph)

#define PD7P_PTC_DRV1 MCHP_PINMUX(d, 7, p, periph)

#define PD7P_PTC_PTCXY1 MCHP_PINMUX(d, 7, p, periph)

#define PD8_GPIO MCHP_PINMUX(d, 8, gpio, gpio)

#define PD8A_EIC_EXTINT5 MCHP_PINMUX(d, 8, a, periph)

#define PD8D_SERCOM2_PAD3 MCHP_PINMUX(d, 8, d, periph)

#define PD8F_TCC4_WO1 MCHP_PINMUX(d, 8, f, periph)

#define PD8H_CAN0_TX MCHP_PINMUX(d, 8, h, periph)

#define PD8I_CCL0_OUT1 MCHP_PINMUX(d, 8, i, periph)

#define PD8P_PTC_DRV2 MCHP_PINMUX(d, 8, p, periph)

#define PD8P_PTC_PTCXY2 MCHP_PINMUX(d, 8, p, periph)

#define PD9_GPIO MCHP_PINMUX(d, 9, gpio, gpio)

#define PD9A_EIC_EXTINT6 MCHP_PINMUX(d, 9, a, periph)

#define PD9D_SERCOM3_PAD0 MCHP_PINMUX(d, 9, d, periph)

#define PD9F_TCC5_WO0 MCHP_PINMUX(d, 9, f, periph)

#define PD9I_CCL1_OUT1 MCHP_PINMUX(d, 9, i, periph)

#define PD9P_PTC_DRV3 MCHP_PINMUX(d, 9, p, periph)

#define PD9P_PTC_PTCXY3 MCHP_PINMUX(d, 9, p, periph)

#endif /* MICROCHIP_PIC32CM5112GC00048_PINCTRL_H_ */
