/*
 * Copyright (c) 2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CM6408PL10048_PINCTRL_H_
#define MICROCHIP_PIC32CM6408PL10048_PINCTRL_H_

#include <dt-bindings/pic32c/pic32cm_pl/common/mchp_pinctrl_pinmux_pic32c.h>

#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

#define PA0A_EIC_EXTINT0 MCHP_PINMUX(a, 0, a, periph)

#define PA0C_SERCOM0_PAD0 MCHP_PINMUX(a, 0, c, periph)

#define PA0D_SERCOM1_PAD0 MCHP_PINMUX(a, 0, d, periph)

#define PA0E_TC0_WO0 MCHP_PINMUX(a, 0, e, periph)

#define PA0F_TCC0_WO0 MCHP_PINMUX(a, 0, f, periph)

#define PA0H_CCL_IN0 MCHP_PINMUX(a, 0, h, periph)

#define PA0I_GCLK_IO1 MCHP_PINMUX(a, 0, i, periph)

#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

#define PA1A_EIC_NMI MCHP_PINMUX(a, 1, a, periph)

#define PA1C_SERCOM0_PAD1 MCHP_PINMUX(a, 1, c, periph)

#define PA1D_SERCOM1_PAD1 MCHP_PINMUX(a, 1, d, periph)

#define PA1E_TC0_WO1 MCHP_PINMUX(a, 1, e, periph)

#define PA1F_TCC0_WO1 MCHP_PINMUX(a, 1, f, periph)

#define PA1H_CCL_IN1 MCHP_PINMUX(a, 1, h, periph)

#define PA1I_GCLK_IO2 MCHP_PINMUX(a, 1, i, periph)

#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

#define PA2B_ADC0_AIN2 MCHP_PINMUX(a, 2, b, periph)

#define PA2C_SERCOM0_PAD2 MCHP_PINMUX(a, 2, c, periph)

#define PA2D_SERCOM1_PAD2 MCHP_PINMUX(a, 2, d, periph)

#define PA2E_TC1_WO0 MCHP_PINMUX(a, 2, e, periph)

#define PA2F_TCC0_WO2 MCHP_PINMUX(a, 2, f, periph)

#define PA2H_CCL_IN2 MCHP_PINMUX(a, 2, h, periph)

#define PA2I_GCLK_IO3 MCHP_PINMUX(a, 2, i, periph)

#define PA2P_PTC_PAD2 MCHP_PINMUX(a, 2, p, periph)

#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

#define PA3B_ADC0_AIN3 MCHP_PINMUX(a, 3, b, periph)

#define PA3C_SERCOM0_PAD3 MCHP_PINMUX(a, 3, c, periph)

#define PA3D_SERCOM1_PAD3 MCHP_PINMUX(a, 3, d, periph)

#define PA3E_TC1_WO1 MCHP_PINMUX(a, 3, e, periph)

#define PA3F_TCC0_WO3 MCHP_PINMUX(a, 3, f, periph)

#define PA3H_CCL_OUT0 MCHP_PINMUX(a, 3, h, periph)

#define PA3I_GCLK_IO0 MCHP_PINMUX(a, 3, i, periph)

#define PA3P_PTC_PAD3 MCHP_PINMUX(a, 3, p, periph)

#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

#define PA4B_ADC0_AIN4 MCHP_PINMUX(a, 4, b, periph)

#define PA4C_SERCOM0_PAD0 MCHP_PINMUX(a, 4, c, periph)

#define PA4I_GCLK_IO1 MCHP_PINMUX(a, 4, i, periph)

#define PA4P_PTC_PAD4 MCHP_PINMUX(a, 4, p, periph)

#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

#define PA5A_EIC_EXTINT5 MCHP_PINMUX(a, 5, a, periph)

#define PA5B_ADC0_AIN5 MCHP_PINMUX(a, 5, b, periph)

#define PA5C_SERCOM0_PAD1 MCHP_PINMUX(a, 5, c, periph)

#define PA5H_AC_CMP1 MCHP_PINMUX(a, 5, h, periph)

#define PA5I_GCLK_IO2 MCHP_PINMUX(a, 5, i, periph)

#define PA5P_PTC_PAD5 MCHP_PINMUX(a, 5, p, periph)

#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

#define PA6B_ADC0_AIN6 MCHP_PINMUX(a, 6, b, periph)

#define PA6C_SERCOM0_PAD2 MCHP_PINMUX(a, 6, c, periph)

#define PA6H_CCL_OUT0 MCHP_PINMUX(a, 6, h, periph)

#define PA6I_GCLK_IO3 MCHP_PINMUX(a, 6, i, periph)

#define PA6P_PTC_PAD6 MCHP_PINMUX(a, 6, p, periph)

#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

#define PA7A_EIC_NMI MCHP_PINMUX(a, 7, a, periph)

#define PA7B_ADC0_AIN7 MCHP_PINMUX(a, 7, b, periph)

#define PA7C_SERCOM0_PAD3 MCHP_PINMUX(a, 7, c, periph)

#define PA7H_AC_CMP0 MCHP_PINMUX(a, 7, h, periph)

#define PA7I_GCLK_IO0 MCHP_PINMUX(a, 7, i, periph)

#define PA7P_PTC_PAD7 MCHP_PINMUX(a, 7, p, periph)

#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

#define PA8A_EIC_EXTINT8 MCHP_PINMUX(a, 8, a, periph)

#define PA8C_SERCOM1_PAD2 MCHP_PINMUX(a, 8, c, periph)

#define PA8D_SERCOM0_PAD2 MCHP_PINMUX(a, 8, d, periph)

#define PA8E_TC1_WO0 MCHP_PINMUX(a, 8, e, periph)

#define PA8F_TCC0_WO0 MCHP_PINMUX(a, 8, f, periph)

#define PA8H_CCL_IN3 MCHP_PINMUX(a, 8, h, periph)

#define PA8I_GCLK_IO1 MCHP_PINMUX(a, 8, i, periph)

#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

#define PA9C_SERCOM1_PAD3 MCHP_PINMUX(a, 9, c, periph)

#define PA9D_SERCOM0_PAD3 MCHP_PINMUX(a, 9, d, periph)

#define PA9E_TC1_WO1 MCHP_PINMUX(a, 9, e, periph)

#define PA9F_TCC0_WO1 MCHP_PINMUX(a, 9, f, periph)

#define PA9H_CCL_IN4 MCHP_PINMUX(a, 9, h, periph)

#define PA9I_GCLK_IO2 MCHP_PINMUX(a, 9, i, periph)

#define PA10_GPIO MCHP_PINMUX(a, 10, gpio, gpio)

#define PA10A_EIC_EXTINT10 MCHP_PINMUX(a, 10, a, periph)

#define PA10C_SERCOM1_PAD0 MCHP_PINMUX(a, 10, c, periph)

#define PA10D_SERCOM0_PAD0 MCHP_PINMUX(a, 10, d, periph)

#define PA10E_TC0_WO0 MCHP_PINMUX(a, 10, e, periph)

#define PA10F_TCC0_WO2 MCHP_PINMUX(a, 10, f, periph)

#define PA10H_CCL_IN5 MCHP_PINMUX(a, 10, h, periph)

#define PA10I_GCLK_IO3 MCHP_PINMUX(a, 10, i, periph)

#define PA11_GPIO MCHP_PINMUX(a, 11, gpio, gpio)

#define PA11A_EIC_EXTINT11 MCHP_PINMUX(a, 11, a, periph)

#define PA11C_SERCOM1_PAD1 MCHP_PINMUX(a, 11, c, periph)

#define PA11D_SERCOM0_PAD1 MCHP_PINMUX(a, 11, d, periph)

#define PA11E_TC0_WO1 MCHP_PINMUX(a, 11, e, periph)

#define PA11F_TCC0_WO3 MCHP_PINMUX(a, 11, f, periph)

#define PA11H_CCL_OUT1 MCHP_PINMUX(a, 11, h, periph)

#define PA11I_GCLK_IO1 MCHP_PINMUX(a, 11, i, periph)

#define PA12_GPIO MCHP_PINMUX(a, 12, gpio, gpio)

#define PA12A_EIC_EXTINT12 MCHP_PINMUX(a, 12, a, periph)

#define PA12C_SERCOM1_PAD2 MCHP_PINMUX(a, 12, c, periph)

#define PA13_GPIO MCHP_PINMUX(a, 13, gpio, gpio)

#define PA13A_EIC_EXTINT13 MCHP_PINMUX(a, 13, a, periph)

#define PA13C_SERCOM1_PAD3 MCHP_PINMUX(a, 13, c, periph)

#define PA13H_AC_CMP1 MCHP_PINMUX(a, 13, h, periph)

#define PA14_GPIO MCHP_PINMUX(a, 14, gpio, gpio)

#define PA14A_EIC_EXTINT14 MCHP_PINMUX(a, 14, a, periph)

#define PA14C_SERCOM1_PAD0 MCHP_PINMUX(a, 14, c, periph)

#define PA14H_CCL_OUT1 MCHP_PINMUX(a, 14, h, periph)

#define PA15_GPIO MCHP_PINMUX(a, 15, gpio, gpio)

#define PA15A_EIC_EXTINT15 MCHP_PINMUX(a, 15, a, periph)

#define PA15C_SERCOM1_PAD1 MCHP_PINMUX(a, 15, c, periph)

#define PA15H_AC_CMP0 MCHP_PINMUX(a, 15, h, periph)

#define PA16_GPIO MCHP_PINMUX(a, 16, gpio, gpio)

#define PA16A_EIC_EXTINT0 MCHP_PINMUX(a, 16, a, periph)

#define PA16B_AC_AC0N1 MCHP_PINMUX(a, 16, b, periph)

#define PA16B_AC_AC1N1 MCHP_PINMUX(a, 16, b, periph)

#define PA16B_ADC0_AIN16 MCHP_PINMUX(a, 16, b, periph)

#define PA16F_TCC0_WO0 MCHP_PINMUX(a, 16, f, periph)

#define PA16H_CCL_IN6 MCHP_PINMUX(a, 16, h, periph)

#define PA16P_PTC_PAD16 MCHP_PINMUX(a, 16, p, periph)

#define PA17_GPIO MCHP_PINMUX(a, 17, gpio, gpio)

#define PA17A_EIC_EXTINT1 MCHP_PINMUX(a, 17, a, periph)

#define PA17B_ADC0_AIN17 MCHP_PINMUX(a, 17, b, periph)

#define PA17F_TCC0_WO1 MCHP_PINMUX(a, 17, f, periph)

#define PA17H_CCL_IN7 MCHP_PINMUX(a, 17, h, periph)

#define PA17P_PTC_PAD17 MCHP_PINMUX(a, 17, p, periph)

#define PA18_GPIO MCHP_PINMUX(a, 18, gpio, gpio)

#define PA18A_EIC_EXTINT2 MCHP_PINMUX(a, 18, a, periph)

#define PA18B_AC_AC0P0 MCHP_PINMUX(a, 18, b, periph)

#define PA18B_AC_AC1P0 MCHP_PINMUX(a, 18, b, periph)

#define PA18B_ADC0_AIN18 MCHP_PINMUX(a, 18, b, periph)

#define PA18F_TCC0_WO2 MCHP_PINMUX(a, 18, f, periph)

#define PA18H_CCL_IN8 MCHP_PINMUX(a, 18, h, periph)

#define PA18P_PTC_PAD18 MCHP_PINMUX(a, 18, p, periph)

#define PA19_GPIO MCHP_PINMUX(a, 19, gpio, gpio)

#define PA19A_EIC_EXTINT3 MCHP_PINMUX(a, 19, a, periph)

#define PA19B_AC_AC0N0 MCHP_PINMUX(a, 19, b, periph)

#define PA19B_AC_AC1P1 MCHP_PINMUX(a, 19, b, periph)

#define PA19B_ADC0_AIN19 MCHP_PINMUX(a, 19, b, periph)

#define PA19F_TCC0_WO3 MCHP_PINMUX(a, 19, f, periph)

#define PA19H_CCL_OUT2 MCHP_PINMUX(a, 19, h, periph)

#define PA19P_PTC_PAD19 MCHP_PINMUX(a, 19, p, periph)

#define PA20_GPIO MCHP_PINMUX(a, 20, gpio, gpio)

#define PA20A_EIC_EXTINT4 MCHP_PINMUX(a, 20, a, periph)

#define PA20B_AC_AC0P5 MCHP_PINMUX(a, 20, b, periph)

#define PA20B_AC_AC1P2 MCHP_PINMUX(a, 20, b, periph)

#define PA20B_ADC0_AIN20 MCHP_PINMUX(a, 20, b, periph)

#define PA20C_SERCOM1_PAD0 MCHP_PINMUX(a, 20, c, periph)

#define PA20E_TC2_WO0 MCHP_PINMUX(a, 20, e, periph)

#define PA20I_GCLK_IO2 MCHP_PINMUX(a, 20, i, periph)

#define PA20P_PTC_PAD20 MCHP_PINMUX(a, 20, p, periph)

#define PA21_GPIO MCHP_PINMUX(a, 21, gpio, gpio)

#define PA21A_EIC_EXTINT5 MCHP_PINMUX(a, 21, a, periph)

#define PA21B_AC_AC0P6 MCHP_PINMUX(a, 21, b, periph)

#define PA21B_AC_AC1N0 MCHP_PINMUX(a, 21, b, periph)

#define PA21B_AC_AC1P5 MCHP_PINMUX(a, 21, b, periph)

#define PA21B_ADC0_AIN21 MCHP_PINMUX(a, 21, b, periph)

#define PA21B_PTC_PTC_EXTCINT MCHP_PINMUX(a, 21, b, periph)

#define PA21E_TC2_WO1 MCHP_PINMUX(a, 21, e, periph)

#define PA21I_GCLK_IO3 MCHP_PINMUX(a, 21, i, periph)

#define PA21P_PTC_PAD21 MCHP_PINMUX(a, 21, p, periph)

#define PA22_GPIO MCHP_PINMUX(a, 22, gpio, gpio)

#define PA22A_EIC_EXTINT6 MCHP_PINMUX(a, 22, a, periph)

#define PA22B_AC_AC0P3 MCHP_PINMUX(a, 22, b, periph)

#define PA22B_AC_AC1P3 MCHP_PINMUX(a, 22, b, periph)

#define PA22B_ADC0_AIN22 MCHP_PINMUX(a, 22, b, periph)

#define PA22B_PTC_PTC_EXTCINT1 MCHP_PINMUX(a, 22, b, periph)

#define PA22C_SERCOM1_PAD2 MCHP_PINMUX(a, 22, c, periph)

#define PA22H_CCL_OUT2 MCHP_PINMUX(a, 22, h, periph)

#define PA22I_GCLK_IO1 MCHP_PINMUX(a, 22, i, periph)

#define PA22P_PTC_PAD22 MCHP_PINMUX(a, 22, p, periph)

#define PA23_GPIO MCHP_PINMUX(a, 23, gpio, gpio)

#define PA23A_EIC_EXTINT7 MCHP_PINMUX(a, 23, a, periph)

#define PA23B_AC_AC0N2 MCHP_PINMUX(a, 23, b, periph)

#define PA23B_AC_AC1N2 MCHP_PINMUX(a, 23, b, periph)

#define PA23B_ADC0_AIN23 MCHP_PINMUX(a, 23, b, periph)

#define PA23B_ADC0_VREFP MCHP_PINMUX(a, 23, b, periph)

#define PA23C_SERCOM1_PAD3 MCHP_PINMUX(a, 23, c, periph)

#define PA23I_GCLK_IO0 MCHP_PINMUX(a, 23, i, periph)

#define PA23P_PTC_PAD23 MCHP_PINMUX(a, 23, p, periph)

#define PA24_GPIO MCHP_PINMUX(a, 24, gpio, gpio)

#define PA24A_EIC_EXTINT8 MCHP_PINMUX(a, 24, a, periph)

#define PA24B_ADC0_AIN24 MCHP_PINMUX(a, 24, b, periph)

#define PA24D_SERCOM1_PAD2 MCHP_PINMUX(a, 24, d, periph)

#define PA24F_TCC0_WO0 MCHP_PINMUX(a, 24, f, periph)

#define PA24H_CCL_IN9 MCHP_PINMUX(a, 24, h, periph)

#define PA24I_GCLK_IO1 MCHP_PINMUX(a, 24, i, periph)

#define PA24P_PTC_PAD24 MCHP_PINMUX(a, 24, p, periph)

#define PA25_GPIO MCHP_PINMUX(a, 25, gpio, gpio)

#define PA25A_EIC_EXTINT9 MCHP_PINMUX(a, 25, a, periph)

#define PA25B_ADC0_AIN25 MCHP_PINMUX(a, 25, b, periph)

#define PA25D_SERCOM1_PAD3 MCHP_PINMUX(a, 25, d, periph)

#define PA25F_TCC0_WO1 MCHP_PINMUX(a, 25, f, periph)

#define PA25H_CCL_IN10 MCHP_PINMUX(a, 25, h, periph)

#define PA25I_GCLK_IO2 MCHP_PINMUX(a, 25, i, periph)

#define PA25P_PTC_PAD25 MCHP_PINMUX(a, 25, p, periph)

#define PA26_GPIO MCHP_PINMUX(a, 26, gpio, gpio)

#define PA26A_EIC_EXTINT10 MCHP_PINMUX(a, 26, a, periph)

#define PA26B_ADC0_AIN26 MCHP_PINMUX(a, 26, b, periph)

#define PA26D_SERCOM1_PAD0 MCHP_PINMUX(a, 26, d, periph)

#define PA26F_TCC0_WO2 MCHP_PINMUX(a, 26, f, periph)

#define PA26H_CCL_IN11 MCHP_PINMUX(a, 26, h, periph)

#define PA26I_GCLK_IO3 MCHP_PINMUX(a, 26, i, periph)

#define PA26P_PTC_PAD26 MCHP_PINMUX(a, 26, p, periph)

#define PA27_GPIO MCHP_PINMUX(a, 27, gpio, gpio)

#define PA27A_EIC_EXTINT11 MCHP_PINMUX(a, 27, a, periph)

#define PA27B_ADC0_AIN27 MCHP_PINMUX(a, 27, b, periph)

#define PA27D_SERCOM1_PAD1 MCHP_PINMUX(a, 27, d, periph)

#define PA27F_TCC0_WO3 MCHP_PINMUX(a, 27, f, periph)

#define PA27H_CCL_OUT3 MCHP_PINMUX(a, 27, h, periph)

#define PA27P_PTC_PAD27 MCHP_PINMUX(a, 27, p, periph)

#define PA28_GPIO MCHP_PINMUX(a, 28, gpio, gpio)

#define PA28A_EIC_EXTINT12 MCHP_PINMUX(a, 28, a, periph)

#define PA28B_ADC0_AIN28 MCHP_PINMUX(a, 28, b, periph)

#define PA28P_PTC_PAD28 MCHP_PINMUX(a, 28, p, periph)

#define PA29_GPIO MCHP_PINMUX(a, 29, gpio, gpio)

#define PA29A_EIC_EXTINT13 MCHP_PINMUX(a, 29, a, periph)

#define PA29B_ADC0_AIN29 MCHP_PINMUX(a, 29, b, periph)

#define PA29I_GCLK_IO1 MCHP_PINMUX(a, 29, i, periph)

#define PA29P_PTC_PAD29 MCHP_PINMUX(a, 29, p, periph)

#define PA30_GPIO MCHP_PINMUX(a, 30, gpio, gpio)

#define PA30A_EIC_NMI MCHP_PINMUX(a, 30, a, periph)

#define PA31_GPIO MCHP_PINMUX(a, 31, gpio, gpio)

#define PA31A_EIC_EXTINT15 MCHP_PINMUX(a, 31, a, periph)

#define PA31B_ADC0_AIN31 MCHP_PINMUX(a, 31, b, periph)

#define PA31C_SERCOM1_PAD0 MCHP_PINMUX(a, 31, c, periph)

#define PA31D_SERCOM0_PAD2 MCHP_PINMUX(a, 31, d, periph)

#define PA31I_GCLK_IO0 MCHP_PINMUX(a, 31, i, periph)

#define PA31P_PTC_PAD31 MCHP_PINMUX(a, 31, p, periph)

#define PB0_GPIO MCHP_PINMUX(b, 0, gpio, gpio)

#define PB0A_EIC_EXTINT0 MCHP_PINMUX(b, 0, a, periph)

#define PB0D_SERCOM1_PAD0 MCHP_PINMUX(b, 0, d, periph)

#define PB0F_TCC0_WO0 MCHP_PINMUX(b, 0, f, periph)

#define PB1_GPIO MCHP_PINMUX(b, 1, gpio, gpio)

#define PB1A_EIC_EXTINT1 MCHP_PINMUX(b, 1, a, periph)

#define PB1D_SERCOM1_PAD1 MCHP_PINMUX(b, 1, d, periph)

#define PB1F_TCC0_WO1 MCHP_PINMUX(b, 1, f, periph)

#define PB2_GPIO MCHP_PINMUX(b, 2, gpio, gpio)

#define PB2A_EIC_EXTINT2 MCHP_PINMUX(b, 2, a, periph)

#define PB2D_SERCOM1_PAD2 MCHP_PINMUX(b, 2, d, periph)

#define PB2F_TCC0_WO2 MCHP_PINMUX(b, 2, f, periph)

#define PB3_GPIO MCHP_PINMUX(b, 3, gpio, gpio)

#define PB3A_EIC_EXTINT3 MCHP_PINMUX(b, 3, a, periph)

#define PB3D_SERCOM1_PAD3 MCHP_PINMUX(b, 3, d, periph)

#define PB3F_TCC0_WO3 MCHP_PINMUX(b, 3, f, periph)

#define PB4_GPIO MCHP_PINMUX(b, 4, gpio, gpio)

#define PB4A_EIC_EXTINT4 MCHP_PINMUX(b, 4, a, periph)

#define PB5_GPIO MCHP_PINMUX(b, 5, gpio, gpio)

#define PB5A_EIC_EXTINT5 MCHP_PINMUX(b, 5, a, periph)

#define PB8_GPIO MCHP_PINMUX(b, 8, gpio, gpio)

#define PB8A_EIC_EXTINT8 MCHP_PINMUX(b, 8, a, periph)

#define PB8B_AC_AC0P1 MCHP_PINMUX(b, 8, b, periph)

#define PB8B_ADC0_AIN40 MCHP_PINMUX(b, 8, b, periph)

#define PB8F_TCC0_WO0 MCHP_PINMUX(b, 8, f, periph)

#define PB8P_PTC_PAD40 MCHP_PINMUX(b, 8, p, periph)

#define PB9_GPIO MCHP_PINMUX(b, 9, gpio, gpio)

#define PB9A_EIC_EXTINT9 MCHP_PINMUX(b, 9, a, periph)

#define PB9B_ADC0_AIN41 MCHP_PINMUX(b, 9, b, periph)

#define PB9F_TCC0_WO1 MCHP_PINMUX(b, 9, f, periph)

#define PB9P_PTC_PAD41 MCHP_PINMUX(b, 9, p, periph)

#define PB10_GPIO MCHP_PINMUX(b, 10, gpio, gpio)

#define PB10A_EIC_EXTINT10 MCHP_PINMUX(b, 10, a, periph)

#define PB10B_AC_AC0P2 MCHP_PINMUX(b, 10, b, periph)

#define PB10B_ADC0_AIN42 MCHP_PINMUX(b, 10, b, periph)

#define PB10F_TCC0_WO2 MCHP_PINMUX(b, 10, f, periph)

#define PB10P_PTC_PAD42 MCHP_PINMUX(b, 10, p, periph)

#define PB11_GPIO MCHP_PINMUX(b, 11, gpio, gpio)

#define PB11A_EIC_EXTINT11 MCHP_PINMUX(b, 11, a, periph)

#define PB11B_ADC0_AIN43 MCHP_PINMUX(b, 11, b, periph)

#define PB11F_TCC0_WO3 MCHP_PINMUX(b, 11, f, periph)

#define PB11P_PTC_PAD43 MCHP_PINMUX(b, 11, p, periph)

#endif /* MICROCHIP_PIC32CM6408PL10048_PINCTRL_H_ */
