/*
 * Copyright (c) 2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file sercom_samd5xe5x.h
 * @brief SERCOM Register and Bit Mask Mapping for SAMD5x/E5x family.
 *
 * This file defines generic register and bit mask names for the SERCOM
 * peripheral on Microchip SAMD5x/E5x devices.These macros are intended for
 * use in the SERCOM UART/SPI G1 driver.
 *
 */

#ifndef MICROCHIP_COMMON_SERCOM_SAMD5XE5X_H_
#define MICROCHIP_COMMON_SERCOM_SAMD5XE5X_H_

/*
 * Both internal (INT) and external (EXT) clock modes use the same hardware
 * register addresses and bit fields; the only difference is in the naming
 * of the registers and definitions. Therefore, INT definitions are used as
 * generic types and macros for unified access in driver code.
 */
typedef sercom_usart_int_registers_t sercom_usart_registers_t;
#define UART_GET_BASE_ADDR(regs, is_clock_external)                            \
  ((sercom_usart_registers_t *)((is_clock_external)                            \
                                    ? (void *)&((regs)->USART_EXT)             \
                                    : (void *)&((regs)->USART_INT)))
/*SERCOM_USART_SYNCBUSY*/
#define SERCOM_USART_SYNCBUSY_Msk SERCOM_USART_INT_SYNCBUSY_Msk

/*SERCOM_USART_CTRLA*/
#define SERCOM_USART_CTRLA_FORM_Msk SERCOM_USART_INT_CTRLA_FORM_Msk
#define SERCOM_USART_CTRLA_FORM_USART_FRAME_WITH_PARITY                        \
  SERCOM_USART_INT_CTRLA_FORM_USART_FRAME_WITH_PARITY
#define SERCOM_USART_CTRLA_FORM_USART_FRAME_NO_PARITY                          \
  SERCOM_USART_INT_CTRLA_FORM_USART_FRAME_NO_PARITY
#define SERCOM_USART_CTRLA_RXPO_Msk SERCOM_USART_INT_CTRLA_RXPO_Msk
#define SERCOM_USART_CTRLA_TXPO_Msk SERCOM_USART_INT_CTRLA_TXPO_Msk
#define SERCOM_USART_CTRLA_RXPO(rxpo) SERCOM_USART_INT_CTRLA_RXPO(rxpo)
#define SERCOM_USART_CTRLA_TXPO(txpo) SERCOM_USART_INT_CTRLA_TXPO(txpo)
#define SERCOM_USART_CTRLA_CPOL_Msk SERCOM_USART_INT_CTRLA_CPOL_Msk
#define SERCOM_USART_CTRLA_MODE_Msk SERCOM_USART_INT_CTRLA_MODE_Msk
#define SERCOM_USART_CTRLA_MODE_USART_EXT                                      \
  SERCOM_USART_INT_CTRLA_MODE_USART_EXT_CLK
#define SERCOM_USART_CTRLA_MODE_USART_INT                                      \
  SERCOM_USART_INT_CTRLA_MODE_USART_INT_CLK
#define SERCOM_USART_CTRLA_DORD_Msk SERCOM_USART_INT_CTRLA_DORD_Msk
#define SERCOM_USART_CTRLA_SAMPR_Msk SERCOM_USART_INT_CTRLA_SAMPR_Msk
#define SERCOM_USART_CTRLA_ENABLE_Msk SERCOM_USART_INT_CTRLA_ENABLE_Msk
#define SERCOM_USART_CTRLA_RUNSTDBY_Msk SERCOM_USART_INT_CTRLA_RUNSTDBY_Msk

/*SERCOM_USART_CTRLB*/
#define SERCOM_USART_CTRLB_PMODE_Msk SERCOM_USART_INT_CTRLB_PMODE_Msk
#define SERCOM_USART_CTRLB_SBMODE_Msk SERCOM_USART_INT_CTRLB_SBMODE_Msk
#define SERCOM_USART_CTRLB_CHSIZE_Msk SERCOM_USART_INT_CTRLB_CHSIZE_Msk
#define SERCOM_USART_CTRLB_CHSIZE_5_BIT SERCOM_USART_INT_CTRLB_CHSIZE_5_BIT
#define SERCOM_USART_CTRLB_CHSIZE_6_BIT SERCOM_USART_INT_CTRLB_CHSIZE_6_BIT
#define SERCOM_USART_CTRLB_CHSIZE_7_BIT SERCOM_USART_INT_CTRLB_CHSIZE_7_BIT
#define SERCOM_USART_CTRLB_CHSIZE_8_BIT SERCOM_USART_INT_CTRLB_CHSIZE_8_BIT
#define SERCOM_USART_CTRLB_CHSIZE_9_BIT SERCOM_USART_INT_CTRLB_CHSIZE_9_BIT
#define SERCOM_USART_CTRLB_RXEN_Msk SERCOM_USART_INT_CTRLB_RXEN_Msk
#define SERCOM_USART_CTRLB_TXEN_Msk SERCOM_USART_INT_CTRLB_TXEN_Msk

/*SERCOM_USART_STATUS*/
#define SERCOM_USART_STATUS_BUFOVF_Msk SERCOM_USART_INT_STATUS_BUFOVF_Msk
#define SERCOM_USART_STATUS_FERR_Msk SERCOM_USART_INT_STATUS_FERR_Msk
#define SERCOM_USART_STATUS_PERR_Msk SERCOM_USART_INT_STATUS_PERR_Msk
#define SERCOM_USART_STATUS_ISF_Msk SERCOM_USART_INT_STATUS_ISF_Msk
#define SERCOM_USART_STATUS_COLL_Msk SERCOM_USART_INT_STATUS_COLL_Msk

/*SERCOM_USART_INTENSET*/
#define SERCOM_USART_INTENSET_TXC_Msk SERCOM_USART_INT_INTENSET_TXC_Msk
#define SERCOM_USART_INTENSET_RXC_Msk SERCOM_USART_INT_INTENSET_RXC_Msk
#define SERCOM_USART_INTENSET_DRE_Msk SERCOM_USART_INT_INTENSET_DRE_Msk
#define SERCOM_USART_INTENSET_ERROR_Msk SERCOM_USART_INT_INTENSET_ERROR_Msk

/*SERCOM_USART_INTENCLR*/
#define SERCOM_USART_INTENCLR_TXC_Msk SERCOM_USART_INT_INTENCLR_TXC_Msk
#define SERCOM_USART_INTENCLR_RXC_Msk SERCOM_USART_INT_INTENCLR_RXC_Msk
#define SERCOM_USART_INTENCLR_Msk SERCOM_USART_INT_INTENCLR_Msk
#define SERCOM_USART_INTENCLR_DRE_Msk SERCOM_USART_INT_INTENCLR_DRE_Msk
#define SERCOM_USART_INTENCLR_ERROR_Msk SERCOM_USART_INT_INTENCLR_ERROR_Msk

/*SERCOM_USART_INTFLAG*/
#define SERCOM_USART_INTFLAG_RXC_Msk SERCOM_USART_INT_INTFLAG_RXC_Msk
#define SERCOM_USART_INTFLAG_DRE_Msk SERCOM_USART_INT_INTFLAG_DRE_Msk
#define SERCOM_USART_INTFLAG_TXC_Msk SERCOM_USART_INT_INTFLAG_TXC_Msk
#define SERCOM_USART_INTFLAG_ERROR_Msk SERCOM_USART_INT_INTFLAG_ERROR_Msk
#define SERCOM_USART_INTFLAG_RXBRK_Msk SERCOM_USART_INT_INTFLAG_RXBRK_Msk
#define SERCOM_USART_INTFLAG_CTSIC_Msk SERCOM_USART_INT_INTFLAG_CTSIC_Msk
#define SERCOM_USART_INTFLAG_RXS_Msk SERCOM_USART_INT_INTFLAG_RXS_Msk

/*
 * Both Master and Slave modes use the same hardware register addresses and bit
 * fields; the only difference is in the naming,of the registers and
 * definitions. SPIS and SPIM. Therefore, those definitions are used as generic
 * types and macros for unified access in driver code.
 */
typedef sercom_spim_registers_t sercom_spi_registers_t;

#define SPI_GET_BASE_ADDR(regs, is_slave)                                      \
  ((sercom_spi_registers_t *)(((bool)is_slave) ? (void *)&((regs)->SPIS)             \
                                         : (void *)&((regs)->SPIM)))
/*SERCOM_SPI_SYNCBUSY*/
#define SERCOM_SPI_SYNCBUSY_ENABLE_Msk SERCOM_SPIM_SYNCBUSY_ENABLE_Msk
#define SERCOM_SPI_SYNCBUSY_CTRLB_Msk SERCOM_SPIM_SYNCBUSY_CTRLB_Msk

/*SERCOM_SPI_CTRLA*/
#define SERCOM_SPI_CTRLA_ENABLE_Msk SERCOM_SPIM_CTRLA_ENABLE_Msk
#define SERCOM_SPI_CTRLA_MODE_Msk SERCOM_SPIM_CTRLA_MODE_Msk
#define SERCOM_SPI_CTRLA_MODE_SPI_MASTER SERCOM_SPIM_CTRLA_MODE_SPI_MASTER
#define SERCOM_SPI_CTRLA_MODE_SPI_SLAVE SERCOM_SPIM_CTRLA_MODE_SPI_SLAVE
#define SERCOM_SPI_CTRLA_DORD_Msk SERCOM_SPIM_CTRLA_DORD_Msk
#define SERCOM_SPI_CTRLA_DORD_MSB SERCOM_SPIM_CTRLA_DORD_MSB
#define SERCOM_SPI_CTRLA_DORD_LSB SERCOM_SPIM_CTRLA_DORD_LSB
#define SERCOM_SPI_CTRLA_CPOL_Msk SERCOM_SPIM_CTRLA_CPOL_Msk
#define SERCOM_SPI_CTRLA_CPOL_IDLE_LOW SERCOM_SPIM_CTRLA_CPOL_IDLE_LOW
#define SERCOM_SPI_CTRLA_CPOL_IDLE_HIGH SERCOM_SPIM_CTRLA_CPOL_IDLE_HIGH
#define SERCOM_SPI_CTRLA_CPHA_Msk SERCOM_SPIM_CTRLA_CPHA_Msk
#define SERCOM_SPI_CTRLA_CPHA_LEADING_EDGE SERCOM_SPIM_CTRLA_CPHA_LEADING_EDGE
#define SERCOM_SPI_CTRLA_CPHA_TRAILING_EDGE SERCOM_SPIM_CTRLA_CPHA_TRAILING_EDGE
#define SERCOM_SPI_CTRLA_DIPO_Msk SERCOM_SPIM_CTRLA_DIPO_Msk
#define SERCOM_SPI_CTRLA_DOPO_Msk SERCOM_SPIM_CTRLA_DOPO_Msk
#define SERCOM_SPI_CTRLA_DIPO_MUX0 SERCOM_SPIM_CTRLA_DIPO_PAD0
#define SERCOM_SPI_CTRLA_DOPO_MUX0 SERCOM_SPIM_CTRLA_DOPO_PAD0
#define SERCOM_SPI_CTRLA_IBON_Msk SERCOM_SPIM_CTRLA_IBON_Msk
#define SERCOM_SPI_CTRLA_DIPO(value) SERCOM_SPIM_CTRLA_DIPO(value)
#define SERCOM_SPI_CTRLA_DOPO(value) SERCOM_SPIM_CTRLA_DOPO(value)

/*SERCOM_SPI_CTRLB*/
#define SERCOM_SPI_CTRLB_RXEN_Msk SERCOM_SPIM_CTRLB_RXEN_Msk
#define SERCOM_SPI_CTRLB_CHSIZE_Msk SERCOM_SPIM_CTRLB_CHSIZE_Msk
#define SERCOM_SPI_CTRLB_CHSIZE_8_BIT SERCOM_SPIM_CTRLB_CHSIZE_8_BIT
#define SERCOM_SPI_CTRLB_PLOADEN_Msk SERCOM_SPIM_CTRLB_PLOADEN_Msk
#define SERCOM_SPI_CTRLB_SSDE_Msk SERCOM_SPIM_CTRLB_SSDE_Msk
#define SERCOM_SPI_CTRLB_MSSEN_Msk SERCOM_SPIM_CTRLB_MSSEN_Msk

/*SERCOM_SPI_STATUS*/
#define SERCOM_SPI_STATUS_BUFOVF_Msk SERCOM_SPIM_STATUS_BUFOVF_Msk

/*SERCOM_SPI_INTENSET*/
#define SERCOM_SPI_INTENSET_TXC_Msk SERCOM_SPIM_INTENSET_TXC_Msk
#define SERCOM_SPI_INTENSET_DRE_Msk SERCOM_SPIM_INTENSET_DRE_Msk
#define SERCOM_SPI_INTENSET_SSL_Msk SERCOM_SPIM_INTENSET_SSL_Msk
#define SERCOM_SPI_INTENSET_RXC_Msk SERCOM_SPIM_INTENSET_RXC_Msk

/*SERCOM_SPI_INTENCLR*/
#define SERCOM_SPI_INTENCLR_RXC_Msk SERCOM_SPIM_INTENCLR_RXC_Msk
#define SERCOM_SPI_INTENCLR_TXC_Msk SERCOM_SPIM_INTENCLR_TXC_Msk
#define SERCOM_SPI_INTENCLR_DRE_Msk SERCOM_SPIM_INTENCLR_DRE_Msk
#define SERCOM_SPI_INTENCLR_Msk SERCOM_SPIM_INTENCLR_Msk

/*SERCOM_SPI_INTFLAG*/
#define SERCOM_SPI_INTFLAG_RXC_Msk SERCOM_SPIM_INTFLAG_RXC_Msk
#define SERCOM_SPI_INTFLAG_TXC_Msk SERCOM_SPIM_INTFLAG_TXC_Msk
#define SERCOM_SPI_INTFLAG_DRE_Msk SERCOM_SPIM_INTFLAG_DRE_Msk
#define SERCOM_SPI_INTFLAG_SSL_Msk SERCOM_SPIM_INTFLAG_SSL_Msk
#define SERCOM_SPI_INTFLAG_ERROR_Msk SERCOM_SPIM_INTFLAG_ERROR_Msk
#define SERCOM_SPI_INTFLAG_Msk SERCOM_SPIM_INTFLAG_Msk

#endif /* MICROCHIP_COMMON_SERCOM_SAMD5XE5X_H_ */
