/*
 * Copyright (c) 2025 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CZ8110CA90176_PINCTRL_H_
#define MICROCHIP_PIC32CZ8110CA90176_PINCTRL_H_

#include <dt-bindings/pic32c/pic32cz_ca/common/mchp_pinctrl_pinmux_pic32c.h>

/* pa0_gpio */
#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

/* pa0a_eic_extint0 */
#define PA0A_EIC_EXTINT0 MCHP_PINMUX(a, 0, a, periph)

/* pa0k_eth_gtx1 */
#define PA0K_ETH_GTX1 MCHP_PINMUX(a, 0, k, periph)

/* pa1_gpio */
#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

/* pa1a_eic_extint1 */
#define PA1A_EIC_EXTINT1 MCHP_PINMUX(a, 1, a, periph)

/* pa1k_eth_gtx0 */
#define PA1K_ETH_GTX0 MCHP_PINMUX(a, 1, k, periph)

/* pa2_gpio */
#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

/* pa2a_eic_extint2 */
#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

/* pa2f_tcc2_wo5 */
#define PA2F_TCC2_WO5 MCHP_PINMUX(a, 2, f, periph)

/* pa2k_eth_gtxen */
#define PA2K_ETH_GTXEN MCHP_PINMUX(a, 2, k, periph)

/* pa3_gpio */
#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

/* pa3a_eic_extint3 */
#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

/* pa3d_sercom2_pad3 */
#define PA3D_SERCOM2_PAD3 MCHP_PINMUX(a, 3, d, periph)

/* pa3f_tcc2_wo4 */
#define PA3F_TCC2_WO4 MCHP_PINMUX(a, 3, f, periph)

/* pa3k_eth_gmdc */
#define PA3K_ETH_GMDC MCHP_PINMUX(a, 3, k, periph)

/* pa4_gpio */
#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

/* pa4a_eic_extint4 */
#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

/* pa4d_sercom2_pad2 */
#define PA4D_SERCOM2_PAD2 MCHP_PINMUX(a, 4, d, periph)

/* pa4f_tcc2_wo3 */
#define PA4F_TCC2_WO3 MCHP_PINMUX(a, 4, f, periph)

/* pa4k_eth_gmdio */
#define PA4K_ETH_GMDIO MCHP_PINMUX(a, 4, k, periph)

/* pa5_gpio */
#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

/* pa5a_eic_extint4 */
#define PA5A_EIC_EXTINT4 MCHP_PINMUX(a, 5, a, periph)

/* pa5f_tcc3_wo0 */
#define PA5F_TCC3_WO0 MCHP_PINMUX(a, 5, f, periph)

/* pa5k_eth_grxdv */
#define PA5K_ETH_GRXDV MCHP_PINMUX(a, 5, k, periph)

/* pa6_gpio */
#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

/* pa6a_eic_extint6 */
#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

/* pa6f_tcc3_wo1 */
#define PA6F_TCC3_WO1 MCHP_PINMUX(a, 6, f, periph)

/* pa6k_eth_grxer */
#define PA6K_ETH_GRXER MCHP_PINMUX(a, 6, k, periph)

/* pa7_gpio */
#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

/* pa7a_eic_extint7 */
#define PA7A_EIC_EXTINT7 MCHP_PINMUX(a, 7, a, periph)

/* pa7b_adc3_ain3 */
#define PA7B_ADC3_AIN3 MCHP_PINMUX(a, 7, b, periph)

/* pa8_gpio */
#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

/* pa8a_eic_extint8 */
#define PA8A_EIC_EXTINT8 MCHP_PINMUX(a, 8, a, periph)

/* pa8b_adc3_ain2 */
#define PA8B_ADC3_AIN2 MCHP_PINMUX(a, 8, b, periph)

/* pa9_gpio */
#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

/* pa9a_eic_extint9 */
#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

/* pa9b_adc3_ain1 */
#define PA9B_ADC3_AIN1 MCHP_PINMUX(a, 9, b, periph)

/* pa10_gpio */
#define PA10_GPIO MCHP_PINMUX(a, 10, gpio, gpio)

/* pa10a_eic_extint10 */
#define PA10A_EIC_EXTINT10 MCHP_PINMUX(a, 10, a, periph)

/* pa10b_adc3_ain0 */
#define PA10B_ADC3_AIN0 MCHP_PINMUX(a, 10, b, periph)

/* pa11_gpio */
#define PA11_GPIO MCHP_PINMUX(a, 11, gpio, gpio)

/* pa11a_eic_extint11 */
#define PA11A_EIC_EXTINT11 MCHP_PINMUX(a, 11, a, periph)

/* pa11b_adc2_ain3 */
#define PA11B_ADC2_AIN3 MCHP_PINMUX(a, 11, b, periph)

/* pa12_gpio */
#define PA12_GPIO MCHP_PINMUX(a, 12, gpio, gpio)

/* pa12a_eic_extint12 */
#define PA12A_EIC_EXTINT12 MCHP_PINMUX(a, 12, a, periph)

/* pa12b_adc2_ain2 */
#define PA12B_ADC2_AIN2 MCHP_PINMUX(a, 12, b, periph)

/* pa13_gpio */
#define PA13_GPIO MCHP_PINMUX(a, 13, gpio, gpio)

/* pa13a_eic_extint13 */
#define PA13A_EIC_EXTINT13 MCHP_PINMUX(a, 13, a, periph)

/* pa13b_adc2_ain1 */
#define PA13B_ADC2_AIN1 MCHP_PINMUX(a, 13, b, periph)

/* pa14_gpio */
#define PA14_GPIO MCHP_PINMUX(a, 14, gpio, gpio)

/* pa14a_eic_extint14 */
#define PA14A_EIC_EXTINT14 MCHP_PINMUX(a, 14, a, periph)

/* pa14b_adc2_ain0 */
#define PA14B_ADC2_AIN0 MCHP_PINMUX(a, 14, b, periph)

/* pa15_gpio */
#define PA15_GPIO MCHP_PINMUX(a, 15, gpio, gpio)

/* pa15a_eic_extint15 */
#define PA15A_EIC_EXTINT15 MCHP_PINMUX(a, 15, a, periph)

/* pa15b_adc1_ain3 */
#define PA15B_ADC1_AIN3 MCHP_PINMUX(a, 15, b, periph)

/* pa16_gpio */
#define PA16_GPIO MCHP_PINMUX(a, 16, gpio, gpio)

/* pa16a_eic_extint0 */
#define PA16A_EIC_EXTINT0 MCHP_PINMUX(a, 16, a, periph)

/* pa16b_adc1_ain2 */
#define PA16B_ADC1_AIN2 MCHP_PINMUX(a, 16, b, periph)

/* pa17_gpio */
#define PA17_GPIO MCHP_PINMUX(a, 17, gpio, gpio)

/* pa17a_eic_extint1 */
#define PA17A_EIC_EXTINT1 MCHP_PINMUX(a, 17, a, periph)

/* pa17b_adc1_ain1 */
#define PA17B_ADC1_AIN1 MCHP_PINMUX(a, 17, b, periph)

/* pa18_gpio */
#define PA18_GPIO MCHP_PINMUX(a, 18, gpio, gpio)

/* pa18a_eic_extint2 */
#define PA18A_EIC_EXTINT2 MCHP_PINMUX(a, 18, a, periph)

/* pa18b_adc1_ain0 */
#define PA18B_ADC1_AIN0 MCHP_PINMUX(a, 18, b, periph)

/* pa19_gpio */
#define PA19_GPIO MCHP_PINMUX(a, 19, gpio, gpio)

/* pa19a_eic_extint3 */
#define PA19A_EIC_EXTINT3 MCHP_PINMUX(a, 19, a, periph)

/* pa19b_ac_ain3 */
#define PA19B_AC_AIN3 MCHP_PINMUX(a, 19, b, periph)

/* pa19b_adc0_ain5 */
#define PA19B_ADC0_AIN5 MCHP_PINMUX(a, 19, b, periph)

/* pa20_gpio */
#define PA20_GPIO MCHP_PINMUX(a, 20, gpio, gpio)

/* pa20a_eic_extint4 */
#define PA20A_EIC_EXTINT4 MCHP_PINMUX(a, 20, a, periph)

/* pa20b_ac_ain2 */
#define PA20B_AC_AIN2 MCHP_PINMUX(a, 20, b, periph)

/* pa20b_adc0_ain4 */
#define PA20B_ADC0_AIN4 MCHP_PINMUX(a, 20, b, periph)

/* pa21_gpio */
#define PA21_GPIO MCHP_PINMUX(a, 21, gpio, gpio)

/* pa21a_eic_extint5 */
#define PA21A_EIC_EXTINT5 MCHP_PINMUX(a, 21, a, periph)

/* pa21f_tcc8_wo0 */
#define PA21F_TCC8_WO0 MCHP_PINMUX(a, 21, f, periph)

/* pa21h_can5_tx */
#define PA21H_CAN5_TX MCHP_PINMUX(a, 21, h, periph)

/* pa21k_eth_txck */
#define PA21K_ETH_TXCK MCHP_PINMUX(a, 21, k, periph)

/* pa22_gpio */
#define PA22_GPIO MCHP_PINMUX(a, 22, gpio, gpio)

/* pa22a_eic_extint6 */
#define PA22A_EIC_EXTINT6 MCHP_PINMUX(a, 22, a, periph)

/* pa22f_tcc7_wo0 */
#define PA22F_TCC7_WO0 MCHP_PINMUX(a, 22, f, periph)

/* pa22k_eth_tsucomp */
#define PA22K_ETH_TSUCOMP MCHP_PINMUX(a, 22, k, periph)

/* pa23_gpio */
#define PA23_GPIO MCHP_PINMUX(a, 23, gpio, gpio)

/* pa23a_eic_extint7 */
#define PA23A_EIC_EXTINT7 MCHP_PINMUX(a, 23, a, periph)

/* pa23f_tcc7_wo1 */
#define PA23F_TCC7_WO1 MCHP_PINMUX(a, 23, f, periph)

/* pa24_gpio */
#define PA24_GPIO MCHP_PINMUX(a, 24, gpio, gpio)

/* pa24a_eic_extint8 */
#define PA24A_EIC_EXTINT8 MCHP_PINMUX(a, 24, a, periph)

/* pa24b_adc3_ain5 */
#define PA24B_ADC3_AIN5 MCHP_PINMUX(a, 24, b, periph)

/* pa25_gpio */
#define PA25_GPIO MCHP_PINMUX(a, 25, gpio, gpio)

/* pa25a_eic_extint9 */
#define PA25A_EIC_EXTINT9 MCHP_PINMUX(a, 25, a, periph)

/* pa25b_adc3_ain4 */
#define PA25B_ADC3_AIN4 MCHP_PINMUX(a, 25, b, periph)

/* pa26_gpio */
#define PA26_GPIO MCHP_PINMUX(a, 26, gpio, gpio)

/* pa26a_eic_extint10 */
#define PA26A_EIC_EXTINT10 MCHP_PINMUX(a, 26, a, periph)

/* pa26b_adc2_ain5 */
#define PA26B_ADC2_AIN5 MCHP_PINMUX(a, 26, b, periph)

/* pa27_gpio */
#define PA27_GPIO MCHP_PINMUX(a, 27, gpio, gpio)

/* pa27a_eic_extint11 */
#define PA27A_EIC_EXTINT11 MCHP_PINMUX(a, 27, a, periph)

/* pa27b_adc2_ain4 */
#define PA27B_ADC2_AIN4 MCHP_PINMUX(a, 27, b, periph)

/* pa28_gpio */
#define PA28_GPIO MCHP_PINMUX(a, 28, gpio, gpio)

/* pa28a_eic_extint12 */
#define PA28A_EIC_EXTINT12 MCHP_PINMUX(a, 28, a, periph)

/* pa28b_adc1_ain5 */
#define PA28B_ADC1_AIN5 MCHP_PINMUX(a, 28, b, periph)

/* pa29_gpio */
#define PA29_GPIO MCHP_PINMUX(a, 29, gpio, gpio)

/* pa29a_eic_extint13 */
#define PA29A_EIC_EXTINT13 MCHP_PINMUX(a, 29, a, periph)

/* pa29b_adc1_ain4 */
#define PA29B_ADC1_AIN4 MCHP_PINMUX(a, 29, b, periph)

/* pa30_gpio */
#define PA30_GPIO MCHP_PINMUX(a, 30, gpio, gpio)

/* pa30a_eic_extint14 */
#define PA30A_EIC_EXTINT14 MCHP_PINMUX(a, 30, a, periph)

/* pa30h_can4_rx */
#define PA30H_CAN4_RX MCHP_PINMUX(a, 30, h, periph)

/* pa30j_spi_ixs1_fsync */
#define PA30J_SPI_IXS1_FSYNC MCHP_PINMUX(a, 30, j, periph)

/* pa31_gpio */
#define PA31_GPIO MCHP_PINMUX(a, 31, gpio, gpio)

/* pa31a_eic_extint15 */
#define PA31A_EIC_EXTINT15 MCHP_PINMUX(a, 31, a, periph)

/* pa31h_can4_tx */
#define PA31H_CAN4_TX MCHP_PINMUX(a, 31, h, periph)

/* pa31j_spi_ixs1_mclk1 */
#define PA31J_SPI_IXS1_MCLK1 MCHP_PINMUX(a, 31, j, periph)

/* pb0_gpio */
#define PB0_GPIO MCHP_PINMUX(b, 0, gpio, gpio)

/* pb0a_eic_extint0 */
#define PB0A_EIC_EXTINT0 MCHP_PINMUX(b, 0, a, periph)

/* pb0b_ac_ain1 */
#define PB0B_AC_AIN1 MCHP_PINMUX(b, 0, b, periph)

/* pb0b_adc0_ain3 */
#define PB0B_ADC0_AIN3 MCHP_PINMUX(b, 0, b, periph)

/* pb1_gpio */
#define PB1_GPIO MCHP_PINMUX(b, 1, gpio, gpio)

/* pb1a_eic_extint1 */
#define PB1A_EIC_EXTINT1 MCHP_PINMUX(b, 1, a, periph)

/* pb1b_ac_ain0 */
#define PB1B_AC_AIN0 MCHP_PINMUX(b, 1, b, periph)

/* pb1b_adc0_ain2 */
#define PB1B_ADC0_AIN2 MCHP_PINMUX(b, 1, b, periph)

/* pb2_gpio */
#define PB2_GPIO MCHP_PINMUX(b, 2, gpio, gpio)

/* pb2a_eic_extint2 */
#define PB2A_EIC_EXTINT2 MCHP_PINMUX(b, 2, a, periph)

/* pb2b_adc0_ain1 */
#define PB2B_ADC0_AIN1 MCHP_PINMUX(b, 2, b, periph)

/* pb3_gpio */
#define PB3_GPIO MCHP_PINMUX(b, 3, gpio, gpio)

/* pb3a_eic_extint3 */
#define PB3A_EIC_EXTINT3 MCHP_PINMUX(b, 3, a, periph)

/* pb3b_adc0_ain0 */
#define PB3B_ADC0_AIN0 MCHP_PINMUX(b, 3, b, periph)

/* pb4_gpio */
#define PB4_GPIO MCHP_PINMUX(b, 4, gpio, gpio)

/* pb4a_eic_extint4 */
#define PB4A_EIC_EXTINT4 MCHP_PINMUX(b, 4, a, periph)

/* pb5_gpio */
#define PB5_GPIO MCHP_PINMUX(b, 5, gpio, gpio)

/* pb5a_eic_extint5 */
#define PB5A_EIC_EXTINT5 MCHP_PINMUX(b, 5, a, periph)

/* pb6_gpio */
#define PB6_GPIO MCHP_PINMUX(b, 6, gpio, gpio)

/* pb6a_eic_extint6 */
#define PB6A_EIC_EXTINT6 MCHP_PINMUX(b, 6, a, periph)

/* pb6p_ptc_drv11 */
#define PB6P_PTC_DRV11 MCHP_PINMUX(b, 6, p, periph)

/* pb7_gpio */
#define PB7_GPIO MCHP_PINMUX(b, 7, gpio, gpio)

/* pb7a_eic_extint7 */
#define PB7A_EIC_EXTINT7 MCHP_PINMUX(b, 7, a, periph)

/* pb7p_ptc_drv10 */
#define PB7P_PTC_DRV10 MCHP_PINMUX(b, 7, p, periph)

/* pb8_gpio */
#define PB8_GPIO MCHP_PINMUX(b, 8, gpio, gpio)

/* pb8a_eic_extint8 */
#define PB8A_EIC_EXTINT8 MCHP_PINMUX(b, 8, a, periph)

/* pb8p_ptc_drv9 */
#define PB8P_PTC_DRV9 MCHP_PINMUX(b, 8, p, periph)

/* pb9_gpio */
#define PB9_GPIO MCHP_PINMUX(b, 9, gpio, gpio)

/* pb9a_eic_extint9 */
#define PB9A_EIC_EXTINT9 MCHP_PINMUX(b, 9, a, periph)

/* pb9p_ptc_drv8 */
#define PB9P_PTC_DRV8 MCHP_PINMUX(b, 9, p, periph)

/* pb10_gpio */
#define PB10_GPIO MCHP_PINMUX(b, 10, gpio, gpio)

/* pb10a_eic_extint10 */
#define PB10A_EIC_EXTINT10 MCHP_PINMUX(b, 10, a, periph)

/* pb10f_tcc1_wo0 */
#define PB10F_TCC1_WO0 MCHP_PINMUX(b, 10, f, periph)

/* pb10p_ptc_drv7 */
#define PB10P_PTC_DRV7 MCHP_PINMUX(b, 10, p, periph)

/* pb11_gpio */
#define PB11_GPIO MCHP_PINMUX(b, 11, gpio, gpio)

/* pb11a_eic_extint11 */
#define PB11A_EIC_EXTINT11 MCHP_PINMUX(b, 11, a, periph)

/* pb11f_tcc1_wo1 */
#define PB11F_TCC1_WO1 MCHP_PINMUX(b, 11, f, periph)

/* pb11p_ptc_drv6 */
#define PB11P_PTC_DRV6 MCHP_PINMUX(b, 11, p, periph)

/* pb12_gpio */
#define PB12_GPIO MCHP_PINMUX(b, 12, gpio, gpio)

/* pb12a_eic_extint12 */
#define PB12A_EIC_EXTINT12 MCHP_PINMUX(b, 12, a, periph)

/* pb12f_tcc1_wo2 */
#define PB12F_TCC1_WO2 MCHP_PINMUX(b, 12, f, periph)

/* pb12p_ptc_drv5 */
#define PB12P_PTC_DRV5 MCHP_PINMUX(b, 12, p, periph)

/* pb13_gpio */
#define PB13_GPIO MCHP_PINMUX(b, 13, gpio, gpio)

/* pb13a_eic_extint13 */
#define PB13A_EIC_EXTINT13 MCHP_PINMUX(b, 13, a, periph)

/* pb13f_tcc1_wo3 */
#define PB13F_TCC1_WO3 MCHP_PINMUX(b, 13, f, periph)

/* pb13p_ptc_drv4 */
#define PB13P_PTC_DRV4 MCHP_PINMUX(b, 13, p, periph)

/* pb14_gpio */
#define PB14_GPIO MCHP_PINMUX(b, 14, gpio, gpio)

/* pb14a_eic_extint14 */
#define PB14A_EIC_EXTINT14 MCHP_PINMUX(b, 14, a, periph)

/* pb14f_tcc1_wo4 */
#define PB14F_TCC1_WO4 MCHP_PINMUX(b, 14, f, periph)

/* pb14p_ptc_drv3 */
#define PB14P_PTC_DRV3 MCHP_PINMUX(b, 14, p, periph)

/* pb15_gpio */
#define PB15_GPIO MCHP_PINMUX(b, 15, gpio, gpio)

/* pb15a_eic_extint15 */
#define PB15A_EIC_EXTINT15 MCHP_PINMUX(b, 15, a, periph)

/* pb15f_tcc1_wo5 */
#define PB15F_TCC1_WO5 MCHP_PINMUX(b, 15, f, periph)

/* pb15p_ptc_drv2 */
#define PB15P_PTC_DRV2 MCHP_PINMUX(b, 15, p, periph)

/* pb16_gpio */
#define PB16_GPIO MCHP_PINMUX(b, 16, gpio, gpio)

/* pb16a_eic_extint0 */
#define PB16A_EIC_EXTINT0 MCHP_PINMUX(b, 16, a, periph)

/* pb16f_tcc1_wo6 */
#define PB16F_TCC1_WO6 MCHP_PINMUX(b, 16, f, periph)

/* pb16p_ptc_drv1 */
#define PB16P_PTC_DRV1 MCHP_PINMUX(b, 16, p, periph)

/* pb17_gpio */
#define PB17_GPIO MCHP_PINMUX(b, 17, gpio, gpio)

/* pb17a_eic_extint1 */
#define PB17A_EIC_EXTINT1 MCHP_PINMUX(b, 17, a, periph)

/* pb17f_tcc1_wo7 */
#define PB17F_TCC1_WO7 MCHP_PINMUX(b, 17, f, periph)

/* pb17p_ptc_drv0 */
#define PB17P_PTC_DRV0 MCHP_PINMUX(b, 17, p, periph)

/* pb18_gpio */
#define PB18_GPIO MCHP_PINMUX(b, 18, gpio, gpio)

/* pb18a_eic_extint2 */
#define PB18A_EIC_EXTINT2 MCHP_PINMUX(b, 18, a, periph)

/* pb18b_adc0_ain6 */
#define PB18B_ADC0_AIN6 MCHP_PINMUX(b, 18, b, periph)

/* pb19_gpio */
#define PB19_GPIO MCHP_PINMUX(b, 19, gpio, gpio)

/* pb19a_eic_extint3 */
#define PB19A_EIC_EXTINT3 MCHP_PINMUX(b, 19, a, periph)

/* pb19b_adc0_ain7 */
#define PB19B_ADC0_AIN7 MCHP_PINMUX(b, 19, b, periph)

/* pb20_gpio */
#define PB20_GPIO MCHP_PINMUX(b, 20, gpio, gpio)

/* pb20a_eic_extint4 */
#define PB20A_EIC_EXTINT4 MCHP_PINMUX(b, 20, a, periph)

/* pb20b_adc0_ain8 */
#define PB20B_ADC0_AIN8 MCHP_PINMUX(b, 20, b, periph)

/* pb21_gpio */
#define PB21_GPIO MCHP_PINMUX(b, 21, gpio, gpio)

/* pb21a_eic_extint5 */
#define PB21A_EIC_EXTINT5 MCHP_PINMUX(b, 21, a, periph)

/* pb21p_ptc_drv17 */
#define PB21P_PTC_DRV17 MCHP_PINMUX(b, 21, p, periph)

/* pb22_gpio */
#define PB22_GPIO MCHP_PINMUX(b, 22, gpio, gpio)

/* pb22a_eic_extint6 */
#define PB22A_EIC_EXTINT6 MCHP_PINMUX(b, 22, a, periph)

/* pb22p_ptc_drv16 */
#define PB22P_PTC_DRV16 MCHP_PINMUX(b, 22, p, periph)

/* pb23_gpio */
#define PB23_GPIO MCHP_PINMUX(b, 23, gpio, gpio)

/* pb23a_eic_extint7 */
#define PB23A_EIC_EXTINT7 MCHP_PINMUX(b, 23, a, periph)

/* pb23p_ptc_drv15 */
#define PB23P_PTC_DRV15 MCHP_PINMUX(b, 23, p, periph)

/* pb24_gpio */
#define PB24_GPIO MCHP_PINMUX(b, 24, gpio, gpio)

/* pb24a_eic_extint8 */
#define PB24A_EIC_EXTINT8 MCHP_PINMUX(b, 24, a, periph)

/* pb24p_ptc_drv14 */
#define PB24P_PTC_DRV14 MCHP_PINMUX(b, 24, p, periph)

/* pb25_gpio */
#define PB25_GPIO MCHP_PINMUX(b, 25, gpio, gpio)

/* pb25a_eic_extint9 */
#define PB25A_EIC_EXTINT9 MCHP_PINMUX(b, 25, a, periph)

/* pb25p_ptc_drv13 */
#define PB25P_PTC_DRV13 MCHP_PINMUX(b, 25, p, periph)

/* pb26_gpio */
#define PB26_GPIO MCHP_PINMUX(b, 26, gpio, gpio)

/* pb26a_eic_extint10 */
#define PB26A_EIC_EXTINT10 MCHP_PINMUX(b, 26, a, periph)

/* pb26p_ptc_drv12 */
#define PB26P_PTC_DRV12 MCHP_PINMUX(b, 26, p, periph)

/* pb27_gpio */
#define PB27_GPIO MCHP_PINMUX(b, 27, gpio, gpio)

/* pb27a_eic_extint11 */
#define PB27A_EIC_EXTINT11 MCHP_PINMUX(b, 27, a, periph)

/* pb27p_ptc_drv23 */
#define PB27P_PTC_DRV23 MCHP_PINMUX(b, 27, p, periph)

/* pb28_gpio */
#define PB28_GPIO MCHP_PINMUX(b, 28, gpio, gpio)

/* pb28a_eic_extint12 */
#define PB28A_EIC_EXTINT12 MCHP_PINMUX(b, 28, a, periph)

/* pb28p_ptc_drv22 */
#define PB28P_PTC_DRV22 MCHP_PINMUX(b, 28, p, periph)

/* pb29_gpio */
#define PB29_GPIO MCHP_PINMUX(b, 29, gpio, gpio)

/* pb29a_eic_extint13 */
#define PB29A_EIC_EXTINT13 MCHP_PINMUX(b, 29, a, periph)

/* pb29p_ptc_drv20 */
#define PB29P_PTC_DRV20 MCHP_PINMUX(b, 29, p, periph)

/* pb30_gpio */
#define PB30_GPIO MCHP_PINMUX(b, 30, gpio, gpio)

/* pb30a_eic_extint14 */
#define PB30A_EIC_EXTINT14 MCHP_PINMUX(b, 30, a, periph)

/* pb30p_ptc_drv19 */
#define PB30P_PTC_DRV19 MCHP_PINMUX(b, 30, p, periph)

/* pb31_gpio */
#define PB31_GPIO MCHP_PINMUX(b, 31, gpio, gpio)

/* pb31a_eic_extint15 */
#define PB31A_EIC_EXTINT15 MCHP_PINMUX(b, 31, a, periph)

/* pb31p_ptc_drv18 */
#define PB31P_PTC_DRV18 MCHP_PINMUX(b, 31, p, periph)

/* pc0_gpio */
#define PC0_GPIO MCHP_PINMUX(c, 0, gpio, gpio)

/* pc0a_eic_extint0 */
#define PC0A_EIC_EXTINT0 MCHP_PINMUX(c, 0, a, periph)

/* pc0d_sercom0_pad0 */
#define PC0D_SERCOM0_PAD0 MCHP_PINMUX(c, 0, d, periph)

/* pc0f_tcc0_wo0 */
#define PC0F_TCC0_WO0 MCHP_PINMUX(c, 0, f, periph)

/* pc0j_spi_ixs0_fsync */
#define PC0J_SPI_IXS0_FSYNC MCHP_PINMUX(c, 0, j, periph)

/* pc0m_gclk_io4 */
#define PC0M_GCLK_IO4 MCHP_PINMUX(c, 0, m, periph)

/* pc1_gpio */
#define PC1_GPIO MCHP_PINMUX(c, 1, gpio, gpio)

/* pc1a_eic_extint1 */
#define PC1A_EIC_EXTINT1 MCHP_PINMUX(c, 1, a, periph)

/* pc1d_sercom0_pad1 */
#define PC1D_SERCOM0_PAD1 MCHP_PINMUX(c, 1, d, periph)

/* pc1f_tcc0_wo1 */
#define PC1F_TCC0_WO1 MCHP_PINMUX(c, 1, f, periph)

/* pc1j_spi_ixs0_sck */
#define PC1J_SPI_IXS0_SCK MCHP_PINMUX(c, 1, j, periph)

/* pc1m_gclk_io5 */
#define PC1M_GCLK_IO5 MCHP_PINMUX(c, 1, m, periph)

/* pc2_gpio */
#define PC2_GPIO MCHP_PINMUX(c, 2, gpio, gpio)

/* pc2a_eic_extint1 */
#define PC2A_EIC_EXTINT1 MCHP_PINMUX(c, 2, a, periph)

/* pc2d_sercom0_pad2 */
#define PC2D_SERCOM0_PAD2 MCHP_PINMUX(c, 2, d, periph)

/* pc2f_tcc0_wo2 */
#define PC2F_TCC0_WO2 MCHP_PINMUX(c, 2, f, periph)

/* pc2j_spi_ixs0_sdi */
#define PC2J_SPI_IXS0_SDI MCHP_PINMUX(c, 2, j, periph)

/* pc2m_gclk_io6 */
#define PC2M_GCLK_IO6 MCHP_PINMUX(c, 2, m, periph)

/* pc2p_ptc_eci0 */
#define PC2P_PTC_ECI0 MCHP_PINMUX(c, 2, p, periph)

/* pc3_gpio */
#define PC3_GPIO MCHP_PINMUX(c, 3, gpio, gpio)

/* pc3a_eic_extint3 */
#define PC3A_EIC_EXTINT3 MCHP_PINMUX(c, 3, a, periph)

/* pc3d_sercom0_pad3 */
#define PC3D_SERCOM0_PAD3 MCHP_PINMUX(c, 3, d, periph)

/* pc3f_tcc0_wo3 */
#define PC3F_TCC0_WO3 MCHP_PINMUX(c, 3, f, periph)

/* pc3j_spi_ixs0_sdo */
#define PC3J_SPI_IXS0_SDO MCHP_PINMUX(c, 3, j, periph)

/* pc3m_gclk_io7 */
#define PC3M_GCLK_IO7 MCHP_PINMUX(c, 3, m, periph)

/* pc3p_ptc_eci1 */
#define PC3P_PTC_ECI1 MCHP_PINMUX(c, 3, p, periph)

/* pc4_gpio */
#define PC4_GPIO MCHP_PINMUX(c, 4, gpio, gpio)

/* pc4a_eic_extint4 */
#define PC4A_EIC_EXTINT4 MCHP_PINMUX(c, 4, a, periph)

/* pc4d_sercom1_pad0 */
#define PC4D_SERCOM1_PAD0 MCHP_PINMUX(c, 4, d, periph)

/* pc4e_ebi_nwe_nwr0 */
#define PC4E_EBI_NWE_NWR0 MCHP_PINMUX(c, 4, e, periph)

/* pc4f_tcc0_wo4 */
#define PC4F_TCC0_WO4 MCHP_PINMUX(c, 4, f, periph)

/* pc4h_can0_rx */
#define PC4H_CAN0_RX MCHP_PINMUX(c, 4, h, periph)

/* pc4j_spi_ixs0_mclk0 */
#define PC4J_SPI_IXS0_MCLK0 MCHP_PINMUX(c, 4, j, periph)

/* pc5_gpio */
#define PC5_GPIO MCHP_PINMUX(c, 5, gpio, gpio)

/* pc5a_eic_extint5 */
#define PC5A_EIC_EXTINT5 MCHP_PINMUX(c, 5, a, periph)

/* pc5d_sercom1_pad1 */
#define PC5D_SERCOM1_PAD1 MCHP_PINMUX(c, 5, d, periph)

/* pc5e_ebi_nrd */
#define PC5E_EBI_NRD MCHP_PINMUX(c, 5, e, periph)

/* pc5f_tcc0_wo5 */
#define PC5F_TCC0_WO5 MCHP_PINMUX(c, 5, f, periph)

/* pc5h_can0_tx */
#define PC5H_CAN0_TX MCHP_PINMUX(c, 5, h, periph)

/* pc5k_eth_tsucomp */
#define PC5K_ETH_TSUCOMP MCHP_PINMUX(c, 5, k, periph)

/* pc6_gpio */
#define PC6_GPIO MCHP_PINMUX(c, 6, gpio, gpio)

/* pc6a_eic_extint6 */
#define PC6A_EIC_EXTINT6 MCHP_PINMUX(c, 6, a, periph)

/* pc6b_ac_cmp1 */
#define PC6B_AC_CMP1 MCHP_PINMUX(c, 6, b, periph)

/* pc6d_sercom1_pad2 */
#define PC6D_SERCOM1_PAD2 MCHP_PINMUX(c, 6, d, periph)

/* pc6e_ebi_nbs1_nwr1 */
#define PC6E_EBI_NBS1_NWR1 MCHP_PINMUX(c, 6, e, periph)

/* pc6f_tcc0_wo6 */
#define PC6F_TCC0_WO6 MCHP_PINMUX(c, 6, f, periph)

/* pc6h_can1_rx */
#define PC6H_CAN1_RX MCHP_PINMUX(c, 6, h, periph)

/* pc7_gpio */
#define PC7_GPIO MCHP_PINMUX(c, 7, gpio, gpio)

/* pc7a_eic_extint7 */
#define PC7A_EIC_EXTINT7 MCHP_PINMUX(c, 7, a, periph)

/* pc7b_ac_cmp0 */
#define PC7B_AC_CMP0 MCHP_PINMUX(c, 7, b, periph)

/* pc7d_sercom1_pad3 */
#define PC7D_SERCOM1_PAD3 MCHP_PINMUX(c, 7, d, periph)

/* pc7e_ebi_ncs1 */
#define PC7E_EBI_NCS1 MCHP_PINMUX(c, 7, e, periph)

/* pc7f_tcc0_wo7 */
#define PC7F_TCC0_WO7 MCHP_PINMUX(c, 7, f, periph)

/* pc7h_can1_tx */
#define PC7H_CAN1_TX MCHP_PINMUX(c, 7, h, periph)

/* pc8_gpio */
#define PC8_GPIO MCHP_PINMUX(c, 8, gpio, gpio)

/* pc8a_eic_extint8 */
#define PC8A_EIC_EXTINT8 MCHP_PINMUX(c, 8, a, periph)

/* pc8d_sercom2_pad0 */
#define PC8D_SERCOM2_PAD0 MCHP_PINMUX(c, 8, d, periph)

/* pc8e_ebi_ncs0 */
#define PC8E_EBI_NCS0 MCHP_PINMUX(c, 8, e, periph)

/* pc8f_tcc5_wo0 */
#define PC8F_TCC5_WO0 MCHP_PINMUX(c, 8, f, periph)

/* pc8h_sqi0_clk */
#define PC8H_SQI0_CLK MCHP_PINMUX(c, 8, h, periph)

/* pc8i_sdmmc0_sdck */
#define PC8I_SDMMC0_SDCK MCHP_PINMUX(c, 8, i, periph)

/* pc9_gpio */
#define PC9_GPIO MCHP_PINMUX(c, 9, gpio, gpio)

/* pc9a_eic_extint9 */
#define PC9A_EIC_EXTINT9 MCHP_PINMUX(c, 9, a, periph)

/* pc9d_sercom2_pad1 */
#define PC9D_SERCOM2_PAD1 MCHP_PINMUX(c, 9, d, periph)

/* pc9e_ebi_a22 */
#define PC9E_EBI_A22 MCHP_PINMUX(c, 9, e, periph)

/* pc9f_tcc5_wo1 */
#define PC9F_TCC5_WO1 MCHP_PINMUX(c, 9, f, periph)

/* pc9h_sqi0_data0 */
#define PC9H_SQI0_DATA0 MCHP_PINMUX(c, 9, h, periph)

/* pc9i_sdmmc0_sddat0 */
#define PC9I_SDMMC0_SDDAT0 MCHP_PINMUX(c, 9, i, periph)

/* pc10_gpio */
#define PC10_GPIO MCHP_PINMUX(c, 10, gpio, gpio)

/* pc10a_eic_extint10 */
#define PC10A_EIC_EXTINT10 MCHP_PINMUX(c, 10, a, periph)

/* pc10d_sercom2_pad2 */
#define PC10D_SERCOM2_PAD2 MCHP_PINMUX(c, 10, d, periph)

/* pc10e_ebi_a14 */
#define PC10E_EBI_A14 MCHP_PINMUX(c, 10, e, periph)

/* pc10f_tcc6_wo0 */
#define PC10F_TCC6_WO0 MCHP_PINMUX(c, 10, f, periph)

/* pc10h_sqi0_data1 */
#define PC10H_SQI0_DATA1 MCHP_PINMUX(c, 10, h, periph)

/* pc10i_sdmmc0_sddat1 */
#define PC10I_SDMMC0_SDDAT1 MCHP_PINMUX(c, 10, i, periph)

/* pc11_gpio */
#define PC11_GPIO MCHP_PINMUX(c, 11, gpio, gpio)

/* pc11a_eic_extint11 */
#define PC11A_EIC_EXTINT11 MCHP_PINMUX(c, 11, a, periph)

/* pc11d_sercom2_pad3 */
#define PC11D_SERCOM2_PAD3 MCHP_PINMUX(c, 11, d, periph)

/* pc11e_ebi_a13 */
#define PC11E_EBI_A13 MCHP_PINMUX(c, 11, e, periph)

/* pc11f_tcc6_wo1 */
#define PC11F_TCC6_WO1 MCHP_PINMUX(c, 11, f, periph)

/* pc11h_sqi0_data2 */
#define PC11H_SQI0_DATA2 MCHP_PINMUX(c, 11, h, periph)

/* pc11i_sdmmc0_sddat2 */
#define PC11I_SDMMC0_SDDAT2 MCHP_PINMUX(c, 11, i, periph)

/* pc12_gpio */
#define PC12_GPIO MCHP_PINMUX(c, 12, gpio, gpio)

/* pc12a_eic_extint12 */
#define PC12A_EIC_EXTINT12 MCHP_PINMUX(c, 12, a, periph)

/* pc12d_sercom3_pad0 */
#define PC12D_SERCOM3_PAD0 MCHP_PINMUX(c, 12, d, periph)

/* pc12e_ebi_a9 */
#define PC12E_EBI_A9 MCHP_PINMUX(c, 12, e, periph)

/* pc12f_tcc4_wo0 */
#define PC12F_TCC4_WO0 MCHP_PINMUX(c, 12, f, periph)

/* pc12h_sqi0_data3 */
#define PC12H_SQI0_DATA3 MCHP_PINMUX(c, 12, h, periph)

/* pc12i_sdmmc0_sddat3 */
#define PC12I_SDMMC0_SDDAT3 MCHP_PINMUX(c, 12, i, periph)

/* pc13_gpio */
#define PC13_GPIO MCHP_PINMUX(c, 13, gpio, gpio)

/* pc13a_eic_extint13 */
#define PC13A_EIC_EXTINT13 MCHP_PINMUX(c, 13, a, periph)

/* pc13d_sercom3_pad1 */
#define PC13D_SERCOM3_PAD1 MCHP_PINMUX(c, 13, d, periph)

/* pc13e_ebi_a8 */
#define PC13E_EBI_A8 MCHP_PINMUX(c, 13, e, periph)

/* pc13f_tcc4_wo1 */
#define PC13F_TCC4_WO1 MCHP_PINMUX(c, 13, f, periph)

/* pc13h_sqi0_cs0 */
#define PC13H_SQI0_CS0 MCHP_PINMUX(c, 13, h, periph)

/* pc13i_sdmmc0_sdcmd */
#define PC13I_SDMMC0_SDCMD MCHP_PINMUX(c, 13, i, periph)

/* pc14_gpio */
#define PC14_GPIO MCHP_PINMUX(c, 14, gpio, gpio)

/* pc14a_eic_extint14 */
#define PC14A_EIC_EXTINT14 MCHP_PINMUX(c, 14, a, periph)

/* pc14d_sercom3_pad2 */
#define PC14D_SERCOM3_PAD2 MCHP_PINMUX(c, 14, d, periph)

/* pc14e_ebi_a6 */
#define PC14E_EBI_A6 MCHP_PINMUX(c, 14, e, periph)

/* pc14f_tcc8_wo0 */
#define PC14F_TCC8_WO0 MCHP_PINMUX(c, 14, f, periph)

/* pc14i_sdmmc0_sdwp */
#define PC14I_SDMMC0_SDWP MCHP_PINMUX(c, 14, i, periph)

/* pc15_gpio */
#define PC15_GPIO MCHP_PINMUX(c, 15, gpio, gpio)

/* pc15a_eic_extint15 */
#define PC15A_EIC_EXTINT15 MCHP_PINMUX(c, 15, a, periph)

/* pc15d_sercom3_pad3 */
#define PC15D_SERCOM3_PAD3 MCHP_PINMUX(c, 15, d, periph)

/* pc15e_ebi_a5 */
#define PC15E_EBI_A5 MCHP_PINMUX(c, 15, e, periph)

/* pc15f_tcc8_wo1 */
#define PC15F_TCC8_WO1 MCHP_PINMUX(c, 15, f, periph)

/* pc15h_sqi0_cs1 */
#define PC15H_SQI0_CS1 MCHP_PINMUX(c, 15, h, periph)

/* pc15i_sdmmc0_sdcd */
#define PC15I_SDMMC0_SDCD MCHP_PINMUX(c, 15, i, periph)

/* pc17_gpio */
#define PC17_GPIO MCHP_PINMUX(c, 17, gpio, gpio)

/* pc17a_eic_extint1 */
#define PC17A_EIC_EXTINT1 MCHP_PINMUX(c, 17, a, periph)

/* pc17d_sercom1_pad3 */
#define PC17D_SERCOM1_PAD3 MCHP_PINMUX(c, 17, d, periph)

/* pc17e_ebi_a4 */
#define PC17E_EBI_A4 MCHP_PINMUX(c, 17, e, periph)

/* pc17g_bsdap_tdi */
#define PC17G_BSDAP_TDI MCHP_PINMUX(c, 17, g, periph)

/* pc17k_eth_tsucomp */
#define PC17K_ETH_TSUCOMP MCHP_PINMUX(c, 17, k, periph)

/* pc18_gpio */
#define PC18_GPIO MCHP_PINMUX(c, 18, gpio, gpio)

/* pc18a_eic_extint2 */
#define PC18A_EIC_EXTINT2 MCHP_PINMUX(c, 18, a, periph)

/* pc18d_sercom1_pad2 */
#define PC18D_SERCOM1_PAD2 MCHP_PINMUX(c, 18, d, periph)

/* pc18e_ebi_a3 */
#define PC18E_EBI_A3 MCHP_PINMUX(c, 18, e, periph)

/* pc18g_bsdap_tms_swdio */
#define PC18G_BSDAP_TMS_SWDIO MCHP_PINMUX(c, 18, g, periph)

/* pc19_gpio */
#define PC19_GPIO MCHP_PINMUX(c, 19, gpio, gpio)

/* pc19a_eic_extint3 */
#define PC19A_EIC_EXTINT3 MCHP_PINMUX(c, 19, a, periph)

/* pc19d_sercom1_pad1 */
#define PC19D_SERCOM1_PAD1 MCHP_PINMUX(c, 19, d, periph)

/* pc19e_ebi_a2 */
#define PC19E_EBI_A2 MCHP_PINMUX(c, 19, e, periph)

/* pc19g_bsdap_tdo */
#define PC19G_BSDAP_TDO MCHP_PINMUX(c, 19, g, periph)

/* pc19h_can0_rx */
#define PC19H_CAN0_RX MCHP_PINMUX(c, 19, h, periph)

/* pc19m_gclk_io1 */
#define PC19M_GCLK_IO1 MCHP_PINMUX(c, 19, m, periph)

/* pc20_gpio */
#define PC20_GPIO MCHP_PINMUX(c, 20, gpio, gpio)

/* pc20a_eic_nmi */
#define PC20A_EIC_NMI MCHP_PINMUX(c, 20, a, periph)

/* pc20d_sercom1_pad0 */
#define PC20D_SERCOM1_PAD0 MCHP_PINMUX(c, 20, d, periph)

/* pc20e_ebi_a1 */
#define PC20E_EBI_A1 MCHP_PINMUX(c, 20, e, periph)

/* pc20f_tcc9_wo5 */
#define PC20F_TCC9_WO5 MCHP_PINMUX(c, 20, f, periph)

/* pc20g_bsdap_tck_swclk */
#define PC20G_BSDAP_TCK_SWCLK MCHP_PINMUX(c, 20, g, periph)

/* pc20h_can0_tx */
#define PC20H_CAN0_TX MCHP_PINMUX(c, 20, h, periph)

/* pc20m_gclk_io0 */
#define PC20M_GCLK_IO0 MCHP_PINMUX(c, 20, m, periph)

/* pc21_gpio */
#define PC21_GPIO MCHP_PINMUX(c, 21, gpio, gpio)

/* pc21a_eic_extint5 */
#define PC21A_EIC_EXTINT5 MCHP_PINMUX(c, 21, a, periph)

/* pc21d_sercom4_pad0 */
#define PC21D_SERCOM4_PAD0 MCHP_PINMUX(c, 21, d, periph)

/* pc21e_ebi_ncs3 */
#define PC21E_EBI_NCS3 MCHP_PINMUX(c, 21, e, periph)

/* pc21f_tcc6_wo0 */
#define PC21F_TCC6_WO0 MCHP_PINMUX(c, 21, f, periph)

/* pc22_gpio */
#define PC22_GPIO MCHP_PINMUX(c, 22, gpio, gpio)

/* pc22a_eic_extint6 */
#define PC22A_EIC_EXTINT6 MCHP_PINMUX(c, 22, a, periph)

/* pc22d_sercom4_pad1 */
#define PC22D_SERCOM4_PAD1 MCHP_PINMUX(c, 22, d, periph)

/* pc22e_ebi_ncs2 */
#define PC22E_EBI_NCS2 MCHP_PINMUX(c, 22, e, periph)

/* pc22f_tcc6_wo1 */
#define PC22F_TCC6_WO1 MCHP_PINMUX(c, 22, f, periph)

/* pc23_gpio */
#define PC23_GPIO MCHP_PINMUX(c, 23, gpio, gpio)

/* pc23a_eic_extint7 */
#define PC23A_EIC_EXTINT7 MCHP_PINMUX(c, 23, a, periph)

/* pc23d_sercom4_pad2 */
#define PC23D_SERCOM4_PAD2 MCHP_PINMUX(c, 23, d, periph)

/* pc23e_ebi_nbs0_a0 */
#define PC23E_EBI_NBS0_A0 MCHP_PINMUX(c, 23, e, periph)

/* pc23f_tcc5_wo0 */
#define PC23F_TCC5_WO0 MCHP_PINMUX(c, 23, f, periph)

/* pc24_gpio */
#define PC24_GPIO MCHP_PINMUX(c, 24, gpio, gpio)

/* pc24a_eic_extint8 */
#define PC24A_EIC_EXTINT8 MCHP_PINMUX(c, 24, a, periph)

/* pc24d_sercom4_pad3 */
#define PC24D_SERCOM4_PAD3 MCHP_PINMUX(c, 24, d, periph)

/* pc24e_ebi_a23 */
#define PC24E_EBI_A23 MCHP_PINMUX(c, 24, e, periph)

/* pc24f_tcc5_wo1 */
#define PC24F_TCC5_WO1 MCHP_PINMUX(c, 24, f, periph)

/* pc25_gpio */
#define PC25_GPIO MCHP_PINMUX(c, 25, gpio, gpio)

/* pc25a_eic_extint9 */
#define PC25A_EIC_EXTINT9 MCHP_PINMUX(c, 25, a, periph)

/* pc25d_sercom5_pad0 */
#define PC25D_SERCOM5_PAD0 MCHP_PINMUX(c, 25, d, periph)

/* pc25e_ebi_a21 */
#define PC25E_EBI_A21 MCHP_PINMUX(c, 25, e, periph)

/* pc25h_can2_rx */
#define PC25H_CAN2_RX MCHP_PINMUX(c, 25, h, periph)

/* pc26_gpio */
#define PC26_GPIO MCHP_PINMUX(c, 26, gpio, gpio)

/* pc26a_eic_extint10 */
#define PC26A_EIC_EXTINT10 MCHP_PINMUX(c, 26, a, periph)

/* pc26d_sercom5_pad1 */
#define PC26D_SERCOM5_PAD1 MCHP_PINMUX(c, 26, d, periph)

/* pc26e_ebi_a18 */
#define PC26E_EBI_A18 MCHP_PINMUX(c, 26, e, periph)

/* pc26h_can2_tx */
#define PC26H_CAN2_TX MCHP_PINMUX(c, 26, h, periph)

/* pc27_gpio */
#define PC27_GPIO MCHP_PINMUX(c, 27, gpio, gpio)

/* pc27a_eic_extint11 */
#define PC27A_EIC_EXTINT11 MCHP_PINMUX(c, 27, a, periph)

/* pc27d_sercom5_pad2 */
#define PC27D_SERCOM5_PAD2 MCHP_PINMUX(c, 27, d, periph)

/* pc27e_ebi_a12 */
#define PC27E_EBI_A12 MCHP_PINMUX(c, 27, e, periph)

/* pc27i_sdmmc1_sdwp */
#define PC27I_SDMMC1_SDWP MCHP_PINMUX(c, 27, i, periph)

/* pc28_gpio */
#define PC28_GPIO MCHP_PINMUX(c, 28, gpio, gpio)

/* pc28a_eic_extint12 */
#define PC28A_EIC_EXTINT12 MCHP_PINMUX(c, 28, a, periph)

/* pc28d_sercom5_pad3 */
#define PC28D_SERCOM5_PAD3 MCHP_PINMUX(c, 28, d, periph)

/* pc28e_ebi_a10 */
#define PC28E_EBI_A10 MCHP_PINMUX(c, 28, e, periph)

/* pc28h_sqi1_cs1 */
#define PC28H_SQI1_CS1 MCHP_PINMUX(c, 28, h, periph)

/* pc28i_sdmmc1_sdcd */
#define PC28I_SDMMC1_SDCD MCHP_PINMUX(c, 28, i, periph)

/* pc29_gpio */
#define PC29_GPIO MCHP_PINMUX(c, 29, gpio, gpio)

/* pc29a_eic_extint13 */
#define PC29A_EIC_EXTINT13 MCHP_PINMUX(c, 29, a, periph)

/* pc29e_ebi_a7 */
#define PC29E_EBI_A7 MCHP_PINMUX(c, 29, e, periph)

/* pc29f_tcc4_wo0 */
#define PC29F_TCC4_WO0 MCHP_PINMUX(c, 29, f, periph)

/* pc29h_can3_rx */
#define PC29H_CAN3_RX MCHP_PINMUX(c, 29, h, periph)

/* pc30_gpio */
#define PC30_GPIO MCHP_PINMUX(c, 30, gpio, gpio)

/* pc30a_eic_extint14 */
#define PC30A_EIC_EXTINT14 MCHP_PINMUX(c, 30, a, periph)

/* pc30d_sercom6_pad0 */
#define PC30D_SERCOM6_PAD0 MCHP_PINMUX(c, 30, d, periph)

/* pc30e_ebi_a20 */
#define PC30E_EBI_A20 MCHP_PINMUX(c, 30, e, periph)

/* pc30h_sqi1_clk */
#define PC30H_SQI1_CLK MCHP_PINMUX(c, 30, h, periph)

/* pc30i_sdmmc1_sdck */
#define PC30I_SDMMC1_SDCK MCHP_PINMUX(c, 30, i, periph)

/* pc31_gpio */
#define PC31_GPIO MCHP_PINMUX(c, 31, gpio, gpio)

/* pc31a_eic_extint15 */
#define PC31A_EIC_EXTINT15 MCHP_PINMUX(c, 31, a, periph)

/* pc31d_sercom6_pad1 */
#define PC31D_SERCOM6_PAD1 MCHP_PINMUX(c, 31, d, periph)

/* pc31e_ebi_a19 */
#define PC31E_EBI_A19 MCHP_PINMUX(c, 31, e, periph)

/* pc31h_sqi1_data0 */
#define PC31H_SQI1_DATA0 MCHP_PINMUX(c, 31, h, periph)

/* pc31i_sdmmc1_sddat0 */
#define PC31I_SDMMC1_SDDAT0 MCHP_PINMUX(c, 31, i, periph)

/* pd0_gpio */
#define PD0_GPIO MCHP_PINMUX(d, 0, gpio, gpio)

/* pd0a_eic_extint0 */
#define PD0A_EIC_EXTINT0 MCHP_PINMUX(d, 0, a, periph)

/* pd0m_gclk_io2 */
#define PD0M_GCLK_IO2 MCHP_PINMUX(d, 0, m, periph)

/* pd1_gpio */
#define PD1_GPIO MCHP_PINMUX(d, 1, gpio, gpio)

/* pd1a_eic_extint1 */
#define PD1A_EIC_EXTINT1 MCHP_PINMUX(d, 1, a, periph)

/* pd1m_gclk_io3 */
#define PD1M_GCLK_IO3 MCHP_PINMUX(d, 1, m, periph)

/* pd2_gpio */
#define PD2_GPIO MCHP_PINMUX(d, 2, gpio, gpio)

/* pd2a_eic_extint2 */
#define PD2A_EIC_EXTINT2 MCHP_PINMUX(d, 2, a, periph)

/* pd2e_ebi_d3 */
#define PD2E_EBI_D3 MCHP_PINMUX(d, 2, e, periph)

/* pd2f_tcc9_wo4 */
#define PD2F_TCC9_WO4 MCHP_PINMUX(d, 2, f, periph)

/* pd2j_spi_ixs0_fsync */
#define PD2J_SPI_IXS0_FSYNC MCHP_PINMUX(d, 2, j, periph)

/* pd2k_eth_gtxer */
#define PD2K_ETH_GTXER MCHP_PINMUX(d, 2, k, periph)

/* pd3_gpio */
#define PD3_GPIO MCHP_PINMUX(d, 3, gpio, gpio)

/* pd3a_eic_extint3 */
#define PD3A_EIC_EXTINT3 MCHP_PINMUX(d, 3, a, periph)

/* pd3d_sercom3_pad0 */
#define PD3D_SERCOM3_PAD0 MCHP_PINMUX(d, 3, d, periph)

/* pd3e_ebi_d5 */
#define PD3E_EBI_D5 MCHP_PINMUX(d, 3, e, periph)

/* pd3f_tcc9_wo3 */
#define PD3F_TCC9_WO3 MCHP_PINMUX(d, 3, f, periph)

/* pd3j_spi_ixs0_sdi */
#define PD3J_SPI_IXS0_SDI MCHP_PINMUX(d, 3, j, periph)

/* pd3k_eth_gtx3 */
#define PD3K_ETH_GTX3 MCHP_PINMUX(d, 3, k, periph)

/* pd4_gpio */
#define PD4_GPIO MCHP_PINMUX(d, 4, gpio, gpio)

/* pd4a_eic_extint4 */
#define PD4A_EIC_EXTINT4 MCHP_PINMUX(d, 4, a, periph)

/* pd4d_sercom3_pad1 */
#define PD4D_SERCOM3_PAD1 MCHP_PINMUX(d, 4, d, periph)

/* pd4e_ebi_d8 */
#define PD4E_EBI_D8 MCHP_PINMUX(d, 4, e, periph)

/* pd4f_tcc9_wo0 */
#define PD4F_TCC9_WO0 MCHP_PINMUX(d, 4, f, periph)

/* pd4j_spi_ixs0_sck */
#define PD4J_SPI_IXS0_SCK MCHP_PINMUX(d, 4, j, periph)

/* pd4k_eth_gtx2 */
#define PD4K_ETH_GTX2 MCHP_PINMUX(d, 4, k, periph)

/* pd5_gpio */
#define PD5_GPIO MCHP_PINMUX(d, 5, gpio, gpio)

/* pd5a_eic_extint5 */
#define PD5A_EIC_EXTINT5 MCHP_PINMUX(d, 5, a, periph)

/* pd5d_sercom3_pad2 */
#define PD5D_SERCOM3_PAD2 MCHP_PINMUX(d, 5, d, periph)

/* pd5e_ebi_d11 */
#define PD5E_EBI_D11 MCHP_PINMUX(d, 5, e, periph)

/* pd5f_tcc9_wo1 */
#define PD5F_TCC9_WO1 MCHP_PINMUX(d, 5, f, periph)

/* pd5j_spi_ixs0_sdo */
#define PD5J_SPI_IXS0_SDO MCHP_PINMUX(d, 5, j, periph)

/* pd5k_eth_txck */
#define PD5K_ETH_TXCK MCHP_PINMUX(d, 5, k, periph)

/* pd5l_eth_gtxck */
#define PD5L_ETH_GTXCK MCHP_PINMUX(d, 5, l, periph)

/* pd6_gpio */
#define PD6_GPIO MCHP_PINMUX(d, 6, gpio, gpio)

/* pd6a_eic_extint6 */
#define PD6A_EIC_EXTINT6 MCHP_PINMUX(d, 6, a, periph)

/* pd6d_sercom3_pad3 */
#define PD6D_SERCOM3_PAD3 MCHP_PINMUX(d, 6, d, periph)

/* pd6e_ebi_d12 */
#define PD6E_EBI_D12 MCHP_PINMUX(d, 6, e, periph)

/* pd6f_tcc9_wo2 */
#define PD6F_TCC9_WO2 MCHP_PINMUX(d, 6, f, periph)

/* pd6j_spi_ixs0_mclk0 */
#define PD6J_SPI_IXS0_MCLK0 MCHP_PINMUX(d, 6, j, periph)

/* pd6k_eth_grx3 */
#define PD6K_ETH_GRX3 MCHP_PINMUX(d, 6, k, periph)

/* pd7_gpio */
#define PD7_GPIO MCHP_PINMUX(d, 7, gpio, gpio)

/* pd7a_eic_extint7 */
#define PD7A_EIC_EXTINT7 MCHP_PINMUX(d, 7, a, periph)

/* pd7e_ebi_d15 */
#define PD7E_EBI_D15 MCHP_PINMUX(d, 7, e, periph)

/* pd7f_tcc7_wo1 */
#define PD7F_TCC7_WO1 MCHP_PINMUX(d, 7, f, periph)

/* pd7g_mlb_mlbc */
#define PD7G_MLB_MLBC MCHP_PINMUX(d, 7, g, periph)

/* pd7k_eth_grx2 */
#define PD7K_ETH_GRX2 MCHP_PINMUX(d, 7, k, periph)

/* pd8_gpio */
#define PD8_GPIO MCHP_PINMUX(d, 8, gpio, gpio)

/* pd8a_eic_extint8 */
#define PD8A_EIC_EXTINT8 MCHP_PINMUX(d, 8, a, periph)

/* pd8e_ebi_nwait */
#define PD8E_EBI_NWAIT MCHP_PINMUX(d, 8, e, periph)

/* pd8f_tcc7_wo0 */
#define PD8F_TCC7_WO0 MCHP_PINMUX(d, 8, f, periph)

/* pd8g_mlb_mlbs */
#define PD8G_MLB_MLBS MCHP_PINMUX(d, 8, g, periph)

/* pd8h_can1_rx */
#define PD8H_CAN1_RX MCHP_PINMUX(d, 8, h, periph)

/* pd8k_eth_gcol */
#define PD8K_ETH_GCOL MCHP_PINMUX(d, 8, k, periph)

/* pd9_gpio */
#define PD9_GPIO MCHP_PINMUX(d, 9, gpio, gpio)

/* pd9a_eic_extint9 */
#define PD9A_EIC_EXTINT9 MCHP_PINMUX(d, 9, a, periph)

/* pd9g_mlb_mlbd */
#define PD9G_MLB_MLBD MCHP_PINMUX(d, 9, g, periph)

/* pd9h_can1_tx */
#define PD9H_CAN1_TX MCHP_PINMUX(d, 9, h, periph)

/* pd9k_eth_gcrs */
#define PD9K_ETH_GCRS MCHP_PINMUX(d, 9, k, periph)

/* pd10_gpio */
#define PD10_GPIO MCHP_PINMUX(d, 10, gpio, gpio)

/* pd10a_eic_extint10 */
#define PD10A_EIC_EXTINT10 MCHP_PINMUX(d, 10, a, periph)

/* pd10f_tcc2_wo0 */
#define PD10F_TCC2_WO0 MCHP_PINMUX(d, 10, f, periph)

/* pd10k_eth_grx1 */
#define PD10K_ETH_GRX1 MCHP_PINMUX(d, 10, k, periph)

/* pd11_gpio */
#define PD11_GPIO MCHP_PINMUX(d, 11, gpio, gpio)

/* pd11a_eic_extint11 */
#define PD11A_EIC_EXTINT11 MCHP_PINMUX(d, 11, a, periph)

/* pd11d_sercom2_pad0 */
#define PD11D_SERCOM2_PAD0 MCHP_PINMUX(d, 11, d, periph)

/* pd11f_tcc2_wo1 */
#define PD11F_TCC2_WO1 MCHP_PINMUX(d, 11, f, periph)

/* pd11k_eth_grx0 */
#define PD11K_ETH_GRX0 MCHP_PINMUX(d, 11, k, periph)

/* pd12_gpio */
#define PD12_GPIO MCHP_PINMUX(d, 12, gpio, gpio)

/* pd12a_eic_extint12 */
#define PD12A_EIC_EXTINT12 MCHP_PINMUX(d, 12, a, periph)

/* pd12d_sercom2_pad1 */
#define PD12D_SERCOM2_PAD1 MCHP_PINMUX(d, 12, d, periph)

/* pd12f_tcc2_wo2 */
#define PD12F_TCC2_WO2 MCHP_PINMUX(d, 12, f, periph)

/* pd12k_eth_grefck */
#define PD12K_ETH_GREFCK MCHP_PINMUX(d, 12, k, periph)

/* pd12l_eth_grefck */
#define PD12L_ETH_GREFCK MCHP_PINMUX(d, 12, l, periph)

/* pd13_gpio */
#define PD13_GPIO MCHP_PINMUX(d, 13, gpio, gpio)

/* pd13a_eic_extint14 */
#define PD13A_EIC_EXTINT14 MCHP_PINMUX(d, 13, a, periph)

/* pd13e_ebi_d0 */
#define PD13E_EBI_D0 MCHP_PINMUX(d, 13, e, periph)

/* pd13f_tcc4_wo1 */
#define PD13F_TCC4_WO1 MCHP_PINMUX(d, 13, f, periph)

/* pd13h_can3_tx */
#define PD13H_CAN3_TX MCHP_PINMUX(d, 13, h, periph)

/* pd14_gpio */
#define PD14_GPIO MCHP_PINMUX(d, 14, gpio, gpio)

/* pd14a_eic_extint15 */
#define PD14A_EIC_EXTINT15 MCHP_PINMUX(d, 14, a, periph)

/* pd14d_sercom7_pad0 */
#define PD14D_SERCOM7_PAD0 MCHP_PINMUX(d, 14, d, periph)

/* pd14e_ebi_d2 */
#define PD14E_EBI_D2 MCHP_PINMUX(d, 14, e, periph)

/* pd14k_eth_gtx7 */
#define PD14K_ETH_GTX7 MCHP_PINMUX(d, 14, k, periph)

/* pd15_gpio */
#define PD15_GPIO MCHP_PINMUX(d, 15, gpio, gpio)

/* pd15a_eic_extint0 */
#define PD15A_EIC_EXTINT0 MCHP_PINMUX(d, 15, a, periph)

/* pd15d_sercom7_pad1 */
#define PD15D_SERCOM7_PAD1 MCHP_PINMUX(d, 15, d, periph)

/* pd15e_ebi_d4 */
#define PD15E_EBI_D4 MCHP_PINMUX(d, 15, e, periph)

/* pd15k_eth_gtx6 */
#define PD15K_ETH_GTX6 MCHP_PINMUX(d, 15, k, periph)

/* pd16_gpio */
#define PD16_GPIO MCHP_PINMUX(d, 16, gpio, gpio)

/* pd16a_eic_extint1 */
#define PD16A_EIC_EXTINT1 MCHP_PINMUX(d, 16, a, periph)

/* pd16d_sercom7_pad2 */
#define PD16D_SERCOM7_PAD2 MCHP_PINMUX(d, 16, d, periph)

/* pd16e_ebi_d6 */
#define PD16E_EBI_D6 MCHP_PINMUX(d, 16, e, periph)

/* pd16k_eth_gtx5 */
#define PD16K_ETH_GTX5 MCHP_PINMUX(d, 16, k, periph)

/* pd17_gpio */
#define PD17_GPIO MCHP_PINMUX(d, 17, gpio, gpio)

/* pd17a_eic_extint2 */
#define PD17A_EIC_EXTINT2 MCHP_PINMUX(d, 17, a, periph)

/* pd17d_sercom7_pad3 */
#define PD17D_SERCOM7_PAD3 MCHP_PINMUX(d, 17, d, periph)

/* pd17e_ebi_d7 */
#define PD17E_EBI_D7 MCHP_PINMUX(d, 17, e, periph)

/* pd17k_eth_gtx4 */
#define PD17K_ETH_GTX4 MCHP_PINMUX(d, 17, k, periph)

/* pd18_gpio */
#define PD18_GPIO MCHP_PINMUX(d, 18, gpio, gpio)

/* pd18a_eic_extint3 */
#define PD18A_EIC_EXTINT3 MCHP_PINMUX(d, 18, a, periph)

/* pd18e_ebi_d9 */
#define PD18E_EBI_D9 MCHP_PINMUX(d, 18, e, periph)

/* pd18k_eth_grx7 */
#define PD18K_ETH_GRX7 MCHP_PINMUX(d, 18, k, periph)

/* pd18m_gclk_io4 */
#define PD18M_GCLK_IO4 MCHP_PINMUX(d, 18, m, periph)

/* pd19_gpio */
#define PD19_GPIO MCHP_PINMUX(d, 19, gpio, gpio)

/* pd19a_eic_extint4 */
#define PD19A_EIC_EXTINT4 MCHP_PINMUX(d, 19, a, periph)

/* pd19e_ebi_d10 */
#define PD19E_EBI_D10 MCHP_PINMUX(d, 19, e, periph)

/* pd19k_eth_grx6 */
#define PD19K_ETH_GRX6 MCHP_PINMUX(d, 19, k, periph)

/* pd19m_gclk_io5 */
#define PD19M_GCLK_IO5 MCHP_PINMUX(d, 19, m, periph)

/* pd20_gpio */
#define PD20_GPIO MCHP_PINMUX(d, 20, gpio, gpio)

/* pd20a_eic_extint5 */
#define PD20A_EIC_EXTINT5 MCHP_PINMUX(d, 20, a, periph)

/* pd20e_ebi_d13 */
#define PD20E_EBI_D13 MCHP_PINMUX(d, 20, e, periph)

/* pd20k_eth_grx4 */
#define PD20K_ETH_GRX4 MCHP_PINMUX(d, 20, k, periph)

/* pd20m_gclk_io6 */
#define PD20M_GCLK_IO6 MCHP_PINMUX(d, 20, m, periph)

/* pd21_gpio */
#define PD21_GPIO MCHP_PINMUX(d, 21, gpio, gpio)

/* pd21a_eic_extint6 */
#define PD21A_EIC_EXTINT6 MCHP_PINMUX(d, 21, a, periph)

/* pd21e_ebi_d14 */
#define PD21E_EBI_D14 MCHP_PINMUX(d, 21, e, periph)

/* pd21k_eth_grx5 */
#define PD21K_ETH_GRX5 MCHP_PINMUX(d, 21, k, periph)

/* pd21m_gclk_io7 */
#define PD21M_GCLK_IO7 MCHP_PINMUX(d, 21, m, periph)

/* pd23_gpio */
#define PD23_GPIO MCHP_PINMUX(d, 23, gpio, gpio)

/* pd23a_eic_extint7 */
#define PD23A_EIC_EXTINT7 MCHP_PINMUX(d, 23, a, periph)

/* pd23e_ebi_d1 */
#define PD23E_EBI_D1 MCHP_PINMUX(d, 23, e, periph)

/* pd23f_tcc8_wo1 */
#define PD23F_TCC8_WO1 MCHP_PINMUX(d, 23, f, periph)

/* pd23h_can5_rx */
#define PD23H_CAN5_RX MCHP_PINMUX(d, 23, h, periph)

/* pe0_gpio */
#define PE0_GPIO MCHP_PINMUX(e, 0, gpio, gpio)

/* pe0a_eic_extint0 */
#define PE0A_EIC_EXTINT0 MCHP_PINMUX(e, 0, a, periph)

/* pe0j_spi_ixs1_sdo */
#define PE0J_SPI_IXS1_SDO MCHP_PINMUX(e, 0, j, periph)

/* pe1_gpio */
#define PE1_GPIO MCHP_PINMUX(e, 1, gpio, gpio)

/* pe1a_eic_extint1 */
#define PE1A_EIC_EXTINT1 MCHP_PINMUX(e, 1, a, periph)

/* pe1j_spi_ixs1_sck */
#define PE1J_SPI_IXS1_SCK MCHP_PINMUX(e, 1, j, periph)

/* pe2_gpio */
#define PE2_GPIO MCHP_PINMUX(e, 2, gpio, gpio)

/* pe2a_eic_extint2 */
#define PE2A_EIC_EXTINT2 MCHP_PINMUX(e, 2, a, periph)

/* pe2j_spi_ixs1_sdi */
#define PE2J_SPI_IXS1_SDI MCHP_PINMUX(e, 2, j, periph)

/* pe3_gpio */
#define PE3_GPIO MCHP_PINMUX(e, 3, gpio, gpio)

/* pe3a_eic_extint3 */
#define PE3A_EIC_EXTINT3 MCHP_PINMUX(e, 3, a, periph)

/* pe3b_adc0_ain9 */
#define PE3B_ADC0_AIN9 MCHP_PINMUX(e, 3, b, periph)

/* pf5_gpio */
#define PF5_GPIO MCHP_PINMUX(f, 5, gpio, gpio)

/* pf5a_eic_extint5 */
#define PF5A_EIC_EXTINT5 MCHP_PINMUX(f, 5, a, periph)

/* pf5p_ptc_drv21 */
#define PF5P_PTC_DRV21 MCHP_PINMUX(f, 5, p, periph)

/* pg0_gpio */
#define PG0_GPIO MCHP_PINMUX(g, 0, gpio, gpio)

/* pg0a_eic_extint0 */
#define PG0A_EIC_EXTINT0 MCHP_PINMUX(g, 0, a, periph)

/* pg0d_sercom6_pad2 */
#define PG0D_SERCOM6_PAD2 MCHP_PINMUX(g, 0, d, periph)

/* pg0e_ebi_a17 */
#define PG0E_EBI_A17 MCHP_PINMUX(g, 0, e, periph)

/* pg0h_sqi1_data1 */
#define PG0H_SQI1_DATA1 MCHP_PINMUX(g, 0, h, periph)

/* pg0i_sdmmc1_sddat1 */
#define PG0I_SDMMC1_SDDAT1 MCHP_PINMUX(g, 0, i, periph)

/* pg1_gpio */
#define PG1_GPIO MCHP_PINMUX(g, 1, gpio, gpio)

/* pg1a_eic_extint1 */
#define PG1A_EIC_EXTINT1 MCHP_PINMUX(g, 1, a, periph)

/* pg1d_sercom6_pad3 */
#define PG1D_SERCOM6_PAD3 MCHP_PINMUX(g, 1, d, periph)

/* pg1e_ebi_a16 */
#define PG1E_EBI_A16 MCHP_PINMUX(g, 1, e, periph)

/* pg1h_sqi1_data2 */
#define PG1H_SQI1_DATA2 MCHP_PINMUX(g, 1, h, periph)

/* pg1i_sdmmc1_sddat2 */
#define PG1I_SDMMC1_SDDAT2 MCHP_PINMUX(g, 1, i, periph)

/* pg2_gpio */
#define PG2_GPIO MCHP_PINMUX(g, 2, gpio, gpio)

/* pg2a_eic_extint2 */
#define PG2A_EIC_EXTINT2 MCHP_PINMUX(g, 2, a, periph)

/* pg2e_ebi_a15 */
#define PG2E_EBI_A15 MCHP_PINMUX(g, 2, e, periph)

/* pg2h_sqi1_data3 */
#define PG2H_SQI1_DATA3 MCHP_PINMUX(g, 2, h, periph)

/* pg2i_sdmmc1_sddat3 */
#define PG2I_SDMMC1_SDDAT3 MCHP_PINMUX(g, 2, i, periph)

/* pg3_gpio */
#define PG3_GPIO MCHP_PINMUX(g, 3, gpio, gpio)

/* pg3a_eic_extint3 */
#define PG3A_EIC_EXTINT3 MCHP_PINMUX(g, 3, a, periph)

/* pg3e_ebi_a11 */
#define PG3E_EBI_A11 MCHP_PINMUX(g, 3, e, periph)

/* pg3h_sqi1_cs0 */
#define PG3H_SQI1_CS0 MCHP_PINMUX(g, 3, h, periph)

/* pg3i_sdmmc1_sdcmd */
#define PG3I_SDMMC1_SDCMD MCHP_PINMUX(g, 3, i, periph)

#endif /* MICROCHIP_PIC32CZ8110CA90176_PINCTRL_H_ */
