/*
 * Copyright (c) 2025 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CM2532JH01048_PINCTRL_H_
#define MICROCHIP_PIC32CM2532JH01048_PINCTRL_H_

#include <dt-bindings/pic32c/pic32cm_jh/common/mchp_pinctrl_pinmux_pic32c.h>

/* pa0_gpio */
#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

/* pa0a_eic_extint0 */
#define PA0A_EIC_EXTINT0 MCHP_PINMUX(a, 0, a, periph)

/* pa0a_rstc_extwake0 */
#define PA0A_RSTC_EXTWAKE0 MCHP_PINMUX(a, 0, a, periph)

/* pa0d_sercom1_pad0 */
#define PA0D_SERCOM1_PAD0 MCHP_PINMUX(a, 0, d, periph)

/* pa0e_tcc2_wo0 */
#define PA0E_TCC2_WO0 MCHP_PINMUX(a, 0, e, periph)

/* pa0f_tc7_wo0 */
#define PA0F_TC7_WO0 MCHP_PINMUX(a, 0, f, periph)

/* pa0h_ac_cmp2 */
#define PA0H_AC_CMP2 MCHP_PINMUX(a, 0, h, periph)

/* pa1_gpio */
#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

/* pa1a_eic_extint1 */
#define PA1A_EIC_EXTINT1 MCHP_PINMUX(a, 1, a, periph)

/* pa1a_rstc_extwake1 */
#define PA1A_RSTC_EXTWAKE1 MCHP_PINMUX(a, 1, a, periph)

/* pa1d_sercom1_pad1 */
#define PA1D_SERCOM1_PAD1 MCHP_PINMUX(a, 1, d, periph)

/* pa1e_tcc2_wo1 */
#define PA1E_TCC2_WO1 MCHP_PINMUX(a, 1, e, periph)

/* pa1f_tc7_wo1 */
#define PA1F_TC7_WO1 MCHP_PINMUX(a, 1, f, periph)

/* pa1h_ac_cmp3 */
#define PA1H_AC_CMP3 MCHP_PINMUX(a, 1, h, periph)

/* pa2_gpio */
#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

/* pa2a_eic_extint2 */
#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

/* pa2a_rstc_extwake2 */
#define PA2A_RSTC_EXTWAKE2 MCHP_PINMUX(a, 2, a, periph)

/* pa2b_ac_ain4 */
#define PA2B_AC_AIN4 MCHP_PINMUX(a, 2, b, periph)

/* pa2b_adc0_ain0 */
#define PA2B_ADC0_AIN0 MCHP_PINMUX(a, 2, b, periph)

/* pa2b_dac_vout */
#define PA2B_DAC_VOUT MCHP_PINMUX(a, 2, b, periph)

/* pa2b_ptc_y0 */
#define PA2B_PTC_Y0 MCHP_PINMUX(a, 2, b, periph)

/* pa2k_ptc_ds0 */
#define PA2K_PTC_DS0 MCHP_PINMUX(a, 2, k, periph)

/* pa3_gpio */
#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

/* pa3a_eic_extint3 */
#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

/* pa3a_rstc_extwake3 */
#define PA3A_RSTC_EXTWAKE3 MCHP_PINMUX(a, 3, a, periph)

/* pa3b_ac_ain5 */
#define PA3B_AC_AIN5 MCHP_PINMUX(a, 3, b, periph)

/* pa3b_adc0_ain1 */
#define PA3B_ADC0_AIN1 MCHP_PINMUX(a, 3, b, periph)

/* pa3b_adc0_vrefp */
#define PA3B_ADC0_VREFP MCHP_PINMUX(a, 3, b, periph)

/* pa3b_dac_vrefp */
#define PA3B_DAC_VREFP MCHP_PINMUX(a, 3, b, periph)

/* pa3b_ptc_y1 */
#define PA3B_PTC_Y1 MCHP_PINMUX(a, 3, b, periph)

/* pa3k_ptc_ds1 */
#define PA3K_PTC_DS1 MCHP_PINMUX(a, 3, k, periph)

/* pa4_gpio */
#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

/* pa4a_eic_extint4 */
#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

/* pa4a_rstc_extwake4 */
#define PA4A_RSTC_EXTWAKE4 MCHP_PINMUX(a, 4, a, periph)

/* pa4b_ac_ain0 */
#define PA4B_AC_AIN0 MCHP_PINMUX(a, 4, b, periph)

/* pa4b_adc0_ain4 */
#define PA4B_ADC0_AIN4 MCHP_PINMUX(a, 4, b, periph)

/* pa4b_ptc_y2 */
#define PA4B_PTC_Y2 MCHP_PINMUX(a, 4, b, periph)

/* pa4d_sercom0_pad0 */
#define PA4D_SERCOM0_PAD0 MCHP_PINMUX(a, 4, d, periph)

/* pa4e_tcc0_wo0 */
#define PA4E_TCC0_WO0 MCHP_PINMUX(a, 4, e, periph)

/* pa4f_tc5_wo0 */
#define PA4F_TC5_WO0 MCHP_PINMUX(a, 4, f, periph)

/* pa4i_ccl_in0 */
#define PA4I_CCL_IN0 MCHP_PINMUX(a, 4, i, periph)

/* pa4k_ptc_ds2 */
#define PA4K_PTC_DS2 MCHP_PINMUX(a, 4, k, periph)

/* pa5_gpio */
#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

/* pa5a_eic_extint5 */
#define PA5A_EIC_EXTINT5 MCHP_PINMUX(a, 5, a, periph)

/* pa5a_rstc_extwake5 */
#define PA5A_RSTC_EXTWAKE5 MCHP_PINMUX(a, 5, a, periph)

/* pa5b_ac_ain1 */
#define PA5B_AC_AIN1 MCHP_PINMUX(a, 5, b, periph)

/* pa5b_adc0_ain5 */
#define PA5B_ADC0_AIN5 MCHP_PINMUX(a, 5, b, periph)

/* pa5b_ptc_y3 */
#define PA5B_PTC_Y3 MCHP_PINMUX(a, 5, b, periph)

/* pa5d_sercom0_pad1 */
#define PA5D_SERCOM0_PAD1 MCHP_PINMUX(a, 5, d, periph)

/* pa5e_tcc0_wo1 */
#define PA5E_TCC0_WO1 MCHP_PINMUX(a, 5, e, periph)

/* pa5f_tc5_wo1 */
#define PA5F_TC5_WO1 MCHP_PINMUX(a, 5, f, periph)

/* pa5i_ccl_in1 */
#define PA5I_CCL_IN1 MCHP_PINMUX(a, 5, i, periph)

/* pa5k_ptc_ds3 */
#define PA5K_PTC_DS3 MCHP_PINMUX(a, 5, k, periph)

/* pa6_gpio */
#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

/* pa6a_eic_extint6 */
#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

/* pa6a_rstc_extwake6 */
#define PA6A_RSTC_EXTWAKE6 MCHP_PINMUX(a, 6, a, periph)

/* pa6b_ac_ain2 */
#define PA6B_AC_AIN2 MCHP_PINMUX(a, 6, b, periph)

/* pa6b_adc0_ain6 */
#define PA6B_ADC0_AIN6 MCHP_PINMUX(a, 6, b, periph)

/* pa6b_ptc_y4 */
#define PA6B_PTC_Y4 MCHP_PINMUX(a, 6, b, periph)

/* pa6d_sercom0_pad2 */
#define PA6D_SERCOM0_PAD2 MCHP_PINMUX(a, 6, d, periph)

/* pa6e_tcc1_wo0 */
#define PA6E_TCC1_WO0 MCHP_PINMUX(a, 6, e, periph)

/* pa6f_tc6_wo0 */
#define PA6F_TC6_WO0 MCHP_PINMUX(a, 6, f, periph)

/* pa6i_ccl_in2 */
#define PA6I_CCL_IN2 MCHP_PINMUX(a, 6, i, periph)

/* pa6k_ptc_ds4 */
#define PA6K_PTC_DS4 MCHP_PINMUX(a, 6, k, periph)

/* pa7_gpio */
#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

/* pa7a_eic_extint7 */
#define PA7A_EIC_EXTINT7 MCHP_PINMUX(a, 7, a, periph)

/* pa7a_rstc_extwake7 */
#define PA7A_RSTC_EXTWAKE7 MCHP_PINMUX(a, 7, a, periph)

/* pa7b_ac_ain3 */
#define PA7B_AC_AIN3 MCHP_PINMUX(a, 7, b, periph)

/* pa7b_adc0_ain7 */
#define PA7B_ADC0_AIN7 MCHP_PINMUX(a, 7, b, periph)

/* pa7b_ptc_y5 */
#define PA7B_PTC_Y5 MCHP_PINMUX(a, 7, b, periph)

/* pa7d_sercom0_pad3 */
#define PA7D_SERCOM0_PAD3 MCHP_PINMUX(a, 7, d, periph)

/* pa7e_tcc1_wo1 */
#define PA7E_TCC1_WO1 MCHP_PINMUX(a, 7, e, periph)

/* pa7f_tc6_wo1 */
#define PA7F_TC6_WO1 MCHP_PINMUX(a, 7, f, periph)

/* pa7i_ccl_out0 */
#define PA7I_CCL_OUT0 MCHP_PINMUX(a, 7, i, periph)

/* pa7k_ptc_ds5 */
#define PA7K_PTC_DS5 MCHP_PINMUX(a, 7, k, periph)

/* pa8_gpio */
#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

/* pa8a_eic_nmi */
#define PA8A_EIC_NMI MCHP_PINMUX(a, 8, a, periph)

/* pa8a_rstc_extwake8 */
#define PA8A_RSTC_EXTWAKE8 MCHP_PINMUX(a, 8, a, periph)

/* pa8b_adc0_ain8 */
#define PA8B_ADC0_AIN8 MCHP_PINMUX(a, 8, b, periph)

/* pa8b_adc1_ain10 */
#define PA8B_ADC1_AIN10 MCHP_PINMUX(a, 8, b, periph)

/* pa8b_ptc_x0 */
#define PA8B_PTC_X0 MCHP_PINMUX(a, 8, b, periph)

/* pa8b_ptc_y16 */
#define PA8B_PTC_Y16 MCHP_PINMUX(a, 8, b, periph)

/* pa8c_sercom0_pad0 */
#define PA8C_SERCOM0_PAD0 MCHP_PINMUX(a, 8, c, periph)

/* pa8d_sercom2_pad0 */
#define PA8D_SERCOM2_PAD0 MCHP_PINMUX(a, 8, d, periph)

/* pa8e_tcc0_wo0 */
#define PA8E_TCC0_WO0 MCHP_PINMUX(a, 8, e, periph)

/* pa8f_tcc1_wo2 */
#define PA8F_TCC1_WO2 MCHP_PINMUX(a, 8, f, periph)

/* pa8i_ccl_in3 */
#define PA8I_CCL_IN3 MCHP_PINMUX(a, 8, i, periph)

/* pa8j_pdec_qdi0 */
#define PA8J_PDEC_QDI0 MCHP_PINMUX(a, 8, j, periph)

/* pa8k_ptc_ds16 */
#define PA8K_PTC_DS16 MCHP_PINMUX(a, 8, k, periph)

/* pa9_gpio */
#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

/* pa9a_eic_extint9 */
#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

/* pa9a_rstc_extwake9 */
#define PA9A_RSTC_EXTWAKE9 MCHP_PINMUX(a, 9, a, periph)

/* pa9b_adc0_ain9 */
#define PA9B_ADC0_AIN9 MCHP_PINMUX(a, 9, b, periph)

/* pa9b_adc1_ain11 */
#define PA9B_ADC1_AIN11 MCHP_PINMUX(a, 9, b, periph)

/* pa9b_ptc_x1 */
#define PA9B_PTC_X1 MCHP_PINMUX(a, 9, b, periph)

/* pa9b_ptc_y17 */
#define PA9B_PTC_Y17 MCHP_PINMUX(a, 9, b, periph)

/* pa9c_sercom0_pad1 */
#define PA9C_SERCOM0_PAD1 MCHP_PINMUX(a, 9, c, periph)

/* pa9d_sercom2_pad1 */
#define PA9D_SERCOM2_PAD1 MCHP_PINMUX(a, 9, d, periph)

/* pa9e_tcc0_wo1 */
#define PA9E_TCC0_WO1 MCHP_PINMUX(a, 9, e, periph)

/* pa9f_tcc1_wo3 */
#define PA9F_TCC1_WO3 MCHP_PINMUX(a, 9, f, periph)

/* pa9i_ccl_in4 */
#define PA9I_CCL_IN4 MCHP_PINMUX(a, 9, i, periph)

/* pa9j_pdec_qdi1 */
#define PA9J_PDEC_QDI1 MCHP_PINMUX(a, 9, j, periph)

/* pa9k_ptc_ds17 */
#define PA9K_PTC_DS17 MCHP_PINMUX(a, 9, k, periph)

/* pa10_gpio */
#define PA10_GPIO MCHP_PINMUX(a, 10, gpio, gpio)

/* pa10a_eic_extint10 */
#define PA10A_EIC_EXTINT10 MCHP_PINMUX(a, 10, a, periph)

/* pa10a_rstc_extwake10 */
#define PA10A_RSTC_EXTWAKE10 MCHP_PINMUX(a, 10, a, periph)

/* pa10b_adc0_ain10 */
#define PA10B_ADC0_AIN10 MCHP_PINMUX(a, 10, b, periph)

/* pa10b_ptc_x2 */
#define PA10B_PTC_X2 MCHP_PINMUX(a, 10, b, periph)

/* pa10b_ptc_y18 */
#define PA10B_PTC_Y18 MCHP_PINMUX(a, 10, b, periph)

/* pa10c_sercom0_pad2 */
#define PA10C_SERCOM0_PAD2 MCHP_PINMUX(a, 10, c, periph)

/* pa10d_sercom2_pad2 */
#define PA10D_SERCOM2_PAD2 MCHP_PINMUX(a, 10, d, periph)

/* pa10e_tcc1_wo0 */
#define PA10E_TCC1_WO0 MCHP_PINMUX(a, 10, e, periph)

/* pa10f_tcc0_wo2 */
#define PA10F_TCC0_WO2 MCHP_PINMUX(a, 10, f, periph)

/* pa10h_gclk_io4 */
#define PA10H_GCLK_IO4 MCHP_PINMUX(a, 10, h, periph)

/* pa10i_ccl_in5 */
#define PA10I_CCL_IN5 MCHP_PINMUX(a, 10, i, periph)

/* pa10j_pdec_qdi2 */
#define PA10J_PDEC_QDI2 MCHP_PINMUX(a, 10, j, periph)

/* pa10k_ptc_ds18 */
#define PA10K_PTC_DS18 MCHP_PINMUX(a, 10, k, periph)

/* pa11_gpio */
#define PA11_GPIO MCHP_PINMUX(a, 11, gpio, gpio)

/* pa11a_eic_extint11 */
#define PA11A_EIC_EXTINT11 MCHP_PINMUX(a, 11, a, periph)

/* pa11a_rstc_extwake11 */
#define PA11A_RSTC_EXTWAKE11 MCHP_PINMUX(a, 11, a, periph)

/* pa11b_adc0_ain11 */
#define PA11B_ADC0_AIN11 MCHP_PINMUX(a, 11, b, periph)

/* pa11b_ptc_x3 */
#define PA11B_PTC_X3 MCHP_PINMUX(a, 11, b, periph)

/* pa11b_ptc_y19 */
#define PA11B_PTC_Y19 MCHP_PINMUX(a, 11, b, periph)

/* pa11c_sercom0_pad3 */
#define PA11C_SERCOM0_PAD3 MCHP_PINMUX(a, 11, c, periph)

/* pa11d_sercom2_pad3 */
#define PA11D_SERCOM2_PAD3 MCHP_PINMUX(a, 11, d, periph)

/* pa11e_tcc1_wo1 */
#define PA11E_TCC1_WO1 MCHP_PINMUX(a, 11, e, periph)

/* pa11f_tcc0_wo3 */
#define PA11F_TCC0_WO3 MCHP_PINMUX(a, 11, f, periph)

/* pa11h_gclk_io5 */
#define PA11H_GCLK_IO5 MCHP_PINMUX(a, 11, h, periph)

/* pa11i_ccl_out1 */
#define PA11I_CCL_OUT1 MCHP_PINMUX(a, 11, i, periph)

/* pa11k_ptc_ds19 */
#define PA11K_PTC_DS19 MCHP_PINMUX(a, 11, k, periph)

/* pa12_gpio */
#define PA12_GPIO MCHP_PINMUX(a, 12, gpio, gpio)

/* pa12a_eic_extint12 */
#define PA12A_EIC_EXTINT12 MCHP_PINMUX(a, 12, a, periph)

/* pa12a_rstc_extwake12 */
#define PA12A_RSTC_EXTWAKE12 MCHP_PINMUX(a, 12, a, periph)

/* pa12c_sercom2_pad0 */
#define PA12C_SERCOM2_PAD0 MCHP_PINMUX(a, 12, c, periph)

/* pa12d_sercom4_pad0 */
#define PA12D_SERCOM4_PAD0 MCHP_PINMUX(a, 12, d, periph)

/* pa12e_tcc2_wo0 */
#define PA12E_TCC2_WO0 MCHP_PINMUX(a, 12, e, periph)

/* pa12f_tcc0_wo6 */
#define PA12F_TCC0_WO6 MCHP_PINMUX(a, 12, f, periph)

/* pa12h_ac_cmp0 */
#define PA12H_AC_CMP0 MCHP_PINMUX(a, 12, h, periph)

/* pa13_gpio */
#define PA13_GPIO MCHP_PINMUX(a, 13, gpio, gpio)

/* pa13a_eic_extint13 */
#define PA13A_EIC_EXTINT13 MCHP_PINMUX(a, 13, a, periph)

/* pa13a_rstc_extwake13 */
#define PA13A_RSTC_EXTWAKE13 MCHP_PINMUX(a, 13, a, periph)

/* pa13c_sercom2_pad1 */
#define PA13C_SERCOM2_PAD1 MCHP_PINMUX(a, 13, c, periph)

/* pa13d_sercom4_pad1 */
#define PA13D_SERCOM4_PAD1 MCHP_PINMUX(a, 13, d, periph)

/* pa13e_tcc2_wo1 */
#define PA13E_TCC2_WO1 MCHP_PINMUX(a, 13, e, periph)

/* pa13f_tcc0_wo7 */
#define PA13F_TCC0_WO7 MCHP_PINMUX(a, 13, f, periph)

/* pa13h_ac_cmp1 */
#define PA13H_AC_CMP1 MCHP_PINMUX(a, 13, h, periph)

/* pa14_gpio */
#define PA14_GPIO MCHP_PINMUX(a, 14, gpio, gpio)

/* pa14a_eic_extint14 */
#define PA14A_EIC_EXTINT14 MCHP_PINMUX(a, 14, a, periph)

/* pa14a_rstc_extwake14 */
#define PA14A_RSTC_EXTWAKE14 MCHP_PINMUX(a, 14, a, periph)

/* pa14c_sercom2_pad2 */
#define PA14C_SERCOM2_PAD2 MCHP_PINMUX(a, 14, c, periph)

/* pa14d_sercom4_pad2 */
#define PA14D_SERCOM4_PAD2 MCHP_PINMUX(a, 14, d, periph)

/* pa14e_tc4_wo0 */
#define PA14E_TC4_WO0 MCHP_PINMUX(a, 14, e, periph)

/* pa14f_tcc0_wo4 */
#define PA14F_TCC0_WO4 MCHP_PINMUX(a, 14, f, periph)

/* pa14h_gclk_io0 */
#define PA14H_GCLK_IO0 MCHP_PINMUX(a, 14, h, periph)

/* pa15_gpio */
#define PA15_GPIO MCHP_PINMUX(a, 15, gpio, gpio)

/* pa15a_eic_extint15 */
#define PA15A_EIC_EXTINT15 MCHP_PINMUX(a, 15, a, periph)

/* pa15a_rstc_extwake15 */
#define PA15A_RSTC_EXTWAKE15 MCHP_PINMUX(a, 15, a, periph)

/* pa15c_sercom2_pad3 */
#define PA15C_SERCOM2_PAD3 MCHP_PINMUX(a, 15, c, periph)

/* pa15d_sercom4_pad3 */
#define PA15D_SERCOM4_PAD3 MCHP_PINMUX(a, 15, d, periph)

/* pa15e_tc4_wo1 */
#define PA15E_TC4_WO1 MCHP_PINMUX(a, 15, e, periph)

/* pa15f_tcc0_wo5 */
#define PA15F_TCC0_WO5 MCHP_PINMUX(a, 15, f, periph)

/* pa15h_gclk_io1 */
#define PA15H_GCLK_IO1 MCHP_PINMUX(a, 15, h, periph)

/* pa16_gpio */
#define PA16_GPIO MCHP_PINMUX(a, 16, gpio, gpio)

/* pa16a_eic_extint0 */
#define PA16A_EIC_EXTINT0 MCHP_PINMUX(a, 16, a, periph)

/* pa16b_ptc_x4 */
#define PA16B_PTC_X4 MCHP_PINMUX(a, 16, b, periph)

/* pa16b_ptc_y20 */
#define PA16B_PTC_Y20 MCHP_PINMUX(a, 16, b, periph)

/* pa16c_sercom1_pad0 */
#define PA16C_SERCOM1_PAD0 MCHP_PINMUX(a, 16, c, periph)

/* pa16d_sercom3_pad0 */
#define PA16D_SERCOM3_PAD0 MCHP_PINMUX(a, 16, d, periph)

/* pa16e_tcc2_wo0 */
#define PA16E_TCC2_WO0 MCHP_PINMUX(a, 16, e, periph)

/* pa16f_tcc0_wo6 */
#define PA16F_TCC0_WO6 MCHP_PINMUX(a, 16, f, periph)

/* pa16g_pdec_qdi0 */
#define PA16G_PDEC_QDI0 MCHP_PINMUX(a, 16, g, periph)

/* pa16h_gclk_io2 */
#define PA16H_GCLK_IO2 MCHP_PINMUX(a, 16, h, periph)

/* pa16i_ccl_in0 */
#define PA16I_CCL_IN0 MCHP_PINMUX(a, 16, i, periph)

/* pa16k_ptc_ds20 */
#define PA16K_PTC_DS20 MCHP_PINMUX(a, 16, k, periph)

/* pa17_gpio */
#define PA17_GPIO MCHP_PINMUX(a, 17, gpio, gpio)

/* pa17a_eic_extint1 */
#define PA17A_EIC_EXTINT1 MCHP_PINMUX(a, 17, a, periph)

/* pa17b_ptc_x5 */
#define PA17B_PTC_X5 MCHP_PINMUX(a, 17, b, periph)

/* pa17b_ptc_y21 */
#define PA17B_PTC_Y21 MCHP_PINMUX(a, 17, b, periph)

/* pa17c_sercom1_pad1 */
#define PA17C_SERCOM1_PAD1 MCHP_PINMUX(a, 17, c, periph)

/* pa17d_sercom3_pad1 */
#define PA17D_SERCOM3_PAD1 MCHP_PINMUX(a, 17, d, periph)

/* pa17e_tcc2_wo1 */
#define PA17E_TCC2_WO1 MCHP_PINMUX(a, 17, e, periph)

/* pa17f_tcc0_wo7 */
#define PA17F_TCC0_WO7 MCHP_PINMUX(a, 17, f, periph)

/* pa17g_pdec_qdi1 */
#define PA17G_PDEC_QDI1 MCHP_PINMUX(a, 17, g, periph)

/* pa17h_gclk_io3 */
#define PA17H_GCLK_IO3 MCHP_PINMUX(a, 17, h, periph)

/* pa17i_ccl_in1 */
#define PA17I_CCL_IN1 MCHP_PINMUX(a, 17, i, periph)

/* pa17k_ptc_ds21 */
#define PA17K_PTC_DS21 MCHP_PINMUX(a, 17, k, periph)

/* pa18_gpio */
#define PA18_GPIO MCHP_PINMUX(a, 18, gpio, gpio)

/* pa18a_eic_extint2 */
#define PA18A_EIC_EXTINT2 MCHP_PINMUX(a, 18, a, periph)

/* pa18b_ptc_x6 */
#define PA18B_PTC_X6 MCHP_PINMUX(a, 18, b, periph)

/* pa18b_ptc_y22 */
#define PA18B_PTC_Y22 MCHP_PINMUX(a, 18, b, periph)

/* pa18c_sercom1_pad2 */
#define PA18C_SERCOM1_PAD2 MCHP_PINMUX(a, 18, c, periph)

/* pa18d_sercom3_pad2 */
#define PA18D_SERCOM3_PAD2 MCHP_PINMUX(a, 18, d, periph)

/* pa18e_tc4_wo0 */
#define PA18E_TC4_WO0 MCHP_PINMUX(a, 18, e, periph)

/* pa18f_tcc0_wo2 */
#define PA18F_TCC0_WO2 MCHP_PINMUX(a, 18, f, periph)

/* pa18g_pdec_qdi2 */
#define PA18G_PDEC_QDI2 MCHP_PINMUX(a, 18, g, periph)

/* pa18h_ac_cmp0 */
#define PA18H_AC_CMP0 MCHP_PINMUX(a, 18, h, periph)

/* pa18i_ccl_in2 */
#define PA18I_CCL_IN2 MCHP_PINMUX(a, 18, i, periph)

/* pa18k_ptc_ds22 */
#define PA18K_PTC_DS22 MCHP_PINMUX(a, 18, k, periph)

/* pa19_gpio */
#define PA19_GPIO MCHP_PINMUX(a, 19, gpio, gpio)

/* pa19a_eic_extint3 */
#define PA19A_EIC_EXTINT3 MCHP_PINMUX(a, 19, a, periph)

/* pa19b_ptc_x7 */
#define PA19B_PTC_X7 MCHP_PINMUX(a, 19, b, periph)

/* pa19b_ptc_y23 */
#define PA19B_PTC_Y23 MCHP_PINMUX(a, 19, b, periph)

/* pa19c_sercom1_pad3 */
#define PA19C_SERCOM1_PAD3 MCHP_PINMUX(a, 19, c, periph)

/* pa19d_sercom3_pad3 */
#define PA19D_SERCOM3_PAD3 MCHP_PINMUX(a, 19, d, periph)

/* pa19e_tc4_wo1 */
#define PA19E_TC4_WO1 MCHP_PINMUX(a, 19, e, periph)

/* pa19f_tcc0_wo3 */
#define PA19F_TCC0_WO3 MCHP_PINMUX(a, 19, f, periph)

/* pa19h_ac_cmp1 */
#define PA19H_AC_CMP1 MCHP_PINMUX(a, 19, h, periph)

/* pa19i_ccl_out0 */
#define PA19I_CCL_OUT0 MCHP_PINMUX(a, 19, i, periph)

/* pa19k_ptc_ds23 */
#define PA19K_PTC_DS23 MCHP_PINMUX(a, 19, k, periph)

/* pa20_gpio */
#define PA20_GPIO MCHP_PINMUX(a, 20, gpio, gpio)

/* pa20a_eic_extint4 */
#define PA20A_EIC_EXTINT4 MCHP_PINMUX(a, 20, a, periph)

/* pa20b_ptc_x8 */
#define PA20B_PTC_X8 MCHP_PINMUX(a, 20, b, periph)

/* pa20b_ptc_y24 */
#define PA20B_PTC_Y24 MCHP_PINMUX(a, 20, b, periph)

/* pa20c_sercom5_pad2 */
#define PA20C_SERCOM5_PAD2 MCHP_PINMUX(a, 20, c, periph)

/* pa20d_sercom3_pad2 */
#define PA20D_SERCOM3_PAD2 MCHP_PINMUX(a, 20, d, periph)

/* pa20e_tc3_wo0 */
#define PA20E_TC3_WO0 MCHP_PINMUX(a, 20, e, periph)

/* pa20f_tcc0_wo6 */
#define PA20F_TCC0_WO6 MCHP_PINMUX(a, 20, f, periph)

/* pa20h_gclk_io4 */
#define PA20H_GCLK_IO4 MCHP_PINMUX(a, 20, h, periph)

/* pa20k_ptc_ds24 */
#define PA20K_PTC_DS24 MCHP_PINMUX(a, 20, k, periph)

/* pa21_gpio */
#define PA21_GPIO MCHP_PINMUX(a, 21, gpio, gpio)

/* pa21a_eic_extint5 */
#define PA21A_EIC_EXTINT5 MCHP_PINMUX(a, 21, a, periph)

/* pa21b_ptc_x9 */
#define PA21B_PTC_X9 MCHP_PINMUX(a, 21, b, periph)

/* pa21b_ptc_y25 */
#define PA21B_PTC_Y25 MCHP_PINMUX(a, 21, b, periph)

/* pa21c_sercom5_pad3 */
#define PA21C_SERCOM5_PAD3 MCHP_PINMUX(a, 21, c, periph)

/* pa21d_sercom3_pad3 */
#define PA21D_SERCOM3_PAD3 MCHP_PINMUX(a, 21, d, periph)

/* pa21e_tc3_wo1 */
#define PA21E_TC3_WO1 MCHP_PINMUX(a, 21, e, periph)

/* pa21f_tcc0_wo7 */
#define PA21F_TCC0_WO7 MCHP_PINMUX(a, 21, f, periph)

/* pa21h_gclk_io5 */
#define PA21H_GCLK_IO5 MCHP_PINMUX(a, 21, h, periph)

/* pa21k_ptc_ds25 */
#define PA21K_PTC_DS25 MCHP_PINMUX(a, 21, k, periph)

/* pa22_gpio */
#define PA22_GPIO MCHP_PINMUX(a, 22, gpio, gpio)

/* pa22a_eic_extint6 */
#define PA22A_EIC_EXTINT6 MCHP_PINMUX(a, 22, a, periph)

/* pa22b_ptc_x10 */
#define PA22B_PTC_X10 MCHP_PINMUX(a, 22, b, periph)

/* pa22b_ptc_y26 */
#define PA22B_PTC_Y26 MCHP_PINMUX(a, 22, b, periph)

/* pa22c_sercom3_pad0 */
#define PA22C_SERCOM3_PAD0 MCHP_PINMUX(a, 22, c, periph)

/* pa22d_sercom5_pad0 */
#define PA22D_SERCOM5_PAD0 MCHP_PINMUX(a, 22, d, periph)

/* pa22e_tc0_wo0 */
#define PA22E_TC0_WO0 MCHP_PINMUX(a, 22, e, periph)

/* pa22f_tcc0_wo4 */
#define PA22F_TCC0_WO4 MCHP_PINMUX(a, 22, f, periph)

/* pa22h_gclk_io6 */
#define PA22H_GCLK_IO6 MCHP_PINMUX(a, 22, h, periph)

/* pa22i_ccl_in6 */
#define PA22I_CCL_IN6 MCHP_PINMUX(a, 22, i, periph)

/* pa22k_ptc_ds26 */
#define PA22K_PTC_DS26 MCHP_PINMUX(a, 22, k, periph)

/* pa23_gpio */
#define PA23_GPIO MCHP_PINMUX(a, 23, gpio, gpio)

/* pa23a_eic_extint7 */
#define PA23A_EIC_EXTINT7 MCHP_PINMUX(a, 23, a, periph)

/* pa23b_ptc_x11 */
#define PA23B_PTC_X11 MCHP_PINMUX(a, 23, b, periph)

/* pa23b_ptc_y27 */
#define PA23B_PTC_Y27 MCHP_PINMUX(a, 23, b, periph)

/* pa23c_sercom3_pad1 */
#define PA23C_SERCOM3_PAD1 MCHP_PINMUX(a, 23, c, periph)

/* pa23d_sercom5_pad1 */
#define PA23D_SERCOM5_PAD1 MCHP_PINMUX(a, 23, d, periph)

/* pa23e_tc0_wo1 */
#define PA23E_TC0_WO1 MCHP_PINMUX(a, 23, e, periph)

/* pa23f_tcc0_wo5 */
#define PA23F_TCC0_WO5 MCHP_PINMUX(a, 23, f, periph)

/* pa23h_gclk_io7 */
#define PA23H_GCLK_IO7 MCHP_PINMUX(a, 23, h, periph)

/* pa23i_ccl_in7 */
#define PA23I_CCL_IN7 MCHP_PINMUX(a, 23, i, periph)

/* pa23k_ptc_ds27 */
#define PA23K_PTC_DS27 MCHP_PINMUX(a, 23, k, periph)

/* pa24_gpio */
#define PA24_GPIO MCHP_PINMUX(a, 24, gpio, gpio)

/* pa24a_eic_extint12 */
#define PA24A_EIC_EXTINT12 MCHP_PINMUX(a, 24, a, periph)

/* pa24c_sercom3_pad2 */
#define PA24C_SERCOM3_PAD2 MCHP_PINMUX(a, 24, c, periph)

/* pa24d_sercom5_pad2 */
#define PA24D_SERCOM5_PAD2 MCHP_PINMUX(a, 24, d, periph)

/* pa24e_tc1_wo0 */
#define PA24E_TC1_WO0 MCHP_PINMUX(a, 24, e, periph)

/* pa24f_tcc1_wo2 */
#define PA24F_TCC1_WO2 MCHP_PINMUX(a, 24, f, periph)

/* pa24g_can0_tx */
#define PA24G_CAN0_TX MCHP_PINMUX(a, 24, g, periph)

/* pa24h_ac_cmp2 */
#define PA24H_AC_CMP2 MCHP_PINMUX(a, 24, h, periph)

/* pa24i_ccl_in8 */
#define PA24I_CCL_IN8 MCHP_PINMUX(a, 24, i, periph)

/* pa25_gpio */
#define PA25_GPIO MCHP_PINMUX(a, 25, gpio, gpio)

/* pa25a_eic_extint13 */
#define PA25A_EIC_EXTINT13 MCHP_PINMUX(a, 25, a, periph)

/* pa25c_sercom3_pad3 */
#define PA25C_SERCOM3_PAD3 MCHP_PINMUX(a, 25, c, periph)

/* pa25d_sercom5_pad3 */
#define PA25D_SERCOM5_PAD3 MCHP_PINMUX(a, 25, d, periph)

/* pa25e_tc1_wo1 */
#define PA25E_TC1_WO1 MCHP_PINMUX(a, 25, e, periph)

/* pa25f_tcc1_wo3 */
#define PA25F_TCC1_WO3 MCHP_PINMUX(a, 25, f, periph)

/* pa25g_can0_rx */
#define PA25G_CAN0_RX MCHP_PINMUX(a, 25, g, periph)

/* pa25h_ac_cmp3 */
#define PA25H_AC_CMP3 MCHP_PINMUX(a, 25, h, periph)

/* pa25i_ccl_out2 */
#define PA25I_CCL_OUT2 MCHP_PINMUX(a, 25, i, periph)

/* pa27_gpio */
#define PA27_GPIO MCHP_PINMUX(a, 27, gpio, gpio)

/* pa27a_eic_extint15 */
#define PA27A_EIC_EXTINT15 MCHP_PINMUX(a, 27, a, periph)

/* pa27h_gclk_io0 */
#define PA27H_GCLK_IO0 MCHP_PINMUX(a, 27, h, periph)

/* pa28_gpio */
#define PA28_GPIO MCHP_PINMUX(a, 28, gpio, gpio)

/* pa28a_eic_extint8 */
#define PA28A_EIC_EXTINT8 MCHP_PINMUX(a, 28, a, periph)

/* pa28h_gclk_io0 */
#define PA28H_GCLK_IO0 MCHP_PINMUX(a, 28, h, periph)

/* pa30_gpio */
#define PA30_GPIO MCHP_PINMUX(a, 30, gpio, gpio)

/* pa30a_eic_extint10 */
#define PA30A_EIC_EXTINT10 MCHP_PINMUX(a, 30, a, periph)

/* pa30d_sercom1_pad2 */
#define PA30D_SERCOM1_PAD2 MCHP_PINMUX(a, 30, d, periph)

/* pa30e_tcc1_wo0 */
#define PA30E_TCC1_WO0 MCHP_PINMUX(a, 30, e, periph)

/* pa30h_gclk_io0 */
#define PA30H_GCLK_IO0 MCHP_PINMUX(a, 30, h, periph)

/* pa30i_ccl_in3 */
#define PA30I_CCL_IN3 MCHP_PINMUX(a, 30, i, periph)

/* pa31_gpio */
#define PA31_GPIO MCHP_PINMUX(a, 31, gpio, gpio)

/* pa31a_eic_extint11 */
#define PA31A_EIC_EXTINT11 MCHP_PINMUX(a, 31, a, periph)

/* pa31d_sercom1_pad3 */
#define PA31D_SERCOM1_PAD3 MCHP_PINMUX(a, 31, d, periph)

/* pa31e_tcc1_wo1 */
#define PA31E_TCC1_WO1 MCHP_PINMUX(a, 31, e, periph)

/* pa31i_ccl_out1 */
#define PA31I_CCL_OUT1 MCHP_PINMUX(a, 31, i, periph)

/* pb2_gpio */
#define PB2_GPIO MCHP_PINMUX(b, 2, gpio, gpio)

/* pb2a_eic_extint2 */
#define PB2A_EIC_EXTINT2 MCHP_PINMUX(b, 2, a, periph)

/* pb2b_adc1_ain2 */
#define PB2B_ADC1_AIN2 MCHP_PINMUX(b, 2, b, periph)

/* pb2b_ptc_y8 */
#define PB2B_PTC_Y8 MCHP_PINMUX(b, 2, b, periph)

/* pb2d_sercom5_pad0 */
#define PB2D_SERCOM5_PAD0 MCHP_PINMUX(b, 2, d, periph)

/* pb2e_tc2_wo0 */
#define PB2E_TC2_WO0 MCHP_PINMUX(b, 2, e, periph)

/* pb2f_tc5_wo0 */
#define PB2F_TC5_WO0 MCHP_PINMUX(b, 2, f, periph)

/* pb2i_ccl_out0 */
#define PB2I_CCL_OUT0 MCHP_PINMUX(b, 2, i, periph)

/* pb2k_ptc_ds8 */
#define PB2K_PTC_DS8 MCHP_PINMUX(b, 2, k, periph)

/* pb3_gpio */
#define PB3_GPIO MCHP_PINMUX(b, 3, gpio, gpio)

/* pb3a_eic_extint3 */
#define PB3A_EIC_EXTINT3 MCHP_PINMUX(b, 3, a, periph)

/* pb3b_adc1_ain3 */
#define PB3B_ADC1_AIN3 MCHP_PINMUX(b, 3, b, periph)

/* pb3b_ptc_y9 */
#define PB3B_PTC_Y9 MCHP_PINMUX(b, 3, b, periph)

/* pb3d_sercom5_pad1 */
#define PB3D_SERCOM5_PAD1 MCHP_PINMUX(b, 3, d, periph)

/* pb3e_tc2_wo1 */
#define PB3E_TC2_WO1 MCHP_PINMUX(b, 3, e, periph)

/* pb3f_tc5_wo1 */
#define PB3F_TC5_WO1 MCHP_PINMUX(b, 3, f, periph)

/* pb3k_ptc_ds9 */
#define PB3K_PTC_DS9 MCHP_PINMUX(b, 3, k, periph)

/* pb8_gpio */
#define PB8_GPIO MCHP_PINMUX(b, 8, gpio, gpio)

/* pb8a_eic_extint8 */
#define PB8A_EIC_EXTINT8 MCHP_PINMUX(b, 8, a, periph)

/* pb8b_adc0_ain2 */
#define PB8B_ADC0_AIN2 MCHP_PINMUX(b, 8, b, periph)

/* pb8b_adc1_ain4 */
#define PB8B_ADC1_AIN4 MCHP_PINMUX(b, 8, b, periph)

/* pb8b_ptc_y14 */
#define PB8B_PTC_Y14 MCHP_PINMUX(b, 8, b, periph)

/* pb8d_sercom4_pad0 */
#define PB8D_SERCOM4_PAD0 MCHP_PINMUX(b, 8, d, periph)

/* pb8e_tc0_wo0 */
#define PB8E_TC0_WO0 MCHP_PINMUX(b, 8, e, periph)

/* pb8i_ccl_in8 */
#define PB8I_CCL_IN8 MCHP_PINMUX(b, 8, i, periph)

/* pb8k_ptc_ds14 */
#define PB8K_PTC_DS14 MCHP_PINMUX(b, 8, k, periph)

/* pb9_gpio */
#define PB9_GPIO MCHP_PINMUX(b, 9, gpio, gpio)

/* pb9a_eic_extint9 */
#define PB9A_EIC_EXTINT9 MCHP_PINMUX(b, 9, a, periph)

/* pb9b_adc0_ain3 */
#define PB9B_ADC0_AIN3 MCHP_PINMUX(b, 9, b, periph)

/* pb9b_adc1_ain5 */
#define PB9B_ADC1_AIN5 MCHP_PINMUX(b, 9, b, periph)

/* pb9b_ptc_y15 */
#define PB9B_PTC_Y15 MCHP_PINMUX(b, 9, b, periph)

/* pb9d_sercom4_pad1 */
#define PB9D_SERCOM4_PAD1 MCHP_PINMUX(b, 9, d, periph)

/* pb9e_tc0_wo1 */
#define PB9E_TC0_WO1 MCHP_PINMUX(b, 9, e, periph)

/* pb9i_ccl_out2 */
#define PB9I_CCL_OUT2 MCHP_PINMUX(b, 9, i, periph)

/* pb9k_ptc_ds15 */
#define PB9K_PTC_DS15 MCHP_PINMUX(b, 9, k, periph)

/* pb10_gpio */
#define PB10_GPIO MCHP_PINMUX(b, 10, gpio, gpio)

/* pb10a_eic_extint10 */
#define PB10A_EIC_EXTINT10 MCHP_PINMUX(b, 10, a, periph)

/* pb10d_sercom4_pad2 */
#define PB10D_SERCOM4_PAD2 MCHP_PINMUX(b, 10, d, periph)

/* pb10e_tc1_wo0 */
#define PB10E_TC1_WO0 MCHP_PINMUX(b, 10, e, periph)

/* pb10f_tcc0_wo4 */
#define PB10F_TCC0_WO4 MCHP_PINMUX(b, 10, f, periph)

/* pb10g_can1_tx */
#define PB10G_CAN1_TX MCHP_PINMUX(b, 10, g, periph)

/* pb10h_gclk_io4 */
#define PB10H_GCLK_IO4 MCHP_PINMUX(b, 10, h, periph)

/* pb10i_ccl_in5 */
#define PB10I_CCL_IN5 MCHP_PINMUX(b, 10, i, periph)

/* pb11_gpio */
#define PB11_GPIO MCHP_PINMUX(b, 11, gpio, gpio)

/* pb11a_eic_extint11 */
#define PB11A_EIC_EXTINT11 MCHP_PINMUX(b, 11, a, periph)

/* pb11d_sercom4_pad3 */
#define PB11D_SERCOM4_PAD3 MCHP_PINMUX(b, 11, d, periph)

/* pb11e_tc1_wo1 */
#define PB11E_TC1_WO1 MCHP_PINMUX(b, 11, e, periph)

/* pb11f_tcc0_wo5 */
#define PB11F_TCC0_WO5 MCHP_PINMUX(b, 11, f, periph)

/* pb11g_can1_rx */
#define PB11G_CAN1_RX MCHP_PINMUX(b, 11, g, periph)

/* pb11h_gclk_io5 */
#define PB11H_GCLK_IO5 MCHP_PINMUX(b, 11, h, periph)

/* pb11i_ccl_out1 */
#define PB11I_CCL_OUT1 MCHP_PINMUX(b, 11, i, periph)

/* pb22_gpio */
#define PB22_GPIO MCHP_PINMUX(b, 22, gpio, gpio)

/* pb22a_eic_extint6 */
#define PB22A_EIC_EXTINT6 MCHP_PINMUX(b, 22, a, periph)

/* pb22d_sercom5_pad2 */
#define PB22D_SERCOM5_PAD2 MCHP_PINMUX(b, 22, d, periph)

/* pb22e_tc3_wo0 */
#define PB22E_TC3_WO0 MCHP_PINMUX(b, 22, e, periph)

/* pb22g_can0_tx */
#define PB22G_CAN0_TX MCHP_PINMUX(b, 22, g, periph)

/* pb22h_gclk_io0 */
#define PB22H_GCLK_IO0 MCHP_PINMUX(b, 22, h, periph)

/* pb22i_ccl_in0 */
#define PB22I_CCL_IN0 MCHP_PINMUX(b, 22, i, periph)

/* pb23_gpio */
#define PB23_GPIO MCHP_PINMUX(b, 23, gpio, gpio)

/* pb23a_eic_extint7 */
#define PB23A_EIC_EXTINT7 MCHP_PINMUX(b, 23, a, periph)

/* pb23d_sercom5_pad3 */
#define PB23D_SERCOM5_PAD3 MCHP_PINMUX(b, 23, d, periph)

/* pb23e_tc3_wo1 */
#define PB23E_TC3_WO1 MCHP_PINMUX(b, 23, e, periph)

/* pb23g_can0_rx */
#define PB23G_CAN0_RX MCHP_PINMUX(b, 23, g, periph)

/* pb23h_gclk_io1 */
#define PB23H_GCLK_IO1 MCHP_PINMUX(b, 23, h, periph)

/* pb23i_ccl_out0 */
#define PB23I_CCL_OUT0 MCHP_PINMUX(b, 23, i, periph)

#endif /* MICROCHIP_PIC32CM2532JH01048_PINCTRL_H_ */
