/*
 * Copyright (c) 2025 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CM1216JH01032_PINCTRL_H_
#define MICROCHIP_PIC32CM1216JH01032_PINCTRL_H_

#include <dt-bindings/pic32c/pic32cm_jh/common/mchp_pinctrl_pinmux_pic32c.h>

/* pa0_gpio */
#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

/* pa0a_eic_extint0 */
#define PA0A_EIC_EXTINT0 MCHP_PINMUX(a, 0, a, periph)

/* pa0a_rstc_extwake0 */
#define PA0A_RSTC_EXTWAKE0 MCHP_PINMUX(a, 0, a, periph)

/* pa0d_sercom1_pad0 */
#define PA0D_SERCOM1_PAD0 MCHP_PINMUX(a, 0, d, periph)

/* pa0h_ac_cmp2 */
#define PA0H_AC_CMP2 MCHP_PINMUX(a, 0, h, periph)

/* pa1_gpio */
#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

/* pa1a_eic_extint1 */
#define PA1A_EIC_EXTINT1 MCHP_PINMUX(a, 1, a, periph)

/* pa1a_rstc_extwake1 */
#define PA1A_RSTC_EXTWAKE1 MCHP_PINMUX(a, 1, a, periph)

/* pa1d_sercom1_pad1 */
#define PA1D_SERCOM1_PAD1 MCHP_PINMUX(a, 1, d, periph)

/* pa1h_ac_cmp3 */
#define PA1H_AC_CMP3 MCHP_PINMUX(a, 1, h, periph)

/* pa2_gpio */
#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

/* pa2a_eic_extint2 */
#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

/* pa2a_rstc_extwake2 */
#define PA2A_RSTC_EXTWAKE2 MCHP_PINMUX(a, 2, a, periph)

/* pa2b_ac_ain4 */
#define PA2B_AC_AIN4 MCHP_PINMUX(a, 2, b, periph)

/* pa2b_adc0_ain0 */
#define PA2B_ADC0_AIN0 MCHP_PINMUX(a, 2, b, periph)

/* pa3_gpio */
#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

/* pa3a_eic_extint3 */
#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

/* pa3a_rstc_extwake3 */
#define PA3A_RSTC_EXTWAKE3 MCHP_PINMUX(a, 3, a, periph)

/* pa3b_ac_ain5 */
#define PA3B_AC_AIN5 MCHP_PINMUX(a, 3, b, periph)

/* pa3b_adc0_ain1 */
#define PA3B_ADC0_AIN1 MCHP_PINMUX(a, 3, b, periph)

/* pa3b_adc0_vrefp */
#define PA3B_ADC0_VREFP MCHP_PINMUX(a, 3, b, periph)

/* pa4_gpio */
#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

/* pa4a_eic_extint4 */
#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

/* pa4a_rstc_extwake4 */
#define PA4A_RSTC_EXTWAKE4 MCHP_PINMUX(a, 4, a, periph)

/* pa4b_ac_ain0 */
#define PA4B_AC_AIN0 MCHP_PINMUX(a, 4, b, periph)

/* pa4b_adc0_ain4 */
#define PA4B_ADC0_AIN4 MCHP_PINMUX(a, 4, b, periph)

/* pa4d_sercom0_pad0 */
#define PA4D_SERCOM0_PAD0 MCHP_PINMUX(a, 4, d, periph)

/* pa5_gpio */
#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

/* pa5a_eic_extint5 */
#define PA5A_EIC_EXTINT5 MCHP_PINMUX(a, 5, a, periph)

/* pa5a_rstc_extwake5 */
#define PA5A_RSTC_EXTWAKE5 MCHP_PINMUX(a, 5, a, periph)

/* pa5b_ac_ain1 */
#define PA5B_AC_AIN1 MCHP_PINMUX(a, 5, b, periph)

/* pa5b_adc0_ain5 */
#define PA5B_ADC0_AIN5 MCHP_PINMUX(a, 5, b, periph)

/* pa5d_sercom0_pad1 */
#define PA5D_SERCOM0_PAD1 MCHP_PINMUX(a, 5, d, periph)

/* pa6_gpio */
#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

/* pa6a_eic_extint6 */
#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

/* pa6a_rstc_extwake6 */
#define PA6A_RSTC_EXTWAKE6 MCHP_PINMUX(a, 6, a, periph)

/* pa6b_ac_ain2 */
#define PA6B_AC_AIN2 MCHP_PINMUX(a, 6, b, periph)

/* pa6b_adc0_ain6 */
#define PA6B_ADC0_AIN6 MCHP_PINMUX(a, 6, b, periph)

/* pa6d_sercom0_pad2 */
#define PA6D_SERCOM0_PAD2 MCHP_PINMUX(a, 6, d, periph)

/* pa7_gpio */
#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

/* pa7a_eic_extint7 */
#define PA7A_EIC_EXTINT7 MCHP_PINMUX(a, 7, a, periph)

/* pa7a_rstc_extwake7 */
#define PA7A_RSTC_EXTWAKE7 MCHP_PINMUX(a, 7, a, periph)

/* pa7b_ac_ain3 */
#define PA7B_AC_AIN3 MCHP_PINMUX(a, 7, b, periph)

/* pa7b_adc0_ain7 */
#define PA7B_ADC0_AIN7 MCHP_PINMUX(a, 7, b, periph)

/* pa7d_sercom0_pad3 */
#define PA7D_SERCOM0_PAD3 MCHP_PINMUX(a, 7, d, periph)

/* pa8_gpio */
#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

/* pa8a_eic_nmi */
#define PA8A_EIC_NMI MCHP_PINMUX(a, 8, a, periph)

/* pa8a_rstc_extwake8 */
#define PA8A_RSTC_EXTWAKE8 MCHP_PINMUX(a, 8, a, periph)

/* pa8b_adc0_ain8 */
#define PA8B_ADC0_AIN8 MCHP_PINMUX(a, 8, b, periph)

/* pa8c_sercom0_pad0 */
#define PA8C_SERCOM0_PAD0 MCHP_PINMUX(a, 8, c, periph)

/* pa8d_sercom2_pad0 */
#define PA8D_SERCOM2_PAD0 MCHP_PINMUX(a, 8, d, periph)

/* pa9_gpio */
#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

/* pa9a_eic_extint9 */
#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

/* pa9a_rstc_extwake9 */
#define PA9A_RSTC_EXTWAKE9 MCHP_PINMUX(a, 9, a, periph)

/* pa9b_adc0_ain9 */
#define PA9B_ADC0_AIN9 MCHP_PINMUX(a, 9, b, periph)

/* pa9c_sercom0_pad1 */
#define PA9C_SERCOM0_PAD1 MCHP_PINMUX(a, 9, c, periph)

/* pa9d_sercom2_pad1 */
#define PA9D_SERCOM2_PAD1 MCHP_PINMUX(a, 9, d, periph)

/* pa10_gpio */
#define PA10_GPIO MCHP_PINMUX(a, 10, gpio, gpio)

/* pa10a_eic_extint10 */
#define PA10A_EIC_EXTINT10 MCHP_PINMUX(a, 10, a, periph)

/* pa10a_rstc_extwake10 */
#define PA10A_RSTC_EXTWAKE10 MCHP_PINMUX(a, 10, a, periph)

/* pa10b_adc0_ain10 */
#define PA10B_ADC0_AIN10 MCHP_PINMUX(a, 10, b, periph)

/* pa10c_sercom0_pad2 */
#define PA10C_SERCOM0_PAD2 MCHP_PINMUX(a, 10, c, periph)

/* pa10d_sercom2_pad2 */
#define PA10D_SERCOM2_PAD2 MCHP_PINMUX(a, 10, d, periph)

/* pa10h_gclk_io4 */
#define PA10H_GCLK_IO4 MCHP_PINMUX(a, 10, h, periph)

/* pa11_gpio */
#define PA11_GPIO MCHP_PINMUX(a, 11, gpio, gpio)

/* pa11a_eic_extint11 */
#define PA11A_EIC_EXTINT11 MCHP_PINMUX(a, 11, a, periph)

/* pa11a_rstc_extwake11 */
#define PA11A_RSTC_EXTWAKE11 MCHP_PINMUX(a, 11, a, periph)

/* pa11b_adc0_ain11 */
#define PA11B_ADC0_AIN11 MCHP_PINMUX(a, 11, b, periph)

/* pa11c_sercom0_pad3 */
#define PA11C_SERCOM0_PAD3 MCHP_PINMUX(a, 11, c, periph)

/* pa11d_sercom2_pad3 */
#define PA11D_SERCOM2_PAD3 MCHP_PINMUX(a, 11, d, periph)

/* pa11h_gclk_io5 */
#define PA11H_GCLK_IO5 MCHP_PINMUX(a, 11, h, periph)

/* pa14_gpio */
#define PA14_GPIO MCHP_PINMUX(a, 14, gpio, gpio)

/* pa14a_eic_extint14 */
#define PA14A_EIC_EXTINT14 MCHP_PINMUX(a, 14, a, periph)

/* pa14a_rstc_extwake14 */
#define PA14A_RSTC_EXTWAKE14 MCHP_PINMUX(a, 14, a, periph)

/* pa14c_sercom2_pad2 */
#define PA14C_SERCOM2_PAD2 MCHP_PINMUX(a, 14, c, periph)

/* pa14e_tc4_wo0 */
#define PA14E_TC4_WO0 MCHP_PINMUX(a, 14, e, periph)

/* pa14h_gclk_io0 */
#define PA14H_GCLK_IO0 MCHP_PINMUX(a, 14, h, periph)

/* pa15_gpio */
#define PA15_GPIO MCHP_PINMUX(a, 15, gpio, gpio)

/* pa15a_eic_extint15 */
#define PA15A_EIC_EXTINT15 MCHP_PINMUX(a, 15, a, periph)

/* pa15a_rstc_extwake15 */
#define PA15A_RSTC_EXTWAKE15 MCHP_PINMUX(a, 15, a, periph)

/* pa15c_sercom2_pad3 */
#define PA15C_SERCOM2_PAD3 MCHP_PINMUX(a, 15, c, periph)

/* pa15e_tc4_wo1 */
#define PA15E_TC4_WO1 MCHP_PINMUX(a, 15, e, periph)

/* pa15h_gclk_io1 */
#define PA15H_GCLK_IO1 MCHP_PINMUX(a, 15, h, periph)

/* pa16_gpio */
#define PA16_GPIO MCHP_PINMUX(a, 16, gpio, gpio)

/* pa16a_eic_extint0 */
#define PA16A_EIC_EXTINT0 MCHP_PINMUX(a, 16, a, periph)

/* pa16c_sercom1_pad0 */
#define PA16C_SERCOM1_PAD0 MCHP_PINMUX(a, 16, c, periph)

/* pa16d_sercom3_pad0 */
#define PA16D_SERCOM3_PAD0 MCHP_PINMUX(a, 16, d, periph)

/* pa16h_gclk_io2 */
#define PA16H_GCLK_IO2 MCHP_PINMUX(a, 16, h, periph)

/* pa17_gpio */
#define PA17_GPIO MCHP_PINMUX(a, 17, gpio, gpio)

/* pa17a_eic_extint1 */
#define PA17A_EIC_EXTINT1 MCHP_PINMUX(a, 17, a, periph)

/* pa17c_sercom1_pad1 */
#define PA17C_SERCOM1_PAD1 MCHP_PINMUX(a, 17, c, periph)

/* pa17d_sercom3_pad1 */
#define PA17D_SERCOM3_PAD1 MCHP_PINMUX(a, 17, d, periph)

/* pa17h_gclk_io3 */
#define PA17H_GCLK_IO3 MCHP_PINMUX(a, 17, h, periph)

/* pa18_gpio */
#define PA18_GPIO MCHP_PINMUX(a, 18, gpio, gpio)

/* pa18a_eic_extint2 */
#define PA18A_EIC_EXTINT2 MCHP_PINMUX(a, 18, a, periph)

/* pa18c_sercom1_pad2 */
#define PA18C_SERCOM1_PAD2 MCHP_PINMUX(a, 18, c, periph)

/* pa18d_sercom3_pad2 */
#define PA18D_SERCOM3_PAD2 MCHP_PINMUX(a, 18, d, periph)

/* pa18e_tc4_wo0 */
#define PA18E_TC4_WO0 MCHP_PINMUX(a, 18, e, periph)

/* pa18h_ac_cmp0 */
#define PA18H_AC_CMP0 MCHP_PINMUX(a, 18, h, periph)

/* pa19_gpio */
#define PA19_GPIO MCHP_PINMUX(a, 19, gpio, gpio)

/* pa19a_eic_extint3 */
#define PA19A_EIC_EXTINT3 MCHP_PINMUX(a, 19, a, periph)

/* pa19c_sercom1_pad3 */
#define PA19C_SERCOM1_PAD3 MCHP_PINMUX(a, 19, c, periph)

/* pa19d_sercom3_pad3 */
#define PA19D_SERCOM3_PAD3 MCHP_PINMUX(a, 19, d, periph)

/* pa19e_tc4_wo1 */
#define PA19E_TC4_WO1 MCHP_PINMUX(a, 19, e, periph)

/* pa19h_ac_cmp1 */
#define PA19H_AC_CMP1 MCHP_PINMUX(a, 19, h, periph)

/* pa22_gpio */
#define PA22_GPIO MCHP_PINMUX(a, 22, gpio, gpio)

/* pa22a_eic_extint6 */
#define PA22A_EIC_EXTINT6 MCHP_PINMUX(a, 22, a, periph)

/* pa22c_sercom3_pad0 */
#define PA22C_SERCOM3_PAD0 MCHP_PINMUX(a, 22, c, periph)

/* pa22e_tc0_wo0 */
#define PA22E_TC0_WO0 MCHP_PINMUX(a, 22, e, periph)

/* pa22h_gclk_io6 */
#define PA22H_GCLK_IO6 MCHP_PINMUX(a, 22, h, periph)

/* pa23_gpio */
#define PA23_GPIO MCHP_PINMUX(a, 23, gpio, gpio)

/* pa23a_eic_extint7 */
#define PA23A_EIC_EXTINT7 MCHP_PINMUX(a, 23, a, periph)

/* pa23c_sercom3_pad1 */
#define PA23C_SERCOM3_PAD1 MCHP_PINMUX(a, 23, c, periph)

/* pa23e_tc0_wo1 */
#define PA23E_TC0_WO1 MCHP_PINMUX(a, 23, e, periph)

/* pa23h_gclk_io7 */
#define PA23H_GCLK_IO7 MCHP_PINMUX(a, 23, h, periph)

/* pa24_gpio */
#define PA24_GPIO MCHP_PINMUX(a, 24, gpio, gpio)

/* pa24a_eic_extint12 */
#define PA24A_EIC_EXTINT12 MCHP_PINMUX(a, 24, a, periph)

/* pa24c_sercom3_pad2 */
#define PA24C_SERCOM3_PAD2 MCHP_PINMUX(a, 24, c, periph)

/* pa24e_tc1_wo0 */
#define PA24E_TC1_WO0 MCHP_PINMUX(a, 24, e, periph)

/* pa24g_can0_tx */
#define PA24G_CAN0_TX MCHP_PINMUX(a, 24, g, periph)

/* pa24h_ac_cmp2 */
#define PA24H_AC_CMP2 MCHP_PINMUX(a, 24, h, periph)

/* pa25_gpio */
#define PA25_GPIO MCHP_PINMUX(a, 25, gpio, gpio)

/* pa25a_eic_extint13 */
#define PA25A_EIC_EXTINT13 MCHP_PINMUX(a, 25, a, periph)

/* pa25c_sercom3_pad3 */
#define PA25C_SERCOM3_PAD3 MCHP_PINMUX(a, 25, c, periph)

/* pa25e_tc1_wo1 */
#define PA25E_TC1_WO1 MCHP_PINMUX(a, 25, e, periph)

/* pa25g_can0_rx */
#define PA25G_CAN0_RX MCHP_PINMUX(a, 25, g, periph)

/* pa25h_ac_cmp3 */
#define PA25H_AC_CMP3 MCHP_PINMUX(a, 25, h, periph)

/* pa27_gpio */
#define PA27_GPIO MCHP_PINMUX(a, 27, gpio, gpio)

/* pa27a_eic_extint15 */
#define PA27A_EIC_EXTINT15 MCHP_PINMUX(a, 27, a, periph)

/* pa27h_gclk_io0 */
#define PA27H_GCLK_IO0 MCHP_PINMUX(a, 27, h, periph)

/* pa28_gpio */
#define PA28_GPIO MCHP_PINMUX(a, 28, gpio, gpio)

/* pa28a_eic_extint8 */
#define PA28A_EIC_EXTINT8 MCHP_PINMUX(a, 28, a, periph)

/* pa28h_gclk_io0 */
#define PA28H_GCLK_IO0 MCHP_PINMUX(a, 28, h, periph)

/* pa30_gpio */
#define PA30_GPIO MCHP_PINMUX(a, 30, gpio, gpio)

/* pa30a_eic_extint10 */
#define PA30A_EIC_EXTINT10 MCHP_PINMUX(a, 30, a, periph)

/* pa30d_sercom1_pad2 */
#define PA30D_SERCOM1_PAD2 MCHP_PINMUX(a, 30, d, periph)

/* pa30h_gclk_io0 */
#define PA30H_GCLK_IO0 MCHP_PINMUX(a, 30, h, periph)

/* pa31_gpio */
#define PA31_GPIO MCHP_PINMUX(a, 31, gpio, gpio)

/* pa31a_eic_extint11 */
#define PA31A_EIC_EXTINT11 MCHP_PINMUX(a, 31, a, periph)

/* pa31d_sercom1_pad3 */
#define PA31D_SERCOM1_PAD3 MCHP_PINMUX(a, 31, d, periph)

#endif /* MICROCHIP_PIC32CM1216JH01032_PINCTRL_H_ */
