/*
 * Copyright (c) 2026 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file sercom_pic32cz_ca.h
 * @brief Generic SERCOM USART register macros for PIC32CZ_CA family.
 *
 * This file defines generic register and bit mask names for the SERCOM USART
 * peripheral on Microchip PIC32CZ_CA devices.These macros are intended for
 * use in the SERCOM UART G1 driver.
 *
 */

#ifndef MICROCHIP_COMMON_SERCOM_PIC32CZ_CA_H_
#define MICROCHIP_COMMON_SERCOM_PIC32CZ_CA_H_

/**
 * @brief Get the base address of the USART register block.
 *
 * This macro returns the base address of the USART registers for the given
 * SERCOM instance. The @p is_clock_external parameter is included for
 * compatibility with unified driver code, but is not used for this device
 * family.
 *
 * @param regs Pointer to the SERCOM register structure.
 * @param is_clock_external Boolean indicating if the clock is external (not
 * used).
 * @return Pointer to the USART register block.
 */
typedef sercom_usart_int_registers_t sercom_usart_registers_t;
#define UART_GET_BASE_ADDR(regs, is_clock_external)                            \
  ((sercom_usart_registers_t *)((void *)&((regs)->USART_INT)))

/*SERCOM_USART_SYNCBUSY*/
#define SERCOM_USART_SYNCBUSY_Msk SERCOM_USART_INT_SYNCBUSY_Msk

/*SERCOM_USART_CTRLA*/
#define SERCOM_USART_CTRLA_FORM_Msk SERCOM_USART_INT_CTRLA_FORM_Msk
#define SERCOM_USART_CTRLA_FORM_USART_FRAME_WITH_PARITY                        \
  SERCOM_USART_INT_CTRLA_FORM_USARTP
#define SERCOM_USART_CTRLA_FORM_USART_FRAME_NO_PARITY                          \
  SERCOM_USART_INT_CTRLA_FORM_USART
#define SERCOM_USART_CTRLA_RXPO_Msk SERCOM_USART_INT_CTRLA_RXPO_Msk
#define SERCOM_USART_CTRLA_TXPO_Msk SERCOM_USART_INT_CTRLA_TXPO_Msk
#define SERCOM_USART_CTRLA_RXPO(rxpo) SERCOM_USART_INT_CTRLA_RXPO(rxpo)
#define SERCOM_USART_CTRLA_TXPO(txpo) SERCOM_USART_INT_CTRLA_TXPO(txpo)
#define SERCOM_USART_CTRLA_CPOL_Msk SERCOM_USART_INT_CTRLA_CPOL_Msk
#define SERCOM_USART_CTRLA_MODE_Msk SERCOM_USART_INT_CTRLA_MODE_Msk
#define SERCOM_USART_CTRLA_MODE_USART_EXT                                      \
  SERCOM_USART_INT_CTRLA_MODE_USART_EXT_CLK
#define SERCOM_USART_CTRLA_MODE_USART_INT                                      \
  SERCOM_USART_INT_CTRLA_MODE_USART_INT_CLK
#define SERCOM_USART_CTRLA_DORD_Msk SERCOM_USART_INT_CTRLA_DORD_Msk
#define SERCOM_USART_CTRLA_SAMPR_Msk SERCOM_USART_INT_CTRLA_SAMPR_Msk
#define SERCOM_USART_CTRLA_ENABLE_Msk SERCOM_USART_INT_CTRLA_ENABLE_Msk
#define SERCOM_USART_CTRLA_RUNSTDBY_Msk SERCOM_USART_INT_CTRLA_RUNSTDBY_Msk

/*SERCOM_USART_CTRLB*/
#define SERCOM_USART_CTRLB_PMODE_Msk SERCOM_USART_INT_CTRLB_PMODE_Msk
#define SERCOM_USART_CTRLB_SBMODE_Msk SERCOM_USART_INT_CTRLB_SBMODE_Msk
#define SERCOM_USART_CTRLB_CHSIZE_Msk SERCOM_USART_INT_CTRLB_CHSIZE_Msk
#define SERCOM_USART_CTRLB_CHSIZE_5_BIT SERCOM_USART_INT_CTRLB_CHSIZE_5_BIT
#define SERCOM_USART_CTRLB_CHSIZE_6_BIT SERCOM_USART_INT_CTRLB_CHSIZE_6_BIT
#define SERCOM_USART_CTRLB_CHSIZE_7_BIT SERCOM_USART_INT_CTRLB_CHSIZE_7_BIT
#define SERCOM_USART_CTRLB_CHSIZE_8_BIT SERCOM_USART_INT_CTRLB_CHSIZE_8_BIT
#define SERCOM_USART_CTRLB_CHSIZE_9_BIT SERCOM_USART_INT_CTRLB_CHSIZE_9_BIT
#define SERCOM_USART_CTRLB_RXEN_Msk SERCOM_USART_INT_CTRLB_RXEN_Msk
#define SERCOM_USART_CTRLB_TXEN_Msk SERCOM_USART_INT_CTRLB_TXEN_Msk

/*SERCOM_USART_STATUS*/
#define SERCOM_USART_STATUS_BUFOVF_Msk SERCOM_USART_INT_STATUS_BUFOVF_Msk
#define SERCOM_USART_STATUS_FERR_Msk SERCOM_USART_INT_STATUS_FERR_Msk
#define SERCOM_USART_STATUS_PERR_Msk SERCOM_USART_INT_STATUS_PERR_Msk
#define SERCOM_USART_STATUS_ISF_Msk SERCOM_USART_INT_STATUS_ISF_Msk
#define SERCOM_USART_STATUS_COLL_Msk SERCOM_USART_INT_STATUS_COLL_Msk

/*SERCOM_USART_INTENSET*/
#define SERCOM_USART_INTENSET_TXC_Msk SERCOM_USART_INT_INTENSET_TXC_Msk
#define SERCOM_USART_INTENSET_RXC_Msk SERCOM_USART_INT_INTENSET_RXC_Msk
#define SERCOM_USART_INTENSET_DRE_Msk SERCOM_USART_INT_INTENSET_DRE_Msk
#define SERCOM_USART_INTENSET_ERROR_Msk SERCOM_USART_INT_INTENSET_ERROR_Msk

/*SERCOM_USART_INTENCLR*/
#define SERCOM_USART_INTENCLR_TXC_Msk SERCOM_USART_INT_INTENCLR_TXC_Msk
#define SERCOM_USART_INTENCLR_RXC_Msk SERCOM_USART_INT_INTENCLR_RXC_Msk
#define SERCOM_USART_INTENCLR_Msk SERCOM_USART_INT_INTENCLR_Msk
#define SERCOM_USART_INTENCLR_DRE_Msk SERCOM_USART_INT_INTENCLR_DRE_Msk
#define SERCOM_USART_INTENCLR_ERROR_Msk SERCOM_USART_INT_INTENCLR_ERROR_Msk

/*SERCOM_USART_INTFLAG*/
#define SERCOM_USART_INTFLAG_RXC_Msk SERCOM_USART_INT_INTFLAG_RXC_Msk
#define SERCOM_USART_INTFLAG_DRE_Msk SERCOM_USART_INT_INTFLAG_DRE_Msk
#define SERCOM_USART_INTFLAG_TXC_Msk SERCOM_USART_INT_INTFLAG_TXC_Msk
#define SERCOM_USART_INTFLAG_ERROR_Msk SERCOM_USART_INT_INTFLAG_ERROR_Msk
#define SERCOM_USART_INTFLAG_RXBRK_Msk SERCOM_USART_INT_INTFLAG_RXBRK_Msk
#define SERCOM_USART_INTFLAG_CTSIC_Msk SERCOM_USART_INT_INTFLAG_CTSIC_Msk
#define SERCOM_USART_INTFLAG_RXS_Msk SERCOM_USART_INT_INTFLAG_RXS_Msk

#endif /* MICROCHIP_COMMON_SERCOM_PIC32CZ_CA_H_ */
