/*
 * Copyright (c) 2025 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CZ2051CA80144_PINCTRL_H_
#define MICROCHIP_PIC32CZ2051CA80144_PINCTRL_H_

#include <dt-bindings/pic32c/pic32cz_ca/common/mchp_pinctrl_pinmux_pic32c.h>

#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

#define PA0A_EIC_EXTINT0 MCHP_PINMUX(a, 0, a, periph)

#define PA0K_ETH_GTX1 MCHP_PINMUX(a, 0, k, periph)

#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

#define PA1A_EIC_EXTINT1 MCHP_PINMUX(a, 1, a, periph)

#define PA1K_ETH_GTX0 MCHP_PINMUX(a, 1, k, periph)

#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

#define PA2F_TCC2_WO5 MCHP_PINMUX(a, 2, f, periph)

#define PA2K_ETH_GTXEN MCHP_PINMUX(a, 2, k, periph)

#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

#define PA3D_SERCOM2_PAD3 MCHP_PINMUX(a, 3, d, periph)

#define PA3F_TCC2_WO4 MCHP_PINMUX(a, 3, f, periph)

#define PA3K_ETH_GMDC MCHP_PINMUX(a, 3, k, periph)

#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

#define PA4D_SERCOM2_PAD2 MCHP_PINMUX(a, 4, d, periph)

#define PA4F_TCC2_WO3 MCHP_PINMUX(a, 4, f, periph)

#define PA4K_ETH_GMDIO MCHP_PINMUX(a, 4, k, periph)

#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

#define PA5A_EIC_EXTINT4 MCHP_PINMUX(a, 5, a, periph)

#define PA5F_TCC3_WO0 MCHP_PINMUX(a, 5, f, periph)

#define PA5K_ETH_GRXDV MCHP_PINMUX(a, 5, k, periph)

#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

#define PA6F_TCC3_WO1 MCHP_PINMUX(a, 6, f, periph)

#define PA6K_ETH_GRXER MCHP_PINMUX(a, 6, k, periph)

#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

#define PA7A_EIC_EXTINT7 MCHP_PINMUX(a, 7, a, periph)

#define PA7B_ADC3_AIN3 MCHP_PINMUX(a, 7, b, periph)

#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

#define PA8A_EIC_EXTINT8 MCHP_PINMUX(a, 8, a, periph)

#define PA8B_ADC3_AIN2 MCHP_PINMUX(a, 8, b, periph)

#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

#define PA9B_ADC3_AIN1 MCHP_PINMUX(a, 9, b, periph)

#define PA10_GPIO MCHP_PINMUX(a, 10, gpio, gpio)

#define PA10A_EIC_EXTINT10 MCHP_PINMUX(a, 10, a, periph)

#define PA10B_ADC3_AIN0 MCHP_PINMUX(a, 10, b, periph)

#define PA11_GPIO MCHP_PINMUX(a, 11, gpio, gpio)

#define PA11A_EIC_EXTINT11 MCHP_PINMUX(a, 11, a, periph)

#define PA11B_ADC2_AIN3 MCHP_PINMUX(a, 11, b, periph)

#define PA12_GPIO MCHP_PINMUX(a, 12, gpio, gpio)

#define PA12A_EIC_EXTINT12 MCHP_PINMUX(a, 12, a, periph)

#define PA12B_ADC2_AIN2 MCHP_PINMUX(a, 12, b, periph)

#define PA13_GPIO MCHP_PINMUX(a, 13, gpio, gpio)

#define PA13A_EIC_EXTINT13 MCHP_PINMUX(a, 13, a, periph)

#define PA13B_ADC2_AIN1 MCHP_PINMUX(a, 13, b, periph)

#define PA14_GPIO MCHP_PINMUX(a, 14, gpio, gpio)

#define PA14A_EIC_EXTINT14 MCHP_PINMUX(a, 14, a, periph)

#define PA14B_ADC2_AIN0 MCHP_PINMUX(a, 14, b, periph)

#define PA15_GPIO MCHP_PINMUX(a, 15, gpio, gpio)

#define PA15A_EIC_EXTINT15 MCHP_PINMUX(a, 15, a, periph)

#define PA15B_ADC1_AIN3 MCHP_PINMUX(a, 15, b, periph)

#define PA16_GPIO MCHP_PINMUX(a, 16, gpio, gpio)

#define PA16A_EIC_EXTINT0 MCHP_PINMUX(a, 16, a, periph)

#define PA16B_ADC1_AIN2 MCHP_PINMUX(a, 16, b, periph)

#define PA17_GPIO MCHP_PINMUX(a, 17, gpio, gpio)

#define PA17A_EIC_EXTINT1 MCHP_PINMUX(a, 17, a, periph)

#define PA17B_ADC1_AIN1 MCHP_PINMUX(a, 17, b, periph)

#define PA18_GPIO MCHP_PINMUX(a, 18, gpio, gpio)

#define PA18A_EIC_EXTINT2 MCHP_PINMUX(a, 18, a, periph)

#define PA18B_ADC1_AIN0 MCHP_PINMUX(a, 18, b, periph)

#define PA19_GPIO MCHP_PINMUX(a, 19, gpio, gpio)

#define PA19A_EIC_EXTINT3 MCHP_PINMUX(a, 19, a, periph)

#define PA19B_AC_AIN3 MCHP_PINMUX(a, 19, b, periph)

#define PA19B_ADC0_AIN5 MCHP_PINMUX(a, 19, b, periph)

#define PA20_GPIO MCHP_PINMUX(a, 20, gpio, gpio)

#define PA20A_EIC_EXTINT4 MCHP_PINMUX(a, 20, a, periph)

#define PA20B_AC_AIN2 MCHP_PINMUX(a, 20, b, periph)

#define PA20B_ADC0_AIN4 MCHP_PINMUX(a, 20, b, periph)

#define PA21_GPIO MCHP_PINMUX(a, 21, gpio, gpio)

#define PA21A_EIC_EXTINT5 MCHP_PINMUX(a, 21, a, periph)

#define PA21F_TCC8_WO0 MCHP_PINMUX(a, 21, f, periph)

#define PA21K_ETH_TXCK MCHP_PINMUX(a, 21, k, periph)

#define PA22_GPIO MCHP_PINMUX(a, 22, gpio, gpio)

#define PA22A_EIC_EXTINT6 MCHP_PINMUX(a, 22, a, periph)

#define PA22F_TCC7_WO0 MCHP_PINMUX(a, 22, f, periph)

#define PA22K_ETH_TSUCOMP MCHP_PINMUX(a, 22, k, periph)

#define PA23_GPIO MCHP_PINMUX(a, 23, gpio, gpio)

#define PA23A_EIC_EXTINT7 MCHP_PINMUX(a, 23, a, periph)

#define PA23F_TCC7_WO1 MCHP_PINMUX(a, 23, f, periph)

#define PA24_GPIO MCHP_PINMUX(a, 24, gpio, gpio)

#define PA24A_EIC_EXTINT8 MCHP_PINMUX(a, 24, a, periph)

#define PA24B_ADC3_AIN5 MCHP_PINMUX(a, 24, b, periph)

#define PA25_GPIO MCHP_PINMUX(a, 25, gpio, gpio)

#define PA25A_EIC_EXTINT9 MCHP_PINMUX(a, 25, a, periph)

#define PA25B_ADC3_AIN4 MCHP_PINMUX(a, 25, b, periph)

#define PA26_GPIO MCHP_PINMUX(a, 26, gpio, gpio)

#define PA26A_EIC_EXTINT10 MCHP_PINMUX(a, 26, a, periph)

#define PA26B_ADC2_AIN5 MCHP_PINMUX(a, 26, b, periph)

#define PA27_GPIO MCHP_PINMUX(a, 27, gpio, gpio)

#define PA27A_EIC_EXTINT11 MCHP_PINMUX(a, 27, a, periph)

#define PA27B_ADC2_AIN4 MCHP_PINMUX(a, 27, b, periph)

#define PA28_GPIO MCHP_PINMUX(a, 28, gpio, gpio)

#define PA28A_EIC_EXTINT12 MCHP_PINMUX(a, 28, a, periph)

#define PA28B_ADC1_AIN5 MCHP_PINMUX(a, 28, b, periph)

#define PA29_GPIO MCHP_PINMUX(a, 29, gpio, gpio)

#define PA29A_EIC_EXTINT13 MCHP_PINMUX(a, 29, a, periph)

#define PA29B_ADC1_AIN4 MCHP_PINMUX(a, 29, b, periph)

#define PB0_GPIO MCHP_PINMUX(b, 0, gpio, gpio)

#define PB0A_EIC_EXTINT0 MCHP_PINMUX(b, 0, a, periph)

#define PB0B_AC_AIN1 MCHP_PINMUX(b, 0, b, periph)

#define PB0B_ADC0_AIN3 MCHP_PINMUX(b, 0, b, periph)

#define PB1_GPIO MCHP_PINMUX(b, 1, gpio, gpio)

#define PB1A_EIC_EXTINT1 MCHP_PINMUX(b, 1, a, periph)

#define PB1B_AC_AIN0 MCHP_PINMUX(b, 1, b, periph)

#define PB1B_ADC0_AIN2 MCHP_PINMUX(b, 1, b, periph)

#define PB2_GPIO MCHP_PINMUX(b, 2, gpio, gpio)

#define PB2A_EIC_EXTINT2 MCHP_PINMUX(b, 2, a, periph)

#define PB2B_ADC0_AIN1 MCHP_PINMUX(b, 2, b, periph)

#define PB3_GPIO MCHP_PINMUX(b, 3, gpio, gpio)

#define PB3A_EIC_EXTINT3 MCHP_PINMUX(b, 3, a, periph)

#define PB3B_ADC0_AIN0 MCHP_PINMUX(b, 3, b, periph)

#define PB4_GPIO MCHP_PINMUX(b, 4, gpio, gpio)

#define PB4A_EIC_EXTINT4 MCHP_PINMUX(b, 4, a, periph)

#define PB5_GPIO MCHP_PINMUX(b, 5, gpio, gpio)

#define PB5A_EIC_EXTINT5 MCHP_PINMUX(b, 5, a, periph)

#define PB6_GPIO MCHP_PINMUX(b, 6, gpio, gpio)

#define PB6A_EIC_EXTINT6 MCHP_PINMUX(b, 6, a, periph)

#define PB6P_PTC_DRV11 MCHP_PINMUX(b, 6, p, periph)

#define PB7_GPIO MCHP_PINMUX(b, 7, gpio, gpio)

#define PB7A_EIC_EXTINT7 MCHP_PINMUX(b, 7, a, periph)

#define PB7P_PTC_DRV10 MCHP_PINMUX(b, 7, p, periph)

#define PB8_GPIO MCHP_PINMUX(b, 8, gpio, gpio)

#define PB8A_EIC_EXTINT8 MCHP_PINMUX(b, 8, a, periph)

#define PB8P_PTC_DRV9 MCHP_PINMUX(b, 8, p, periph)

#define PB9_GPIO MCHP_PINMUX(b, 9, gpio, gpio)

#define PB9A_EIC_EXTINT9 MCHP_PINMUX(b, 9, a, periph)

#define PB9P_PTC_DRV8 MCHP_PINMUX(b, 9, p, periph)

#define PB10_GPIO MCHP_PINMUX(b, 10, gpio, gpio)

#define PB10A_EIC_EXTINT10 MCHP_PINMUX(b, 10, a, periph)

#define PB10F_TCC1_WO0 MCHP_PINMUX(b, 10, f, periph)

#define PB10P_PTC_DRV7 MCHP_PINMUX(b, 10, p, periph)

#define PB11_GPIO MCHP_PINMUX(b, 11, gpio, gpio)

#define PB11A_EIC_EXTINT11 MCHP_PINMUX(b, 11, a, periph)

#define PB11F_TCC1_WO1 MCHP_PINMUX(b, 11, f, periph)

#define PB11P_PTC_DRV6 MCHP_PINMUX(b, 11, p, periph)

#define PB12_GPIO MCHP_PINMUX(b, 12, gpio, gpio)

#define PB12A_EIC_EXTINT12 MCHP_PINMUX(b, 12, a, periph)

#define PB12F_TCC1_WO2 MCHP_PINMUX(b, 12, f, periph)

#define PB12P_PTC_DRV5 MCHP_PINMUX(b, 12, p, periph)

#define PB13_GPIO MCHP_PINMUX(b, 13, gpio, gpio)

#define PB13A_EIC_EXTINT13 MCHP_PINMUX(b, 13, a, periph)

#define PB13F_TCC1_WO3 MCHP_PINMUX(b, 13, f, periph)

#define PB13P_PTC_DRV4 MCHP_PINMUX(b, 13, p, periph)

#define PB14_GPIO MCHP_PINMUX(b, 14, gpio, gpio)

#define PB14A_EIC_EXTINT14 MCHP_PINMUX(b, 14, a, periph)

#define PB14F_TCC1_WO4 MCHP_PINMUX(b, 14, f, periph)

#define PB14P_PTC_DRV3 MCHP_PINMUX(b, 14, p, periph)

#define PB15_GPIO MCHP_PINMUX(b, 15, gpio, gpio)

#define PB15A_EIC_EXTINT15 MCHP_PINMUX(b, 15, a, periph)

#define PB15F_TCC1_WO5 MCHP_PINMUX(b, 15, f, periph)

#define PB15P_PTC_DRV2 MCHP_PINMUX(b, 15, p, periph)

#define PB16_GPIO MCHP_PINMUX(b, 16, gpio, gpio)

#define PB16A_EIC_EXTINT0 MCHP_PINMUX(b, 16, a, periph)

#define PB16F_TCC1_WO6 MCHP_PINMUX(b, 16, f, periph)

#define PB16P_PTC_DRV1 MCHP_PINMUX(b, 16, p, periph)

#define PB17_GPIO MCHP_PINMUX(b, 17, gpio, gpio)

#define PB17A_EIC_EXTINT1 MCHP_PINMUX(b, 17, a, periph)

#define PB17F_TCC1_WO7 MCHP_PINMUX(b, 17, f, periph)

#define PB17P_PTC_DRV0 MCHP_PINMUX(b, 17, p, periph)

#define PB18_GPIO MCHP_PINMUX(b, 18, gpio, gpio)

#define PB18A_EIC_EXTINT2 MCHP_PINMUX(b, 18, a, periph)

#define PB18B_ADC0_AIN6 MCHP_PINMUX(b, 18, b, periph)

#define PB19_GPIO MCHP_PINMUX(b, 19, gpio, gpio)

#define PB19A_EIC_EXTINT3 MCHP_PINMUX(b, 19, a, periph)

#define PB19B_ADC0_AIN7 MCHP_PINMUX(b, 19, b, periph)

#define PB20_GPIO MCHP_PINMUX(b, 20, gpio, gpio)

#define PB20A_EIC_EXTINT4 MCHP_PINMUX(b, 20, a, periph)

#define PB20B_ADC0_AIN8 MCHP_PINMUX(b, 20, b, periph)

#define PB21_GPIO MCHP_PINMUX(b, 21, gpio, gpio)

#define PB21A_EIC_EXTINT5 MCHP_PINMUX(b, 21, a, periph)

#define PB21P_PTC_DRV17 MCHP_PINMUX(b, 21, p, periph)

#define PB22_GPIO MCHP_PINMUX(b, 22, gpio, gpio)

#define PB22A_EIC_EXTINT6 MCHP_PINMUX(b, 22, a, periph)

#define PB22P_PTC_DRV16 MCHP_PINMUX(b, 22, p, periph)

#define PB23_GPIO MCHP_PINMUX(b, 23, gpio, gpio)

#define PB23A_EIC_EXTINT7 MCHP_PINMUX(b, 23, a, periph)

#define PB23P_PTC_DRV15 MCHP_PINMUX(b, 23, p, periph)

#define PB24_GPIO MCHP_PINMUX(b, 24, gpio, gpio)

#define PB24A_EIC_EXTINT8 MCHP_PINMUX(b, 24, a, periph)

#define PB24P_PTC_DRV14 MCHP_PINMUX(b, 24, p, periph)

#define PB25_GPIO MCHP_PINMUX(b, 25, gpio, gpio)

#define PB25A_EIC_EXTINT9 MCHP_PINMUX(b, 25, a, periph)

#define PB25P_PTC_DRV13 MCHP_PINMUX(b, 25, p, periph)

#define PB26_GPIO MCHP_PINMUX(b, 26, gpio, gpio)

#define PB26A_EIC_EXTINT10 MCHP_PINMUX(b, 26, a, periph)

#define PB26P_PTC_DRV12 MCHP_PINMUX(b, 26, p, periph)

#define PC0_GPIO MCHP_PINMUX(c, 0, gpio, gpio)

#define PC0A_EIC_EXTINT0 MCHP_PINMUX(c, 0, a, periph)

#define PC0D_SERCOM0_PAD0 MCHP_PINMUX(c, 0, d, periph)

#define PC0F_TCC0_WO0 MCHP_PINMUX(c, 0, f, periph)

#define PC0J_SPI_IXS0_FSYNC MCHP_PINMUX(c, 0, j, periph)

#define PC0M_GCLK_IO4 MCHP_PINMUX(c, 0, m, periph)

#define PC1_GPIO MCHP_PINMUX(c, 1, gpio, gpio)

#define PC1A_EIC_EXTINT1 MCHP_PINMUX(c, 1, a, periph)

#define PC1D_SERCOM0_PAD1 MCHP_PINMUX(c, 1, d, periph)

#define PC1F_TCC0_WO1 MCHP_PINMUX(c, 1, f, periph)

#define PC1J_SPI_IXS0_SCK MCHP_PINMUX(c, 1, j, periph)

#define PC1M_GCLK_IO5 MCHP_PINMUX(c, 1, m, periph)

#define PC2_GPIO MCHP_PINMUX(c, 2, gpio, gpio)

#define PC2A_EIC_EXTINT1 MCHP_PINMUX(c, 2, a, periph)

#define PC2D_SERCOM0_PAD2 MCHP_PINMUX(c, 2, d, periph)

#define PC2F_TCC0_WO2 MCHP_PINMUX(c, 2, f, periph)

#define PC2J_SPI_IXS0_SDI MCHP_PINMUX(c, 2, j, periph)

#define PC2M_GCLK_IO6 MCHP_PINMUX(c, 2, m, periph)

#define PC2P_PTC_ECI0 MCHP_PINMUX(c, 2, p, periph)

#define PC3_GPIO MCHP_PINMUX(c, 3, gpio, gpio)

#define PC3A_EIC_EXTINT3 MCHP_PINMUX(c, 3, a, periph)

#define PC3D_SERCOM0_PAD3 MCHP_PINMUX(c, 3, d, periph)

#define PC3F_TCC0_WO3 MCHP_PINMUX(c, 3, f, periph)

#define PC3J_SPI_IXS0_SDO MCHP_PINMUX(c, 3, j, periph)

#define PC3M_GCLK_IO7 MCHP_PINMUX(c, 3, m, periph)

#define PC3P_PTC_ECI1 MCHP_PINMUX(c, 3, p, periph)

#define PC4_GPIO MCHP_PINMUX(c, 4, gpio, gpio)

#define PC4A_EIC_EXTINT4 MCHP_PINMUX(c, 4, a, periph)

#define PC4D_SERCOM1_PAD0 MCHP_PINMUX(c, 4, d, periph)

#define PC4F_TCC0_WO4 MCHP_PINMUX(c, 4, f, periph)

#define PC4H_CAN0_RX MCHP_PINMUX(c, 4, h, periph)

#define PC4J_SPI_IXS0_MCLK0 MCHP_PINMUX(c, 4, j, periph)

#define PC5_GPIO MCHP_PINMUX(c, 5, gpio, gpio)

#define PC5A_EIC_EXTINT5 MCHP_PINMUX(c, 5, a, periph)

#define PC5D_SERCOM1_PAD1 MCHP_PINMUX(c, 5, d, periph)

#define PC5F_TCC0_WO5 MCHP_PINMUX(c, 5, f, periph)

#define PC5H_CAN0_TX MCHP_PINMUX(c, 5, h, periph)

#define PC5K_ETH_TSUCOMP MCHP_PINMUX(c, 5, k, periph)

#define PC6_GPIO MCHP_PINMUX(c, 6, gpio, gpio)

#define PC6A_EIC_EXTINT6 MCHP_PINMUX(c, 6, a, periph)

#define PC6B_AC_CMP1 MCHP_PINMUX(c, 6, b, periph)

#define PC6D_SERCOM1_PAD2 MCHP_PINMUX(c, 6, d, periph)

#define PC6F_TCC0_WO6 MCHP_PINMUX(c, 6, f, periph)

#define PC6H_CAN1_RX MCHP_PINMUX(c, 6, h, periph)

#define PC7_GPIO MCHP_PINMUX(c, 7, gpio, gpio)

#define PC7A_EIC_EXTINT7 MCHP_PINMUX(c, 7, a, periph)

#define PC7B_AC_CMP0 MCHP_PINMUX(c, 7, b, periph)

#define PC7D_SERCOM1_PAD3 MCHP_PINMUX(c, 7, d, periph)

#define PC7F_TCC0_WO7 MCHP_PINMUX(c, 7, f, periph)

#define PC7H_CAN1_TX MCHP_PINMUX(c, 7, h, periph)

#define PC8_GPIO MCHP_PINMUX(c, 8, gpio, gpio)

#define PC8A_EIC_EXTINT8 MCHP_PINMUX(c, 8, a, periph)

#define PC8D_SERCOM2_PAD0 MCHP_PINMUX(c, 8, d, periph)

#define PC8F_TCC5_WO0 MCHP_PINMUX(c, 8, f, periph)

#define PC8H_SQI0_CLK MCHP_PINMUX(c, 8, h, periph)

#define PC8I_SDMMC0_SDCK MCHP_PINMUX(c, 8, i, periph)

#define PC9_GPIO MCHP_PINMUX(c, 9, gpio, gpio)

#define PC9A_EIC_EXTINT9 MCHP_PINMUX(c, 9, a, periph)

#define PC9D_SERCOM2_PAD1 MCHP_PINMUX(c, 9, d, periph)

#define PC9F_TCC5_WO1 MCHP_PINMUX(c, 9, f, periph)

#define PC9H_SQI0_DATA0 MCHP_PINMUX(c, 9, h, periph)

#define PC9I_SDMMC0_SDDAT0 MCHP_PINMUX(c, 9, i, periph)

#define PC10_GPIO MCHP_PINMUX(c, 10, gpio, gpio)

#define PC10A_EIC_EXTINT10 MCHP_PINMUX(c, 10, a, periph)

#define PC10D_SERCOM2_PAD2 MCHP_PINMUX(c, 10, d, periph)

#define PC10F_TCC6_WO0 MCHP_PINMUX(c, 10, f, periph)

#define PC10H_SQI0_DATA1 MCHP_PINMUX(c, 10, h, periph)

#define PC10I_SDMMC0_SDDAT1 MCHP_PINMUX(c, 10, i, periph)

#define PC11_GPIO MCHP_PINMUX(c, 11, gpio, gpio)

#define PC11A_EIC_EXTINT11 MCHP_PINMUX(c, 11, a, periph)

#define PC11D_SERCOM2_PAD3 MCHP_PINMUX(c, 11, d, periph)

#define PC11F_TCC6_WO1 MCHP_PINMUX(c, 11, f, periph)

#define PC11H_SQI0_DATA2 MCHP_PINMUX(c, 11, h, periph)

#define PC11I_SDMMC0_SDDAT2 MCHP_PINMUX(c, 11, i, periph)

#define PC12_GPIO MCHP_PINMUX(c, 12, gpio, gpio)

#define PC12A_EIC_EXTINT12 MCHP_PINMUX(c, 12, a, periph)

#define PC12D_SERCOM3_PAD0 MCHP_PINMUX(c, 12, d, periph)

#define PC12F_TCC4_WO0 MCHP_PINMUX(c, 12, f, periph)

#define PC12H_SQI0_DATA3 MCHP_PINMUX(c, 12, h, periph)

#define PC12I_SDMMC0_SDDAT3 MCHP_PINMUX(c, 12, i, periph)

#define PC13_GPIO MCHP_PINMUX(c, 13, gpio, gpio)

#define PC13A_EIC_EXTINT13 MCHP_PINMUX(c, 13, a, periph)

#define PC13D_SERCOM3_PAD1 MCHP_PINMUX(c, 13, d, periph)

#define PC13F_TCC4_WO1 MCHP_PINMUX(c, 13, f, periph)

#define PC13H_SQI0_CS0 MCHP_PINMUX(c, 13, h, periph)

#define PC13I_SDMMC0_SDCMD MCHP_PINMUX(c, 13, i, periph)

#define PC14_GPIO MCHP_PINMUX(c, 14, gpio, gpio)

#define PC14A_EIC_EXTINT14 MCHP_PINMUX(c, 14, a, periph)

#define PC14D_SERCOM3_PAD2 MCHP_PINMUX(c, 14, d, periph)

#define PC14F_TCC8_WO0 MCHP_PINMUX(c, 14, f, periph)

#define PC14I_SDMMC0_SDWP MCHP_PINMUX(c, 14, i, periph)

#define PC15_GPIO MCHP_PINMUX(c, 15, gpio, gpio)

#define PC15A_EIC_EXTINT15 MCHP_PINMUX(c, 15, a, periph)

#define PC15D_SERCOM3_PAD3 MCHP_PINMUX(c, 15, d, periph)

#define PC15F_TCC8_WO1 MCHP_PINMUX(c, 15, f, periph)

#define PC15H_SQI0_CS1 MCHP_PINMUX(c, 15, h, periph)

#define PC15I_SDMMC0_SDCD MCHP_PINMUX(c, 15, i, periph)

#define PC17_GPIO MCHP_PINMUX(c, 17, gpio, gpio)

#define PC17A_EIC_EXTINT1 MCHP_PINMUX(c, 17, a, periph)

#define PC17D_SERCOM1_PAD3 MCHP_PINMUX(c, 17, d, periph)

#define PC17G_BSDAP_TDI MCHP_PINMUX(c, 17, g, periph)

#define PC17K_ETH_TSUCOMP MCHP_PINMUX(c, 17, k, periph)

#define PC18_GPIO MCHP_PINMUX(c, 18, gpio, gpio)

#define PC18A_EIC_EXTINT2 MCHP_PINMUX(c, 18, a, periph)

#define PC18D_SERCOM1_PAD2 MCHP_PINMUX(c, 18, d, periph)

#define PC18G_BSDAP_TMS_SWDIO MCHP_PINMUX(c, 18, g, periph)

#define PC19_GPIO MCHP_PINMUX(c, 19, gpio, gpio)

#define PC19A_EIC_EXTINT3 MCHP_PINMUX(c, 19, a, periph)

#define PC19D_SERCOM1_PAD1 MCHP_PINMUX(c, 19, d, periph)

#define PC19G_BSDAP_TDO MCHP_PINMUX(c, 19, g, periph)

#define PC19H_CAN0_RX MCHP_PINMUX(c, 19, h, periph)

#define PC19M_GCLK_IO1 MCHP_PINMUX(c, 19, m, periph)

#define PC20_GPIO MCHP_PINMUX(c, 20, gpio, gpio)

#define PC20A_EIC_NMI MCHP_PINMUX(c, 20, a, periph)

#define PC20D_SERCOM1_PAD0 MCHP_PINMUX(c, 20, d, periph)

#define PC20F_TCC9_WO5 MCHP_PINMUX(c, 20, f, periph)

#define PC20G_BSDAP_TCK_SWCLK MCHP_PINMUX(c, 20, g, periph)

#define PC20H_CAN0_TX MCHP_PINMUX(c, 20, h, periph)

#define PC20M_GCLK_IO0 MCHP_PINMUX(c, 20, m, periph)

#define PC21_GPIO MCHP_PINMUX(c, 21, gpio, gpio)

#define PC21A_EIC_EXTINT5 MCHP_PINMUX(c, 21, a, periph)

#define PC21D_SERCOM4_PAD0 MCHP_PINMUX(c, 21, d, periph)

#define PC21F_TCC6_WO0 MCHP_PINMUX(c, 21, f, periph)

#define PC22_GPIO MCHP_PINMUX(c, 22, gpio, gpio)

#define PC22A_EIC_EXTINT6 MCHP_PINMUX(c, 22, a, periph)

#define PC22D_SERCOM4_PAD1 MCHP_PINMUX(c, 22, d, periph)

#define PC22F_TCC6_WO1 MCHP_PINMUX(c, 22, f, periph)

#define PC23_GPIO MCHP_PINMUX(c, 23, gpio, gpio)

#define PC23A_EIC_EXTINT7 MCHP_PINMUX(c, 23, a, periph)

#define PC23D_SERCOM4_PAD2 MCHP_PINMUX(c, 23, d, periph)

#define PC23F_TCC5_WO0 MCHP_PINMUX(c, 23, f, periph)

#define PC24_GPIO MCHP_PINMUX(c, 24, gpio, gpio)

#define PC24A_EIC_EXTINT8 MCHP_PINMUX(c, 24, a, periph)

#define PC24D_SERCOM4_PAD3 MCHP_PINMUX(c, 24, d, periph)

#define PC24F_TCC5_WO1 MCHP_PINMUX(c, 24, f, periph)

#define PC25_GPIO MCHP_PINMUX(c, 25, gpio, gpio)

#define PC25A_EIC_EXTINT9 MCHP_PINMUX(c, 25, a, periph)

#define PC25D_SERCOM5_PAD0 MCHP_PINMUX(c, 25, d, periph)

#define PC25H_CAN2_RX MCHP_PINMUX(c, 25, h, periph)

#define PC26_GPIO MCHP_PINMUX(c, 26, gpio, gpio)

#define PC26A_EIC_EXTINT10 MCHP_PINMUX(c, 26, a, periph)

#define PC26D_SERCOM5_PAD1 MCHP_PINMUX(c, 26, d, periph)

#define PC26H_CAN2_TX MCHP_PINMUX(c, 26, h, periph)

#define PC27_GPIO MCHP_PINMUX(c, 27, gpio, gpio)

#define PC27A_EIC_EXTINT11 MCHP_PINMUX(c, 27, a, periph)

#define PC27D_SERCOM5_PAD2 MCHP_PINMUX(c, 27, d, periph)

#define PC28_GPIO MCHP_PINMUX(c, 28, gpio, gpio)

#define PC28A_EIC_EXTINT12 MCHP_PINMUX(c, 28, a, periph)

#define PC28D_SERCOM5_PAD3 MCHP_PINMUX(c, 28, d, periph)

#define PC29_GPIO MCHP_PINMUX(c, 29, gpio, gpio)

#define PC29A_EIC_EXTINT13 MCHP_PINMUX(c, 29, a, periph)

#define PC29F_TCC4_WO0 MCHP_PINMUX(c, 29, f, periph)

#define PC29H_CAN3_RX MCHP_PINMUX(c, 29, h, periph)

#define PD0_GPIO MCHP_PINMUX(d, 0, gpio, gpio)

#define PD0A_EIC_EXTINT0 MCHP_PINMUX(d, 0, a, periph)

#define PD0M_GCLK_IO2 MCHP_PINMUX(d, 0, m, periph)

#define PD1_GPIO MCHP_PINMUX(d, 1, gpio, gpio)

#define PD1A_EIC_EXTINT1 MCHP_PINMUX(d, 1, a, periph)

#define PD1M_GCLK_IO3 MCHP_PINMUX(d, 1, m, periph)

#define PD2_GPIO MCHP_PINMUX(d, 2, gpio, gpio)

#define PD2A_EIC_EXTINT2 MCHP_PINMUX(d, 2, a, periph)

#define PD2F_TCC9_WO4 MCHP_PINMUX(d, 2, f, periph)

#define PD2J_SPI_IXS0_FSYNC MCHP_PINMUX(d, 2, j, periph)

#define PD2K_ETH_GTXER MCHP_PINMUX(d, 2, k, periph)

#define PD3_GPIO MCHP_PINMUX(d, 3, gpio, gpio)

#define PD3A_EIC_EXTINT3 MCHP_PINMUX(d, 3, a, periph)

#define PD3D_SERCOM3_PAD0 MCHP_PINMUX(d, 3, d, periph)

#define PD3F_TCC9_WO3 MCHP_PINMUX(d, 3, f, periph)

#define PD3J_SPI_IXS0_SDI MCHP_PINMUX(d, 3, j, periph)

#define PD3K_ETH_GTX3 MCHP_PINMUX(d, 3, k, periph)

#define PD4_GPIO MCHP_PINMUX(d, 4, gpio, gpio)

#define PD4A_EIC_EXTINT4 MCHP_PINMUX(d, 4, a, periph)

#define PD4D_SERCOM3_PAD1 MCHP_PINMUX(d, 4, d, periph)

#define PD4F_TCC9_WO0 MCHP_PINMUX(d, 4, f, periph)

#define PD4J_SPI_IXS0_SCK MCHP_PINMUX(d, 4, j, periph)

#define PD4K_ETH_GTX2 MCHP_PINMUX(d, 4, k, periph)

#define PD5_GPIO MCHP_PINMUX(d, 5, gpio, gpio)

#define PD5A_EIC_EXTINT5 MCHP_PINMUX(d, 5, a, periph)

#define PD5D_SERCOM3_PAD2 MCHP_PINMUX(d, 5, d, periph)

#define PD5F_TCC9_WO1 MCHP_PINMUX(d, 5, f, periph)

#define PD5J_SPI_IXS0_SDO MCHP_PINMUX(d, 5, j, periph)

#define PD5K_ETH_TXCK MCHP_PINMUX(d, 5, k, periph)

#define PD5L_ETH_GTXCK MCHP_PINMUX(d, 5, l, periph)

#define PD6_GPIO MCHP_PINMUX(d, 6, gpio, gpio)

#define PD6A_EIC_EXTINT6 MCHP_PINMUX(d, 6, a, periph)

#define PD6D_SERCOM3_PAD3 MCHP_PINMUX(d, 6, d, periph)

#define PD6F_TCC9_WO2 MCHP_PINMUX(d, 6, f, periph)

#define PD6J_SPI_IXS0_MCLK0 MCHP_PINMUX(d, 6, j, periph)

#define PD6K_ETH_GRX3 MCHP_PINMUX(d, 6, k, periph)

#define PD7_GPIO MCHP_PINMUX(d, 7, gpio, gpio)

#define PD7A_EIC_EXTINT7 MCHP_PINMUX(d, 7, a, periph)

#define PD7F_TCC7_WO1 MCHP_PINMUX(d, 7, f, periph)

#define PD7G_MLB_MLBC MCHP_PINMUX(d, 7, g, periph)

#define PD7K_ETH_GRX2 MCHP_PINMUX(d, 7, k, periph)

#define PD8_GPIO MCHP_PINMUX(d, 8, gpio, gpio)

#define PD8A_EIC_EXTINT8 MCHP_PINMUX(d, 8, a, periph)

#define PD8F_TCC7_WO0 MCHP_PINMUX(d, 8, f, periph)

#define PD8G_MLB_MLBS MCHP_PINMUX(d, 8, g, periph)

#define PD8H_CAN1_RX MCHP_PINMUX(d, 8, h, periph)

#define PD8K_ETH_GCOL MCHP_PINMUX(d, 8, k, periph)

#define PD9_GPIO MCHP_PINMUX(d, 9, gpio, gpio)

#define PD9A_EIC_EXTINT9 MCHP_PINMUX(d, 9, a, periph)

#define PD9G_MLB_MLBD MCHP_PINMUX(d, 9, g, periph)

#define PD9H_CAN1_TX MCHP_PINMUX(d, 9, h, periph)

#define PD9K_ETH_GCRS MCHP_PINMUX(d, 9, k, periph)

#define PD10_GPIO MCHP_PINMUX(d, 10, gpio, gpio)

#define PD10A_EIC_EXTINT10 MCHP_PINMUX(d, 10, a, periph)

#define PD10F_TCC2_WO0 MCHP_PINMUX(d, 10, f, periph)

#define PD10K_ETH_GRX1 MCHP_PINMUX(d, 10, k, periph)

#define PD11_GPIO MCHP_PINMUX(d, 11, gpio, gpio)

#define PD11A_EIC_EXTINT11 MCHP_PINMUX(d, 11, a, periph)

#define PD11D_SERCOM2_PAD0 MCHP_PINMUX(d, 11, d, periph)

#define PD11F_TCC2_WO1 MCHP_PINMUX(d, 11, f, periph)

#define PD11K_ETH_GRX0 MCHP_PINMUX(d, 11, k, periph)

#define PD12_GPIO MCHP_PINMUX(d, 12, gpio, gpio)

#define PD12A_EIC_EXTINT12 MCHP_PINMUX(d, 12, a, periph)

#define PD12D_SERCOM2_PAD1 MCHP_PINMUX(d, 12, d, periph)

#define PD12F_TCC2_WO2 MCHP_PINMUX(d, 12, f, periph)

#define PD12K_ETH_GREFCK MCHP_PINMUX(d, 12, k, periph)

#define PD12L_ETH_GREFCK MCHP_PINMUX(d, 12, l, periph)

#define PD13_GPIO MCHP_PINMUX(d, 13, gpio, gpio)

#define PD13A_EIC_EXTINT14 MCHP_PINMUX(d, 13, a, periph)

#define PD13F_TCC4_WO1 MCHP_PINMUX(d, 13, f, periph)

#define PD13H_CAN3_TX MCHP_PINMUX(d, 13, h, periph)

#define PD14_GPIO MCHP_PINMUX(d, 14, gpio, gpio)

#define PD14A_EIC_EXTINT15 MCHP_PINMUX(d, 14, a, periph)

#define PD14K_ETH_GTX7 MCHP_PINMUX(d, 14, k, periph)

#define PD15_GPIO MCHP_PINMUX(d, 15, gpio, gpio)

#define PD15A_EIC_EXTINT0 MCHP_PINMUX(d, 15, a, periph)

#define PD15K_ETH_GTX6 MCHP_PINMUX(d, 15, k, periph)

#define PD16_GPIO MCHP_PINMUX(d, 16, gpio, gpio)

#define PD16A_EIC_EXTINT1 MCHP_PINMUX(d, 16, a, periph)

#define PD16K_ETH_GTX5 MCHP_PINMUX(d, 16, k, periph)

#define PD17_GPIO MCHP_PINMUX(d, 17, gpio, gpio)

#define PD17A_EIC_EXTINT2 MCHP_PINMUX(d, 17, a, periph)

#define PD17K_ETH_GTX4 MCHP_PINMUX(d, 17, k, periph)

#define PD18_GPIO MCHP_PINMUX(d, 18, gpio, gpio)

#define PD18A_EIC_EXTINT3 MCHP_PINMUX(d, 18, a, periph)

#define PD18K_ETH_GRX7 MCHP_PINMUX(d, 18, k, periph)

#define PD18M_GCLK_IO4 MCHP_PINMUX(d, 18, m, periph)

#define PD19_GPIO MCHP_PINMUX(d, 19, gpio, gpio)

#define PD19A_EIC_EXTINT4 MCHP_PINMUX(d, 19, a, periph)

#define PD19K_ETH_GRX6 MCHP_PINMUX(d, 19, k, periph)

#define PD19M_GCLK_IO5 MCHP_PINMUX(d, 19, m, periph)

#define PD20_GPIO MCHP_PINMUX(d, 20, gpio, gpio)

#define PD20A_EIC_EXTINT5 MCHP_PINMUX(d, 20, a, periph)

#define PD20K_ETH_GRX4 MCHP_PINMUX(d, 20, k, periph)

#define PD20M_GCLK_IO6 MCHP_PINMUX(d, 20, m, periph)

#define PD21_GPIO MCHP_PINMUX(d, 21, gpio, gpio)

#define PD21A_EIC_EXTINT6 MCHP_PINMUX(d, 21, a, periph)

#define PD21K_ETH_GRX5 MCHP_PINMUX(d, 21, k, periph)

#define PD21M_GCLK_IO7 MCHP_PINMUX(d, 21, m, periph)

#endif /* MICROCHIP_PIC32CZ2051CA80144_PINCTRL_H_ */
