/*
 * Copyright (c) 2025 Microchip Technology Inc.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Autogenerated file
 */

#ifndef MICROCHIP_PIC32CZ8110CA80208_PINCTRL_H_
#define MICROCHIP_PIC32CZ8110CA80208_PINCTRL_H_

#include <dt-bindings/pic32c/pic32cz_ca/common/mchp_pinctrl_pinmux_pic32c.h>

#define PA0_GPIO MCHP_PINMUX(a, 0, gpio, gpio)

#define PA0A_EIC_EXTINT0 MCHP_PINMUX(a, 0, a, periph)

#define PA0K_ETH_GTX1 MCHP_PINMUX(a, 0, k, periph)

#define PA1_GPIO MCHP_PINMUX(a, 1, gpio, gpio)

#define PA1A_EIC_EXTINT1 MCHP_PINMUX(a, 1, a, periph)

#define PA1K_ETH_GTX0 MCHP_PINMUX(a, 1, k, periph)

#define PA2_GPIO MCHP_PINMUX(a, 2, gpio, gpio)

#define PA2A_EIC_EXTINT2 MCHP_PINMUX(a, 2, a, periph)

#define PA2F_TCC2_WO5 MCHP_PINMUX(a, 2, f, periph)

#define PA2K_ETH_GTXEN MCHP_PINMUX(a, 2, k, periph)

#define PA3_GPIO MCHP_PINMUX(a, 3, gpio, gpio)

#define PA3A_EIC_EXTINT3 MCHP_PINMUX(a, 3, a, periph)

#define PA3D_SERCOM2_PAD3 MCHP_PINMUX(a, 3, d, periph)

#define PA3F_TCC2_WO4 MCHP_PINMUX(a, 3, f, periph)

#define PA3K_ETH_GMDC MCHP_PINMUX(a, 3, k, periph)

#define PA4_GPIO MCHP_PINMUX(a, 4, gpio, gpio)

#define PA4A_EIC_EXTINT4 MCHP_PINMUX(a, 4, a, periph)

#define PA4D_SERCOM2_PAD2 MCHP_PINMUX(a, 4, d, periph)

#define PA4F_TCC2_WO3 MCHP_PINMUX(a, 4, f, periph)

#define PA4K_ETH_GMDIO MCHP_PINMUX(a, 4, k, periph)

#define PA5_GPIO MCHP_PINMUX(a, 5, gpio, gpio)

#define PA5A_EIC_EXTINT4 MCHP_PINMUX(a, 5, a, periph)

#define PA5F_TCC3_WO0 MCHP_PINMUX(a, 5, f, periph)

#define PA5K_ETH_GRXDV MCHP_PINMUX(a, 5, k, periph)

#define PA6_GPIO MCHP_PINMUX(a, 6, gpio, gpio)

#define PA6A_EIC_EXTINT6 MCHP_PINMUX(a, 6, a, periph)

#define PA6F_TCC3_WO1 MCHP_PINMUX(a, 6, f, periph)

#define PA6K_ETH_GRXER MCHP_PINMUX(a, 6, k, periph)

#define PA7_GPIO MCHP_PINMUX(a, 7, gpio, gpio)

#define PA7A_EIC_EXTINT7 MCHP_PINMUX(a, 7, a, periph)

#define PA7B_ADC3_AIN3 MCHP_PINMUX(a, 7, b, periph)

#define PA8_GPIO MCHP_PINMUX(a, 8, gpio, gpio)

#define PA8A_EIC_EXTINT8 MCHP_PINMUX(a, 8, a, periph)

#define PA8B_ADC3_AIN2 MCHP_PINMUX(a, 8, b, periph)

#define PA9_GPIO MCHP_PINMUX(a, 9, gpio, gpio)

#define PA9A_EIC_EXTINT9 MCHP_PINMUX(a, 9, a, periph)

#define PA9B_ADC3_AIN1 MCHP_PINMUX(a, 9, b, periph)

#define PA10_GPIO MCHP_PINMUX(a, 10, gpio, gpio)

#define PA10A_EIC_EXTINT10 MCHP_PINMUX(a, 10, a, periph)

#define PA10B_ADC3_AIN0 MCHP_PINMUX(a, 10, b, periph)

#define PA11_GPIO MCHP_PINMUX(a, 11, gpio, gpio)

#define PA11A_EIC_EXTINT11 MCHP_PINMUX(a, 11, a, periph)

#define PA11B_ADC2_AIN3 MCHP_PINMUX(a, 11, b, periph)

#define PA12_GPIO MCHP_PINMUX(a, 12, gpio, gpio)

#define PA12A_EIC_EXTINT12 MCHP_PINMUX(a, 12, a, periph)

#define PA12B_ADC2_AIN2 MCHP_PINMUX(a, 12, b, periph)

#define PA13_GPIO MCHP_PINMUX(a, 13, gpio, gpio)

#define PA13A_EIC_EXTINT13 MCHP_PINMUX(a, 13, a, periph)

#define PA13B_ADC2_AIN1 MCHP_PINMUX(a, 13, b, periph)

#define PA14_GPIO MCHP_PINMUX(a, 14, gpio, gpio)

#define PA14A_EIC_EXTINT14 MCHP_PINMUX(a, 14, a, periph)

#define PA14B_ADC2_AIN0 MCHP_PINMUX(a, 14, b, periph)

#define PA15_GPIO MCHP_PINMUX(a, 15, gpio, gpio)

#define PA15A_EIC_EXTINT15 MCHP_PINMUX(a, 15, a, periph)

#define PA15B_ADC1_AIN3 MCHP_PINMUX(a, 15, b, periph)

#define PA16_GPIO MCHP_PINMUX(a, 16, gpio, gpio)

#define PA16A_EIC_EXTINT0 MCHP_PINMUX(a, 16, a, periph)

#define PA16B_ADC1_AIN2 MCHP_PINMUX(a, 16, b, periph)

#define PA17_GPIO MCHP_PINMUX(a, 17, gpio, gpio)

#define PA17A_EIC_EXTINT1 MCHP_PINMUX(a, 17, a, periph)

#define PA17B_ADC1_AIN1 MCHP_PINMUX(a, 17, b, periph)

#define PA18_GPIO MCHP_PINMUX(a, 18, gpio, gpio)

#define PA18A_EIC_EXTINT2 MCHP_PINMUX(a, 18, a, periph)

#define PA18B_ADC1_AIN0 MCHP_PINMUX(a, 18, b, periph)

#define PA19_GPIO MCHP_PINMUX(a, 19, gpio, gpio)

#define PA19A_EIC_EXTINT3 MCHP_PINMUX(a, 19, a, periph)

#define PA19B_AC_AIN3 MCHP_PINMUX(a, 19, b, periph)

#define PA19B_ADC0_AIN5 MCHP_PINMUX(a, 19, b, periph)

#define PA20_GPIO MCHP_PINMUX(a, 20, gpio, gpio)

#define PA20A_EIC_EXTINT4 MCHP_PINMUX(a, 20, a, periph)

#define PA20B_AC_AIN2 MCHP_PINMUX(a, 20, b, periph)

#define PA20B_ADC0_AIN4 MCHP_PINMUX(a, 20, b, periph)

#define PA21_GPIO MCHP_PINMUX(a, 21, gpio, gpio)

#define PA21A_EIC_EXTINT5 MCHP_PINMUX(a, 21, a, periph)

#define PA21F_TCC8_WO0 MCHP_PINMUX(a, 21, f, periph)

#define PA21H_CAN5_TX MCHP_PINMUX(a, 21, h, periph)

#define PA21K_ETH_TXCK MCHP_PINMUX(a, 21, k, periph)

#define PA22_GPIO MCHP_PINMUX(a, 22, gpio, gpio)

#define PA22A_EIC_EXTINT6 MCHP_PINMUX(a, 22, a, periph)

#define PA22F_TCC7_WO0 MCHP_PINMUX(a, 22, f, periph)

#define PA22K_ETH_TSUCOMP MCHP_PINMUX(a, 22, k, periph)

#define PA23_GPIO MCHP_PINMUX(a, 23, gpio, gpio)

#define PA23A_EIC_EXTINT7 MCHP_PINMUX(a, 23, a, periph)

#define PA23F_TCC7_WO1 MCHP_PINMUX(a, 23, f, periph)

#define PA24_GPIO MCHP_PINMUX(a, 24, gpio, gpio)

#define PA24A_EIC_EXTINT8 MCHP_PINMUX(a, 24, a, periph)

#define PA24B_ADC3_AIN5 MCHP_PINMUX(a, 24, b, periph)

#define PA25_GPIO MCHP_PINMUX(a, 25, gpio, gpio)

#define PA25A_EIC_EXTINT9 MCHP_PINMUX(a, 25, a, periph)

#define PA25B_ADC3_AIN4 MCHP_PINMUX(a, 25, b, periph)

#define PA26_GPIO MCHP_PINMUX(a, 26, gpio, gpio)

#define PA26A_EIC_EXTINT10 MCHP_PINMUX(a, 26, a, periph)

#define PA26B_ADC2_AIN5 MCHP_PINMUX(a, 26, b, periph)

#define PA27_GPIO MCHP_PINMUX(a, 27, gpio, gpio)

#define PA27A_EIC_EXTINT11 MCHP_PINMUX(a, 27, a, periph)

#define PA27B_ADC2_AIN4 MCHP_PINMUX(a, 27, b, periph)

#define PA28_GPIO MCHP_PINMUX(a, 28, gpio, gpio)

#define PA28A_EIC_EXTINT12 MCHP_PINMUX(a, 28, a, periph)

#define PA28B_ADC1_AIN5 MCHP_PINMUX(a, 28, b, periph)

#define PA29_GPIO MCHP_PINMUX(a, 29, gpio, gpio)

#define PA29A_EIC_EXTINT13 MCHP_PINMUX(a, 29, a, periph)

#define PA29B_ADC1_AIN4 MCHP_PINMUX(a, 29, b, periph)

#define PA30_GPIO MCHP_PINMUX(a, 30, gpio, gpio)

#define PA30A_EIC_EXTINT14 MCHP_PINMUX(a, 30, a, periph)

#define PA30H_CAN4_RX MCHP_PINMUX(a, 30, h, periph)

#define PA30J_SPI_IXS1_FSYNC MCHP_PINMUX(a, 30, j, periph)

#define PA31_GPIO MCHP_PINMUX(a, 31, gpio, gpio)

#define PA31A_EIC_EXTINT15 MCHP_PINMUX(a, 31, a, periph)

#define PA31H_CAN4_TX MCHP_PINMUX(a, 31, h, periph)

#define PA31J_SPI_IXS1_MCLK1 MCHP_PINMUX(a, 31, j, periph)

#define PB0_GPIO MCHP_PINMUX(b, 0, gpio, gpio)

#define PB0A_EIC_EXTINT0 MCHP_PINMUX(b, 0, a, periph)

#define PB0B_AC_AIN1 MCHP_PINMUX(b, 0, b, periph)

#define PB0B_ADC0_AIN3 MCHP_PINMUX(b, 0, b, periph)

#define PB1_GPIO MCHP_PINMUX(b, 1, gpio, gpio)

#define PB1A_EIC_EXTINT1 MCHP_PINMUX(b, 1, a, periph)

#define PB1B_AC_AIN0 MCHP_PINMUX(b, 1, b, periph)

#define PB1B_ADC0_AIN2 MCHP_PINMUX(b, 1, b, periph)

#define PB2_GPIO MCHP_PINMUX(b, 2, gpio, gpio)

#define PB2A_EIC_EXTINT2 MCHP_PINMUX(b, 2, a, periph)

#define PB2B_ADC0_AIN1 MCHP_PINMUX(b, 2, b, periph)

#define PB3_GPIO MCHP_PINMUX(b, 3, gpio, gpio)

#define PB3A_EIC_EXTINT3 MCHP_PINMUX(b, 3, a, periph)

#define PB3B_ADC0_AIN0 MCHP_PINMUX(b, 3, b, periph)

#define PB4_GPIO MCHP_PINMUX(b, 4, gpio, gpio)

#define PB4A_EIC_EXTINT4 MCHP_PINMUX(b, 4, a, periph)

#define PB5_GPIO MCHP_PINMUX(b, 5, gpio, gpio)

#define PB5A_EIC_EXTINT5 MCHP_PINMUX(b, 5, a, periph)

#define PB6_GPIO MCHP_PINMUX(b, 6, gpio, gpio)

#define PB6A_EIC_EXTINT6 MCHP_PINMUX(b, 6, a, periph)

#define PB6P_PTC_DRV11 MCHP_PINMUX(b, 6, p, periph)

#define PB7_GPIO MCHP_PINMUX(b, 7, gpio, gpio)

#define PB7A_EIC_EXTINT7 MCHP_PINMUX(b, 7, a, periph)

#define PB7P_PTC_DRV10 MCHP_PINMUX(b, 7, p, periph)

#define PB8_GPIO MCHP_PINMUX(b, 8, gpio, gpio)

#define PB8A_EIC_EXTINT8 MCHP_PINMUX(b, 8, a, periph)

#define PB8P_PTC_DRV9 MCHP_PINMUX(b, 8, p, periph)

#define PB9_GPIO MCHP_PINMUX(b, 9, gpio, gpio)

#define PB9A_EIC_EXTINT9 MCHP_PINMUX(b, 9, a, periph)

#define PB9P_PTC_DRV8 MCHP_PINMUX(b, 9, p, periph)

#define PB10_GPIO MCHP_PINMUX(b, 10, gpio, gpio)

#define PB10A_EIC_EXTINT10 MCHP_PINMUX(b, 10, a, periph)

#define PB10F_TCC1_WO0 MCHP_PINMUX(b, 10, f, periph)

#define PB10P_PTC_DRV7 MCHP_PINMUX(b, 10, p, periph)

#define PB11_GPIO MCHP_PINMUX(b, 11, gpio, gpio)

#define PB11A_EIC_EXTINT11 MCHP_PINMUX(b, 11, a, periph)

#define PB11F_TCC1_WO1 MCHP_PINMUX(b, 11, f, periph)

#define PB11P_PTC_DRV6 MCHP_PINMUX(b, 11, p, periph)

#define PB12_GPIO MCHP_PINMUX(b, 12, gpio, gpio)

#define PB12A_EIC_EXTINT12 MCHP_PINMUX(b, 12, a, periph)

#define PB12F_TCC1_WO2 MCHP_PINMUX(b, 12, f, periph)

#define PB12P_PTC_DRV5 MCHP_PINMUX(b, 12, p, periph)

#define PB13_GPIO MCHP_PINMUX(b, 13, gpio, gpio)

#define PB13A_EIC_EXTINT13 MCHP_PINMUX(b, 13, a, periph)

#define PB13F_TCC1_WO3 MCHP_PINMUX(b, 13, f, periph)

#define PB13P_PTC_DRV4 MCHP_PINMUX(b, 13, p, periph)

#define PB14_GPIO MCHP_PINMUX(b, 14, gpio, gpio)

#define PB14A_EIC_EXTINT14 MCHP_PINMUX(b, 14, a, periph)

#define PB14F_TCC1_WO4 MCHP_PINMUX(b, 14, f, periph)

#define PB14P_PTC_DRV3 MCHP_PINMUX(b, 14, p, periph)

#define PB15_GPIO MCHP_PINMUX(b, 15, gpio, gpio)

#define PB15A_EIC_EXTINT15 MCHP_PINMUX(b, 15, a, periph)

#define PB15F_TCC1_WO5 MCHP_PINMUX(b, 15, f, periph)

#define PB15P_PTC_DRV2 MCHP_PINMUX(b, 15, p, periph)

#define PB16_GPIO MCHP_PINMUX(b, 16, gpio, gpio)

#define PB16A_EIC_EXTINT0 MCHP_PINMUX(b, 16, a, periph)

#define PB16F_TCC1_WO6 MCHP_PINMUX(b, 16, f, periph)

#define PB16P_PTC_DRV1 MCHP_PINMUX(b, 16, p, periph)

#define PB17_GPIO MCHP_PINMUX(b, 17, gpio, gpio)

#define PB17A_EIC_EXTINT1 MCHP_PINMUX(b, 17, a, periph)

#define PB17F_TCC1_WO7 MCHP_PINMUX(b, 17, f, periph)

#define PB17P_PTC_DRV0 MCHP_PINMUX(b, 17, p, periph)

#define PB18_GPIO MCHP_PINMUX(b, 18, gpio, gpio)

#define PB18A_EIC_EXTINT2 MCHP_PINMUX(b, 18, a, periph)

#define PB18B_ADC0_AIN6 MCHP_PINMUX(b, 18, b, periph)

#define PB19_GPIO MCHP_PINMUX(b, 19, gpio, gpio)

#define PB19A_EIC_EXTINT3 MCHP_PINMUX(b, 19, a, periph)

#define PB19B_ADC0_AIN7 MCHP_PINMUX(b, 19, b, periph)

#define PB20_GPIO MCHP_PINMUX(b, 20, gpio, gpio)

#define PB20A_EIC_EXTINT4 MCHP_PINMUX(b, 20, a, periph)

#define PB20B_ADC0_AIN8 MCHP_PINMUX(b, 20, b, periph)

#define PB21_GPIO MCHP_PINMUX(b, 21, gpio, gpio)

#define PB21A_EIC_EXTINT5 MCHP_PINMUX(b, 21, a, periph)

#define PB21P_PTC_DRV17 MCHP_PINMUX(b, 21, p, periph)

#define PB22_GPIO MCHP_PINMUX(b, 22, gpio, gpio)

#define PB22A_EIC_EXTINT6 MCHP_PINMUX(b, 22, a, periph)

#define PB22P_PTC_DRV16 MCHP_PINMUX(b, 22, p, periph)

#define PB23_GPIO MCHP_PINMUX(b, 23, gpio, gpio)

#define PB23A_EIC_EXTINT7 MCHP_PINMUX(b, 23, a, periph)

#define PB23P_PTC_DRV15 MCHP_PINMUX(b, 23, p, periph)

#define PB24_GPIO MCHP_PINMUX(b, 24, gpio, gpio)

#define PB24A_EIC_EXTINT8 MCHP_PINMUX(b, 24, a, periph)

#define PB24P_PTC_DRV14 MCHP_PINMUX(b, 24, p, periph)

#define PB25_GPIO MCHP_PINMUX(b, 25, gpio, gpio)

#define PB25A_EIC_EXTINT9 MCHP_PINMUX(b, 25, a, periph)

#define PB25P_PTC_DRV13 MCHP_PINMUX(b, 25, p, periph)

#define PB26_GPIO MCHP_PINMUX(b, 26, gpio, gpio)

#define PB26A_EIC_EXTINT10 MCHP_PINMUX(b, 26, a, periph)

#define PB26P_PTC_DRV12 MCHP_PINMUX(b, 26, p, periph)

#define PB27_GPIO MCHP_PINMUX(b, 27, gpio, gpio)

#define PB27A_EIC_EXTINT11 MCHP_PINMUX(b, 27, a, periph)

#define PB27P_PTC_DRV23 MCHP_PINMUX(b, 27, p, periph)

#define PB28_GPIO MCHP_PINMUX(b, 28, gpio, gpio)

#define PB28A_EIC_EXTINT12 MCHP_PINMUX(b, 28, a, periph)

#define PB28P_PTC_DRV22 MCHP_PINMUX(b, 28, p, periph)

#define PB29_GPIO MCHP_PINMUX(b, 29, gpio, gpio)

#define PB29A_EIC_EXTINT13 MCHP_PINMUX(b, 29, a, periph)

#define PB29P_PTC_DRV20 MCHP_PINMUX(b, 29, p, periph)

#define PB30_GPIO MCHP_PINMUX(b, 30, gpio, gpio)

#define PB30A_EIC_EXTINT14 MCHP_PINMUX(b, 30, a, periph)

#define PB30P_PTC_DRV19 MCHP_PINMUX(b, 30, p, periph)

#define PB31_GPIO MCHP_PINMUX(b, 31, gpio, gpio)

#define PB31A_EIC_EXTINT15 MCHP_PINMUX(b, 31, a, periph)

#define PB31P_PTC_DRV18 MCHP_PINMUX(b, 31, p, periph)

#define PC0_GPIO MCHP_PINMUX(c, 0, gpio, gpio)

#define PC0A_EIC_EXTINT0 MCHP_PINMUX(c, 0, a, periph)

#define PC0D_SERCOM0_PAD0 MCHP_PINMUX(c, 0, d, periph)

#define PC0F_TCC0_WO0 MCHP_PINMUX(c, 0, f, periph)

#define PC0J_SPI_IXS0_FSYNC MCHP_PINMUX(c, 0, j, periph)

#define PC0M_GCLK_IO4 MCHP_PINMUX(c, 0, m, periph)

#define PC1_GPIO MCHP_PINMUX(c, 1, gpio, gpio)

#define PC1A_EIC_EXTINT1 MCHP_PINMUX(c, 1, a, periph)

#define PC1D_SERCOM0_PAD1 MCHP_PINMUX(c, 1, d, periph)

#define PC1F_TCC0_WO1 MCHP_PINMUX(c, 1, f, periph)

#define PC1J_SPI_IXS0_SCK MCHP_PINMUX(c, 1, j, periph)

#define PC1M_GCLK_IO5 MCHP_PINMUX(c, 1, m, periph)

#define PC2_GPIO MCHP_PINMUX(c, 2, gpio, gpio)

#define PC2A_EIC_EXTINT1 MCHP_PINMUX(c, 2, a, periph)

#define PC2D_SERCOM0_PAD2 MCHP_PINMUX(c, 2, d, periph)

#define PC2F_TCC0_WO2 MCHP_PINMUX(c, 2, f, periph)

#define PC2J_SPI_IXS0_SDI MCHP_PINMUX(c, 2, j, periph)

#define PC2M_GCLK_IO6 MCHP_PINMUX(c, 2, m, periph)

#define PC2P_PTC_ECI0 MCHP_PINMUX(c, 2, p, periph)

#define PC3_GPIO MCHP_PINMUX(c, 3, gpio, gpio)

#define PC3A_EIC_EXTINT3 MCHP_PINMUX(c, 3, a, periph)

#define PC3D_SERCOM0_PAD3 MCHP_PINMUX(c, 3, d, periph)

#define PC3F_TCC0_WO3 MCHP_PINMUX(c, 3, f, periph)

#define PC3J_SPI_IXS0_SDO MCHP_PINMUX(c, 3, j, periph)

#define PC3M_GCLK_IO7 MCHP_PINMUX(c, 3, m, periph)

#define PC3P_PTC_ECI1 MCHP_PINMUX(c, 3, p, periph)

#define PC4_GPIO MCHP_PINMUX(c, 4, gpio, gpio)

#define PC4A_EIC_EXTINT4 MCHP_PINMUX(c, 4, a, periph)

#define PC4D_SERCOM1_PAD0 MCHP_PINMUX(c, 4, d, periph)

#define PC4E_EBI_NWE_NWR0 MCHP_PINMUX(c, 4, e, periph)

#define PC4F_TCC0_WO4 MCHP_PINMUX(c, 4, f, periph)

#define PC4H_CAN0_RX MCHP_PINMUX(c, 4, h, periph)

#define PC4J_SPI_IXS0_MCLK0 MCHP_PINMUX(c, 4, j, periph)

#define PC5_GPIO MCHP_PINMUX(c, 5, gpio, gpio)

#define PC5A_EIC_EXTINT5 MCHP_PINMUX(c, 5, a, periph)

#define PC5D_SERCOM1_PAD1 MCHP_PINMUX(c, 5, d, periph)

#define PC5E_EBI_NRD MCHP_PINMUX(c, 5, e, periph)

#define PC5F_TCC0_WO5 MCHP_PINMUX(c, 5, f, periph)

#define PC5H_CAN0_TX MCHP_PINMUX(c, 5, h, periph)

#define PC5K_ETH_TSUCOMP MCHP_PINMUX(c, 5, k, periph)

#define PC6_GPIO MCHP_PINMUX(c, 6, gpio, gpio)

#define PC6A_EIC_EXTINT6 MCHP_PINMUX(c, 6, a, periph)

#define PC6B_AC_CMP1 MCHP_PINMUX(c, 6, b, periph)

#define PC6D_SERCOM1_PAD2 MCHP_PINMUX(c, 6, d, periph)

#define PC6E_EBI_NBS1_NWR1 MCHP_PINMUX(c, 6, e, periph)

#define PC6F_TCC0_WO6 MCHP_PINMUX(c, 6, f, periph)

#define PC6H_CAN1_RX MCHP_PINMUX(c, 6, h, periph)

#define PC7_GPIO MCHP_PINMUX(c, 7, gpio, gpio)

#define PC7A_EIC_EXTINT7 MCHP_PINMUX(c, 7, a, periph)

#define PC7B_AC_CMP0 MCHP_PINMUX(c, 7, b, periph)

#define PC7D_SERCOM1_PAD3 MCHP_PINMUX(c, 7, d, periph)

#define PC7E_EBI_NCS1 MCHP_PINMUX(c, 7, e, periph)

#define PC7F_TCC0_WO7 MCHP_PINMUX(c, 7, f, periph)

#define PC7H_CAN1_TX MCHP_PINMUX(c, 7, h, periph)

#define PC8_GPIO MCHP_PINMUX(c, 8, gpio, gpio)

#define PC8A_EIC_EXTINT8 MCHP_PINMUX(c, 8, a, periph)

#define PC8D_SERCOM2_PAD0 MCHP_PINMUX(c, 8, d, periph)

#define PC8E_EBI_NCS0 MCHP_PINMUX(c, 8, e, periph)

#define PC8F_TCC5_WO0 MCHP_PINMUX(c, 8, f, periph)

#define PC8H_SQI0_CLK MCHP_PINMUX(c, 8, h, periph)

#define PC8I_SDMMC0_SDCK MCHP_PINMUX(c, 8, i, periph)

#define PC9_GPIO MCHP_PINMUX(c, 9, gpio, gpio)

#define PC9A_EIC_EXTINT9 MCHP_PINMUX(c, 9, a, periph)

#define PC9D_SERCOM2_PAD1 MCHP_PINMUX(c, 9, d, periph)

#define PC9E_EBI_A22 MCHP_PINMUX(c, 9, e, periph)

#define PC9F_TCC5_WO1 MCHP_PINMUX(c, 9, f, periph)

#define PC9H_SQI0_DATA0 MCHP_PINMUX(c, 9, h, periph)

#define PC9I_SDMMC0_SDDAT0 MCHP_PINMUX(c, 9, i, periph)

#define PC10_GPIO MCHP_PINMUX(c, 10, gpio, gpio)

#define PC10A_EIC_EXTINT10 MCHP_PINMUX(c, 10, a, periph)

#define PC10D_SERCOM2_PAD2 MCHP_PINMUX(c, 10, d, periph)

#define PC10E_EBI_A14 MCHP_PINMUX(c, 10, e, periph)

#define PC10F_TCC6_WO0 MCHP_PINMUX(c, 10, f, periph)

#define PC10H_SQI0_DATA1 MCHP_PINMUX(c, 10, h, periph)

#define PC10I_SDMMC0_SDDAT1 MCHP_PINMUX(c, 10, i, periph)

#define PC11_GPIO MCHP_PINMUX(c, 11, gpio, gpio)

#define PC11A_EIC_EXTINT11 MCHP_PINMUX(c, 11, a, periph)

#define PC11D_SERCOM2_PAD3 MCHP_PINMUX(c, 11, d, periph)

#define PC11E_EBI_A13 MCHP_PINMUX(c, 11, e, periph)

#define PC11F_TCC6_WO1 MCHP_PINMUX(c, 11, f, periph)

#define PC11H_SQI0_DATA2 MCHP_PINMUX(c, 11, h, periph)

#define PC11I_SDMMC0_SDDAT2 MCHP_PINMUX(c, 11, i, periph)

#define PC12_GPIO MCHP_PINMUX(c, 12, gpio, gpio)

#define PC12A_EIC_EXTINT12 MCHP_PINMUX(c, 12, a, periph)

#define PC12D_SERCOM3_PAD0 MCHP_PINMUX(c, 12, d, periph)

#define PC12E_EBI_A9 MCHP_PINMUX(c, 12, e, periph)

#define PC12F_TCC4_WO0 MCHP_PINMUX(c, 12, f, periph)

#define PC12H_SQI0_DATA3 MCHP_PINMUX(c, 12, h, periph)

#define PC12I_SDMMC0_SDDAT3 MCHP_PINMUX(c, 12, i, periph)

#define PC13_GPIO MCHP_PINMUX(c, 13, gpio, gpio)

#define PC13A_EIC_EXTINT13 MCHP_PINMUX(c, 13, a, periph)

#define PC13D_SERCOM3_PAD1 MCHP_PINMUX(c, 13, d, periph)

#define PC13E_EBI_A8 MCHP_PINMUX(c, 13, e, periph)

#define PC13F_TCC4_WO1 MCHP_PINMUX(c, 13, f, periph)

#define PC13H_SQI0_CS0 MCHP_PINMUX(c, 13, h, periph)

#define PC13I_SDMMC0_SDCMD MCHP_PINMUX(c, 13, i, periph)

#define PC14_GPIO MCHP_PINMUX(c, 14, gpio, gpio)

#define PC14A_EIC_EXTINT14 MCHP_PINMUX(c, 14, a, periph)

#define PC14D_SERCOM3_PAD2 MCHP_PINMUX(c, 14, d, periph)

#define PC14E_EBI_A6 MCHP_PINMUX(c, 14, e, periph)

#define PC14F_TCC8_WO0 MCHP_PINMUX(c, 14, f, periph)

#define PC14I_SDMMC0_SDWP MCHP_PINMUX(c, 14, i, periph)

#define PC15_GPIO MCHP_PINMUX(c, 15, gpio, gpio)

#define PC15A_EIC_EXTINT15 MCHP_PINMUX(c, 15, a, periph)

#define PC15D_SERCOM3_PAD3 MCHP_PINMUX(c, 15, d, periph)

#define PC15E_EBI_A5 MCHP_PINMUX(c, 15, e, periph)

#define PC15F_TCC8_WO1 MCHP_PINMUX(c, 15, f, periph)

#define PC15H_SQI0_CS1 MCHP_PINMUX(c, 15, h, periph)

#define PC15I_SDMMC0_SDCD MCHP_PINMUX(c, 15, i, periph)

#define PC17_GPIO MCHP_PINMUX(c, 17, gpio, gpio)

#define PC17A_EIC_EXTINT1 MCHP_PINMUX(c, 17, a, periph)

#define PC17D_SERCOM1_PAD3 MCHP_PINMUX(c, 17, d, periph)

#define PC17E_EBI_A4 MCHP_PINMUX(c, 17, e, periph)

#define PC17G_BSDAP_TDI MCHP_PINMUX(c, 17, g, periph)

#define PC17K_ETH_TSUCOMP MCHP_PINMUX(c, 17, k, periph)

#define PC18_GPIO MCHP_PINMUX(c, 18, gpio, gpio)

#define PC18A_EIC_EXTINT2 MCHP_PINMUX(c, 18, a, periph)

#define PC18D_SERCOM1_PAD2 MCHP_PINMUX(c, 18, d, periph)

#define PC18E_EBI_A3 MCHP_PINMUX(c, 18, e, periph)

#define PC18G_BSDAP_TMS_SWDIO MCHP_PINMUX(c, 18, g, periph)

#define PC19_GPIO MCHP_PINMUX(c, 19, gpio, gpio)

#define PC19A_EIC_EXTINT3 MCHP_PINMUX(c, 19, a, periph)

#define PC19D_SERCOM1_PAD1 MCHP_PINMUX(c, 19, d, periph)

#define PC19E_EBI_A2 MCHP_PINMUX(c, 19, e, periph)

#define PC19G_BSDAP_TDO MCHP_PINMUX(c, 19, g, periph)

#define PC19H_CAN0_RX MCHP_PINMUX(c, 19, h, periph)

#define PC19M_GCLK_IO1 MCHP_PINMUX(c, 19, m, periph)

#define PC20_GPIO MCHP_PINMUX(c, 20, gpio, gpio)

#define PC20A_EIC_NMI MCHP_PINMUX(c, 20, a, periph)

#define PC20D_SERCOM1_PAD0 MCHP_PINMUX(c, 20, d, periph)

#define PC20E_EBI_A1 MCHP_PINMUX(c, 20, e, periph)

#define PC20F_TCC9_WO5 MCHP_PINMUX(c, 20, f, periph)

#define PC20G_BSDAP_TCK_SWCLK MCHP_PINMUX(c, 20, g, periph)

#define PC20H_CAN0_TX MCHP_PINMUX(c, 20, h, periph)

#define PC20M_GCLK_IO0 MCHP_PINMUX(c, 20, m, periph)

#define PC21_GPIO MCHP_PINMUX(c, 21, gpio, gpio)

#define PC21A_EIC_EXTINT5 MCHP_PINMUX(c, 21, a, periph)

#define PC21D_SERCOM4_PAD0 MCHP_PINMUX(c, 21, d, periph)

#define PC21E_EBI_NCS3 MCHP_PINMUX(c, 21, e, periph)

#define PC21F_TCC6_WO0 MCHP_PINMUX(c, 21, f, periph)

#define PC22_GPIO MCHP_PINMUX(c, 22, gpio, gpio)

#define PC22A_EIC_EXTINT6 MCHP_PINMUX(c, 22, a, periph)

#define PC22D_SERCOM4_PAD1 MCHP_PINMUX(c, 22, d, periph)

#define PC22E_EBI_NCS2 MCHP_PINMUX(c, 22, e, periph)

#define PC22F_TCC6_WO1 MCHP_PINMUX(c, 22, f, periph)

#define PC23_GPIO MCHP_PINMUX(c, 23, gpio, gpio)

#define PC23A_EIC_EXTINT7 MCHP_PINMUX(c, 23, a, periph)

#define PC23D_SERCOM4_PAD2 MCHP_PINMUX(c, 23, d, periph)

#define PC23E_EBI_NBS0_A0 MCHP_PINMUX(c, 23, e, periph)

#define PC23F_TCC5_WO0 MCHP_PINMUX(c, 23, f, periph)

#define PC24_GPIO MCHP_PINMUX(c, 24, gpio, gpio)

#define PC24A_EIC_EXTINT8 MCHP_PINMUX(c, 24, a, periph)

#define PC24D_SERCOM4_PAD3 MCHP_PINMUX(c, 24, d, periph)

#define PC24E_EBI_A23 MCHP_PINMUX(c, 24, e, periph)

#define PC24F_TCC5_WO1 MCHP_PINMUX(c, 24, f, periph)

#define PC25_GPIO MCHP_PINMUX(c, 25, gpio, gpio)

#define PC25A_EIC_EXTINT9 MCHP_PINMUX(c, 25, a, periph)

#define PC25D_SERCOM5_PAD0 MCHP_PINMUX(c, 25, d, periph)

#define PC25E_EBI_A21 MCHP_PINMUX(c, 25, e, periph)

#define PC25H_CAN2_RX MCHP_PINMUX(c, 25, h, periph)

#define PC26_GPIO MCHP_PINMUX(c, 26, gpio, gpio)

#define PC26A_EIC_EXTINT10 MCHP_PINMUX(c, 26, a, periph)

#define PC26D_SERCOM5_PAD1 MCHP_PINMUX(c, 26, d, periph)

#define PC26E_EBI_A18 MCHP_PINMUX(c, 26, e, periph)

#define PC26H_CAN2_TX MCHP_PINMUX(c, 26, h, periph)

#define PC27_GPIO MCHP_PINMUX(c, 27, gpio, gpio)

#define PC27A_EIC_EXTINT11 MCHP_PINMUX(c, 27, a, periph)

#define PC27D_SERCOM5_PAD2 MCHP_PINMUX(c, 27, d, periph)

#define PC27E_EBI_A12 MCHP_PINMUX(c, 27, e, periph)

#define PC27I_SDMMC1_SDWP MCHP_PINMUX(c, 27, i, periph)

#define PC28_GPIO MCHP_PINMUX(c, 28, gpio, gpio)

#define PC28A_EIC_EXTINT12 MCHP_PINMUX(c, 28, a, periph)

#define PC28D_SERCOM5_PAD3 MCHP_PINMUX(c, 28, d, periph)

#define PC28E_EBI_A10 MCHP_PINMUX(c, 28, e, periph)

#define PC28H_SQI1_CS1 MCHP_PINMUX(c, 28, h, periph)

#define PC28I_SDMMC1_SDCD MCHP_PINMUX(c, 28, i, periph)

#define PC29_GPIO MCHP_PINMUX(c, 29, gpio, gpio)

#define PC29A_EIC_EXTINT13 MCHP_PINMUX(c, 29, a, periph)

#define PC29E_EBI_A7 MCHP_PINMUX(c, 29, e, periph)

#define PC29F_TCC4_WO0 MCHP_PINMUX(c, 29, f, periph)

#define PC29H_CAN3_RX MCHP_PINMUX(c, 29, h, periph)

#define PC30_GPIO MCHP_PINMUX(c, 30, gpio, gpio)

#define PC30A_EIC_EXTINT14 MCHP_PINMUX(c, 30, a, periph)

#define PC30D_SERCOM6_PAD0 MCHP_PINMUX(c, 30, d, periph)

#define PC30E_EBI_A20 MCHP_PINMUX(c, 30, e, periph)

#define PC30H_SQI1_CLK MCHP_PINMUX(c, 30, h, periph)

#define PC30I_SDMMC1_SDCK MCHP_PINMUX(c, 30, i, periph)

#define PC31_GPIO MCHP_PINMUX(c, 31, gpio, gpio)

#define PC31A_EIC_EXTINT15 MCHP_PINMUX(c, 31, a, periph)

#define PC31D_SERCOM6_PAD1 MCHP_PINMUX(c, 31, d, periph)

#define PC31E_EBI_A19 MCHP_PINMUX(c, 31, e, periph)

#define PC31H_SQI1_DATA0 MCHP_PINMUX(c, 31, h, periph)

#define PC31I_SDMMC1_SDDAT0 MCHP_PINMUX(c, 31, i, periph)

#define PD0_GPIO MCHP_PINMUX(d, 0, gpio, gpio)

#define PD0A_EIC_EXTINT0 MCHP_PINMUX(d, 0, a, periph)

#define PD0M_GCLK_IO2 MCHP_PINMUX(d, 0, m, periph)

#define PD1_GPIO MCHP_PINMUX(d, 1, gpio, gpio)

#define PD1A_EIC_EXTINT1 MCHP_PINMUX(d, 1, a, periph)

#define PD1M_GCLK_IO3 MCHP_PINMUX(d, 1, m, periph)

#define PD2_GPIO MCHP_PINMUX(d, 2, gpio, gpio)

#define PD2A_EIC_EXTINT2 MCHP_PINMUX(d, 2, a, periph)

#define PD2E_EBI_D3 MCHP_PINMUX(d, 2, e, periph)

#define PD2F_TCC9_WO4 MCHP_PINMUX(d, 2, f, periph)

#define PD2J_SPI_IXS0_FSYNC MCHP_PINMUX(d, 2, j, periph)

#define PD2K_ETH_GTXER MCHP_PINMUX(d, 2, k, periph)

#define PD3_GPIO MCHP_PINMUX(d, 3, gpio, gpio)

#define PD3A_EIC_EXTINT3 MCHP_PINMUX(d, 3, a, periph)

#define PD3D_SERCOM3_PAD0 MCHP_PINMUX(d, 3, d, periph)

#define PD3E_EBI_D5 MCHP_PINMUX(d, 3, e, periph)

#define PD3F_TCC9_WO3 MCHP_PINMUX(d, 3, f, periph)

#define PD3J_SPI_IXS0_SDI MCHP_PINMUX(d, 3, j, periph)

#define PD3K_ETH_GTX3 MCHP_PINMUX(d, 3, k, periph)

#define PD4_GPIO MCHP_PINMUX(d, 4, gpio, gpio)

#define PD4A_EIC_EXTINT4 MCHP_PINMUX(d, 4, a, periph)

#define PD4D_SERCOM3_PAD1 MCHP_PINMUX(d, 4, d, periph)

#define PD4E_EBI_D8 MCHP_PINMUX(d, 4, e, periph)

#define PD4F_TCC9_WO0 MCHP_PINMUX(d, 4, f, periph)

#define PD4J_SPI_IXS0_SCK MCHP_PINMUX(d, 4, j, periph)

#define PD4K_ETH_GTX2 MCHP_PINMUX(d, 4, k, periph)

#define PD5_GPIO MCHP_PINMUX(d, 5, gpio, gpio)

#define PD5A_EIC_EXTINT5 MCHP_PINMUX(d, 5, a, periph)

#define PD5D_SERCOM3_PAD2 MCHP_PINMUX(d, 5, d, periph)

#define PD5E_EBI_D11 MCHP_PINMUX(d, 5, e, periph)

#define PD5F_TCC9_WO1 MCHP_PINMUX(d, 5, f, periph)

#define PD5J_SPI_IXS0_SDO MCHP_PINMUX(d, 5, j, periph)

#define PD5K_ETH_TXCK MCHP_PINMUX(d, 5, k, periph)

#define PD5L_ETH_GTXCK MCHP_PINMUX(d, 5, l, periph)

#define PD6_GPIO MCHP_PINMUX(d, 6, gpio, gpio)

#define PD6A_EIC_EXTINT6 MCHP_PINMUX(d, 6, a, periph)

#define PD6D_SERCOM3_PAD3 MCHP_PINMUX(d, 6, d, periph)

#define PD6E_EBI_D12 MCHP_PINMUX(d, 6, e, periph)

#define PD6F_TCC9_WO2 MCHP_PINMUX(d, 6, f, periph)

#define PD6J_SPI_IXS0_MCLK0 MCHP_PINMUX(d, 6, j, periph)

#define PD6K_ETH_GRX3 MCHP_PINMUX(d, 6, k, periph)

#define PD7_GPIO MCHP_PINMUX(d, 7, gpio, gpio)

#define PD7A_EIC_EXTINT7 MCHP_PINMUX(d, 7, a, periph)

#define PD7E_EBI_D15 MCHP_PINMUX(d, 7, e, periph)

#define PD7F_TCC7_WO1 MCHP_PINMUX(d, 7, f, periph)

#define PD7G_MLB_MLBC MCHP_PINMUX(d, 7, g, periph)

#define PD7K_ETH_GRX2 MCHP_PINMUX(d, 7, k, periph)

#define PD8_GPIO MCHP_PINMUX(d, 8, gpio, gpio)

#define PD8A_EIC_EXTINT8 MCHP_PINMUX(d, 8, a, periph)

#define PD8E_EBI_NWAIT MCHP_PINMUX(d, 8, e, periph)

#define PD8F_TCC7_WO0 MCHP_PINMUX(d, 8, f, periph)

#define PD8G_MLB_MLBS MCHP_PINMUX(d, 8, g, periph)

#define PD8H_CAN1_RX MCHP_PINMUX(d, 8, h, periph)

#define PD8K_ETH_GCOL MCHP_PINMUX(d, 8, k, periph)

#define PD9_GPIO MCHP_PINMUX(d, 9, gpio, gpio)

#define PD9A_EIC_EXTINT9 MCHP_PINMUX(d, 9, a, periph)

#define PD9G_MLB_MLBD MCHP_PINMUX(d, 9, g, periph)

#define PD9H_CAN1_TX MCHP_PINMUX(d, 9, h, periph)

#define PD9K_ETH_GCRS MCHP_PINMUX(d, 9, k, periph)

#define PD10_GPIO MCHP_PINMUX(d, 10, gpio, gpio)

#define PD10A_EIC_EXTINT10 MCHP_PINMUX(d, 10, a, periph)

#define PD10F_TCC2_WO0 MCHP_PINMUX(d, 10, f, periph)

#define PD10K_ETH_GRX1 MCHP_PINMUX(d, 10, k, periph)

#define PD11_GPIO MCHP_PINMUX(d, 11, gpio, gpio)

#define PD11A_EIC_EXTINT11 MCHP_PINMUX(d, 11, a, periph)

#define PD11D_SERCOM2_PAD0 MCHP_PINMUX(d, 11, d, periph)

#define PD11F_TCC2_WO1 MCHP_PINMUX(d, 11, f, periph)

#define PD11K_ETH_GRX0 MCHP_PINMUX(d, 11, k, periph)

#define PD12_GPIO MCHP_PINMUX(d, 12, gpio, gpio)

#define PD12A_EIC_EXTINT12 MCHP_PINMUX(d, 12, a, periph)

#define PD12D_SERCOM2_PAD1 MCHP_PINMUX(d, 12, d, periph)

#define PD12F_TCC2_WO2 MCHP_PINMUX(d, 12, f, periph)

#define PD12K_ETH_GREFCK MCHP_PINMUX(d, 12, k, periph)

#define PD12L_ETH_GREFCK MCHP_PINMUX(d, 12, l, periph)

#define PD13_GPIO MCHP_PINMUX(d, 13, gpio, gpio)

#define PD13A_EIC_EXTINT14 MCHP_PINMUX(d, 13, a, periph)

#define PD13E_EBI_D0 MCHP_PINMUX(d, 13, e, periph)

#define PD13F_TCC4_WO1 MCHP_PINMUX(d, 13, f, periph)

#define PD13H_CAN3_TX MCHP_PINMUX(d, 13, h, periph)

#define PD14_GPIO MCHP_PINMUX(d, 14, gpio, gpio)

#define PD14A_EIC_EXTINT15 MCHP_PINMUX(d, 14, a, periph)

#define PD14D_SERCOM7_PAD0 MCHP_PINMUX(d, 14, d, periph)

#define PD14E_EBI_D2 MCHP_PINMUX(d, 14, e, periph)

#define PD14K_ETH_GTX7 MCHP_PINMUX(d, 14, k, periph)

#define PD15_GPIO MCHP_PINMUX(d, 15, gpio, gpio)

#define PD15A_EIC_EXTINT0 MCHP_PINMUX(d, 15, a, periph)

#define PD15D_SERCOM7_PAD1 MCHP_PINMUX(d, 15, d, periph)

#define PD15E_EBI_D4 MCHP_PINMUX(d, 15, e, periph)

#define PD15K_ETH_GTX6 MCHP_PINMUX(d, 15, k, periph)

#define PD16_GPIO MCHP_PINMUX(d, 16, gpio, gpio)

#define PD16A_EIC_EXTINT1 MCHP_PINMUX(d, 16, a, periph)

#define PD16D_SERCOM7_PAD2 MCHP_PINMUX(d, 16, d, periph)

#define PD16E_EBI_D6 MCHP_PINMUX(d, 16, e, periph)

#define PD16K_ETH_GTX5 MCHP_PINMUX(d, 16, k, periph)

#define PD17_GPIO MCHP_PINMUX(d, 17, gpio, gpio)

#define PD17A_EIC_EXTINT2 MCHP_PINMUX(d, 17, a, periph)

#define PD17D_SERCOM7_PAD3 MCHP_PINMUX(d, 17, d, periph)

#define PD17E_EBI_D7 MCHP_PINMUX(d, 17, e, periph)

#define PD17K_ETH_GTX4 MCHP_PINMUX(d, 17, k, periph)

#define PD18_GPIO MCHP_PINMUX(d, 18, gpio, gpio)

#define PD18A_EIC_EXTINT3 MCHP_PINMUX(d, 18, a, periph)

#define PD18E_EBI_D9 MCHP_PINMUX(d, 18, e, periph)

#define PD18K_ETH_GRX7 MCHP_PINMUX(d, 18, k, periph)

#define PD18M_GCLK_IO4 MCHP_PINMUX(d, 18, m, periph)

#define PD19_GPIO MCHP_PINMUX(d, 19, gpio, gpio)

#define PD19A_EIC_EXTINT4 MCHP_PINMUX(d, 19, a, periph)

#define PD19E_EBI_D10 MCHP_PINMUX(d, 19, e, periph)

#define PD19K_ETH_GRX6 MCHP_PINMUX(d, 19, k, periph)

#define PD19M_GCLK_IO5 MCHP_PINMUX(d, 19, m, periph)

#define PD20_GPIO MCHP_PINMUX(d, 20, gpio, gpio)

#define PD20A_EIC_EXTINT5 MCHP_PINMUX(d, 20, a, periph)

#define PD20E_EBI_D13 MCHP_PINMUX(d, 20, e, periph)

#define PD20K_ETH_GRX4 MCHP_PINMUX(d, 20, k, periph)

#define PD20M_GCLK_IO6 MCHP_PINMUX(d, 20, m, periph)

#define PD21_GPIO MCHP_PINMUX(d, 21, gpio, gpio)

#define PD21A_EIC_EXTINT6 MCHP_PINMUX(d, 21, a, periph)

#define PD21E_EBI_D14 MCHP_PINMUX(d, 21, e, periph)

#define PD21K_ETH_GRX5 MCHP_PINMUX(d, 21, k, periph)

#define PD21M_GCLK_IO7 MCHP_PINMUX(d, 21, m, periph)

#define PD23_GPIO MCHP_PINMUX(d, 23, gpio, gpio)

#define PD23A_EIC_EXTINT7 MCHP_PINMUX(d, 23, a, periph)

#define PD23E_EBI_D1 MCHP_PINMUX(d, 23, e, periph)

#define PD23F_TCC8_WO1 MCHP_PINMUX(d, 23, f, periph)

#define PD23H_CAN5_RX MCHP_PINMUX(d, 23, h, periph)

#define PD24_GPIO MCHP_PINMUX(d, 24, gpio, gpio)

#define PD24A_EIC_EXTINT8 MCHP_PINMUX(d, 24, a, periph)

#define PD24D_SERCOM8_PAD0 MCHP_PINMUX(d, 24, d, periph)

#define PD25_GPIO MCHP_PINMUX(d, 25, gpio, gpio)

#define PD25A_EIC_EXTINT9 MCHP_PINMUX(d, 25, a, periph)

#define PD25D_SERCOM8_PAD1 MCHP_PINMUX(d, 25, d, periph)

#define PD26_GPIO MCHP_PINMUX(d, 26, gpio, gpio)

#define PD26A_EIC_EXTINT10 MCHP_PINMUX(d, 26, a, periph)

#define PD26D_SERCOM8_PAD2 MCHP_PINMUX(d, 26, d, periph)

#define PD26F_TCC2_WO0 MCHP_PINMUX(d, 26, f, periph)

#define PD27_GPIO MCHP_PINMUX(d, 27, gpio, gpio)

#define PD27A_EIC_EXTINT11 MCHP_PINMUX(d, 27, a, periph)

#define PD27D_SERCOM8_PAD3 MCHP_PINMUX(d, 27, d, periph)

#define PD27F_TCC2_WO1 MCHP_PINMUX(d, 27, f, periph)

#define PD28_GPIO MCHP_PINMUX(d, 28, gpio, gpio)

#define PD28A_EIC_EXTINT12 MCHP_PINMUX(d, 28, a, periph)

#define PD28D_SERCOM9_PAD0 MCHP_PINMUX(d, 28, d, periph)

#define PD28F_TCC2_WO2 MCHP_PINMUX(d, 28, f, periph)

#define PD29_GPIO MCHP_PINMUX(d, 29, gpio, gpio)

#define PD29A_EIC_EXTINT13 MCHP_PINMUX(d, 29, a, periph)

#define PD29D_SERCOM9_PAD1 MCHP_PINMUX(d, 29, d, periph)

#define PD29F_TCC2_WO3 MCHP_PINMUX(d, 29, f, periph)

#define PE0_GPIO MCHP_PINMUX(e, 0, gpio, gpio)

#define PE0A_EIC_EXTINT0 MCHP_PINMUX(e, 0, a, periph)

#define PE0J_SPI_IXS1_SDO MCHP_PINMUX(e, 0, j, periph)

#define PE1_GPIO MCHP_PINMUX(e, 1, gpio, gpio)

#define PE1A_EIC_EXTINT1 MCHP_PINMUX(e, 1, a, periph)

#define PE1J_SPI_IXS1_SCK MCHP_PINMUX(e, 1, j, periph)

#define PE2_GPIO MCHP_PINMUX(e, 2, gpio, gpio)

#define PE2A_EIC_EXTINT2 MCHP_PINMUX(e, 2, a, periph)

#define PE2J_SPI_IXS1_SDI MCHP_PINMUX(e, 2, j, periph)

#define PE3_GPIO MCHP_PINMUX(e, 3, gpio, gpio)

#define PE3A_EIC_EXTINT3 MCHP_PINMUX(e, 3, a, periph)

#define PE3B_ADC0_AIN9 MCHP_PINMUX(e, 3, b, periph)

#define PE4_GPIO MCHP_PINMUX(e, 4, gpio, gpio)

#define PE4A_EIC_EXTINT4 MCHP_PINMUX(e, 4, a, periph)

#define PE4D_SERCOM9_PAD2 MCHP_PINMUX(e, 4, d, periph)

#define PE4F_TCC2_WO4 MCHP_PINMUX(e, 4, f, periph)

#define PE5_GPIO MCHP_PINMUX(e, 5, gpio, gpio)

#define PE5A_EIC_EXTINT5 MCHP_PINMUX(e, 5, a, periph)

#define PE5D_SERCOM9_PAD3 MCHP_PINMUX(e, 5, d, periph)

#define PE5F_TCC2_WO5 MCHP_PINMUX(e, 5, f, periph)

#define PE6_GPIO MCHP_PINMUX(e, 6, gpio, gpio)

#define PE6A_EIC_EXTINT6 MCHP_PINMUX(e, 6, a, periph)

#define PE6B_ADC0_AIN10 MCHP_PINMUX(e, 6, b, periph)

#define PE7_GPIO MCHP_PINMUX(e, 7, gpio, gpio)

#define PE7A_EIC_EXTINT7 MCHP_PINMUX(e, 7, a, periph)

#define PE7B_ADC0_AIN11 MCHP_PINMUX(e, 7, b, periph)

#define PE8_GPIO MCHP_PINMUX(e, 8, gpio, gpio)

#define PE8A_EIC_EXTINT8 MCHP_PINMUX(e, 8, a, periph)

#define PE8B_ADC0_AIN12 MCHP_PINMUX(e, 8, b, periph)

#define PE9_GPIO MCHP_PINMUX(e, 9, gpio, gpio)

#define PE9A_EIC_EXTINT9 MCHP_PINMUX(e, 9, a, periph)

#define PE9B_ADC0_AIN13 MCHP_PINMUX(e, 9, b, periph)

#define PE10_GPIO MCHP_PINMUX(e, 10, gpio, gpio)

#define PE10A_EIC_EXTINT10 MCHP_PINMUX(e, 10, a, periph)

#define PE10B_ADC0_AIN14 MCHP_PINMUX(e, 10, b, periph)

#define PE11_GPIO MCHP_PINMUX(e, 11, gpio, gpio)

#define PE11A_EIC_EXTINT11 MCHP_PINMUX(e, 11, a, periph)

#define PE11B_ADC0_AIN15 MCHP_PINMUX(e, 11, b, periph)

#define PF0_GPIO MCHP_PINMUX(f, 0, gpio, gpio)

#define PF0A_EIC_EXTINT1 MCHP_PINMUX(f, 0, a, periph)

#define PF0P_PTC_DRV30 MCHP_PINMUX(f, 0, p, periph)

#define PF1_GPIO MCHP_PINMUX(f, 1, gpio, gpio)

#define PF1A_EIC_EXTINT1 MCHP_PINMUX(f, 1, a, periph)

#define PF1P_PTC_DRV31 MCHP_PINMUX(f, 1, p, periph)

#define PF2_GPIO MCHP_PINMUX(f, 2, gpio, gpio)

#define PF2A_EIC_EXTINT2 MCHP_PINMUX(f, 2, a, periph)

#define PF2P_PTC_DRV29 MCHP_PINMUX(f, 2, p, periph)

#define PF3_GPIO MCHP_PINMUX(f, 3, gpio, gpio)

#define PF3A_EIC_EXTINT3 MCHP_PINMUX(f, 3, a, periph)

#define PF3P_PTC_DRV28 MCHP_PINMUX(f, 3, p, periph)

#define PF4_GPIO MCHP_PINMUX(f, 4, gpio, gpio)

#define PF4A_EIC_EXTINT4 MCHP_PINMUX(f, 4, a, periph)

#define PF4P_PTC_DRV27 MCHP_PINMUX(f, 4, p, periph)

#define PF5_GPIO MCHP_PINMUX(f, 5, gpio, gpio)

#define PF5A_EIC_EXTINT5 MCHP_PINMUX(f, 5, a, periph)

#define PF5P_PTC_DRV21 MCHP_PINMUX(f, 5, p, periph)

#define PF6_GPIO MCHP_PINMUX(f, 6, gpio, gpio)

#define PF6A_EIC_EXTINT6 MCHP_PINMUX(f, 6, a, periph)

#define PF6P_PTC_DRV26 MCHP_PINMUX(f, 6, p, periph)

#define PF7_GPIO MCHP_PINMUX(f, 7, gpio, gpio)

#define PF7A_EIC_EXTINT7 MCHP_PINMUX(f, 7, a, periph)

#define PF7P_PTC_DRV25 MCHP_PINMUX(f, 7, p, periph)

#define PF8_GPIO MCHP_PINMUX(f, 8, gpio, gpio)

#define PF8A_EIC_EXTINT8 MCHP_PINMUX(f, 8, a, periph)

#define PF8P_PTC_DRV24 MCHP_PINMUX(f, 8, p, periph)

#define PG0_GPIO MCHP_PINMUX(g, 0, gpio, gpio)

#define PG0A_EIC_EXTINT0 MCHP_PINMUX(g, 0, a, periph)

#define PG0D_SERCOM6_PAD2 MCHP_PINMUX(g, 0, d, periph)

#define PG0E_EBI_A17 MCHP_PINMUX(g, 0, e, periph)

#define PG0H_SQI1_DATA1 MCHP_PINMUX(g, 0, h, periph)

#define PG0I_SDMMC1_SDDAT1 MCHP_PINMUX(g, 0, i, periph)

#define PG1_GPIO MCHP_PINMUX(g, 1, gpio, gpio)

#define PG1A_EIC_EXTINT1 MCHP_PINMUX(g, 1, a, periph)

#define PG1D_SERCOM6_PAD3 MCHP_PINMUX(g, 1, d, periph)

#define PG1E_EBI_A16 MCHP_PINMUX(g, 1, e, periph)

#define PG1H_SQI1_DATA2 MCHP_PINMUX(g, 1, h, periph)

#define PG1I_SDMMC1_SDDAT2 MCHP_PINMUX(g, 1, i, periph)

#define PG2_GPIO MCHP_PINMUX(g, 2, gpio, gpio)

#define PG2A_EIC_EXTINT2 MCHP_PINMUX(g, 2, a, periph)

#define PG2E_EBI_A15 MCHP_PINMUX(g, 2, e, periph)

#define PG2H_SQI1_DATA3 MCHP_PINMUX(g, 2, h, periph)

#define PG2I_SDMMC1_SDDAT3 MCHP_PINMUX(g, 2, i, periph)

#define PG3_GPIO MCHP_PINMUX(g, 3, gpio, gpio)

#define PG3A_EIC_EXTINT3 MCHP_PINMUX(g, 3, a, periph)

#define PG3E_EBI_A11 MCHP_PINMUX(g, 3, e, periph)

#define PG3H_SQI1_CS0 MCHP_PINMUX(g, 3, h, periph)

#define PG3I_SDMMC1_SDCMD MCHP_PINMUX(g, 3, i, periph)

#define PG4_GPIO MCHP_PINMUX(g, 4, gpio, gpio)

#define PG4A_EIC_EXTINT4 MCHP_PINMUX(g, 4, a, periph)

#define PG4E_EBI_NWE_NWR0 MCHP_PINMUX(g, 4, e, periph)

#define PG5_GPIO MCHP_PINMUX(g, 5, gpio, gpio)

#define PG5A_EIC_EXTINT5 MCHP_PINMUX(g, 5, a, periph)

#define PG5F_TCC9_WO0 MCHP_PINMUX(g, 5, f, periph)

#define PG6_GPIO MCHP_PINMUX(g, 6, gpio, gpio)

#define PG6A_EIC_EXTINT6 MCHP_PINMUX(g, 6, a, periph)

#define PG6F_TCC9_WO1 MCHP_PINMUX(g, 6, f, periph)

#define PG7_GPIO MCHP_PINMUX(g, 7, gpio, gpio)

#define PG7A_EIC_EXTINT7 MCHP_PINMUX(g, 7, a, periph)

#define PG7F_TCC9_WO2 MCHP_PINMUX(g, 7, f, periph)

#define PG8_GPIO MCHP_PINMUX(g, 8, gpio, gpio)

#define PG8A_EIC_EXTINT8 MCHP_PINMUX(g, 8, a, periph)

#define PG9_GPIO MCHP_PINMUX(g, 9, gpio, gpio)

#define PG9A_EIC_EXTINT9 MCHP_PINMUX(g, 9, a, periph)

#define PG9F_TCC9_WO3 MCHP_PINMUX(g, 9, f, periph)

#define PG10_GPIO MCHP_PINMUX(g, 10, gpio, gpio)

#define PG10A_EIC_EXTINT10 MCHP_PINMUX(g, 10, a, periph)

#define PG10F_TCC9_WO4 MCHP_PINMUX(g, 10, f, periph)

#define PG11_GPIO MCHP_PINMUX(g, 11, gpio, gpio)

#define PG11A_EIC_EXTINT11 MCHP_PINMUX(g, 11, a, periph)

#define PG11F_TCC9_WO5 MCHP_PINMUX(g, 11, f, periph)

#endif /* MICROCHIP_PIC32CZ8110CA80208_PINCTRL_H_ */
